export const CATEGORY_META = {
  west: { label: '西方主导', short: '规则先发', color: '#315d8a' },
  un: { label: '联合国体系', short: '全球公共性', color: '#3b7b6d' },
  south: { label: '全球南方 / 新兴市场', short: '能力与代表性', color: '#b45f45' },
  regional: { label: '区域专项', short: '落地与试验', color: '#8a6a35' },
}

export const TYPE_META = {
  organization: '常设组织 / 伙伴关系',
  process: '政治进程 / 峰会机制',
  platform: '知识与政策平台',
  framework: '战略 / 规范性文件',
  workingGroup: '工作组 / 合作板块',
  institute: '研究与能力中心',
}

export const MECHANISMS = [
  {
    id: 'gpai',
    category: 'west',
    name: 'GPAI',
    zh: '全球人工智能伙伴关系',
    type: 'organization',
    year: 2020,
    base: 'OECD 托管的多利益相关方伙伴关系',
    scope: '跨区域',
    status: '运行中 · 2024 年重构',
    maturity: '成熟',
    lead: '最初由 G7 推动；现与 OECD 的 AI 工作整合',
    members: '成员政府 + 专家社群；2024 年形成“GPAI 综合伙伴关系”',
    mandate: '把可信 AI 原则转化为研究、政策建议与跨国项目，连接政府、产业、学界和公民社会。',
    why: '它是“政策原则—专家网络—项目执行”之间最完整的桥梁之一，也是西方主导机制向更多经济体扩容的主要接口。',
    limits: '不制定有法律约束力的全球规则；议程与资源仍受主要出资国影响。',
    outputs: ['专家工作组', '应用型项目', '政策建议', '成员部长级会议'],
    scores: { reach: 4, authority: 3, execution: 4, south: 3 },
    source: { label: 'OECD.AI · GPAI', url: 'https://oecd.ai/en/about/gpai' },
  },
  {
    id: 'oecd-ai',
    category: 'west',
    name: 'OECD.AI',
    zh: 'OECD 人工智能政策观测站',
    type: 'platform',
    year: 2020,
    base: 'OECD 在线政策基础设施',
    scope: '全球数据，OECD 规则中心',
    status: '运行中',
    maturity: '成熟',
    lead: 'OECD 秘书处与成员、伙伴经济体',
    members: '不是会员制组织；服务政府与多利益相关方',
    mandate: '汇总政策、指标、事件与工具，支撑 OECD AI 原则、定义、分类和跨法域比较。',
    why: '它的影响力不靠“发号施令”，而靠统一词汇、指标和证据口径；很多法规与治理框架沿用了 OECD 的 AI 定义。',
    limits: '知识平台不等于监督机构；数据覆盖与政策叙事可能更贴近 OECD 经济体。',
    outputs: ['政策数据库', 'AI 事件监测', '工具与指标目录', '跨国研究'],
    scores: { reach: 5, authority: 3, execution: 3, south: 2 },
    source: { label: 'OECD.AI 官方站', url: 'https://oecd.ai/en/' },
  },
  {
    id: 'safety-summits',
    category: 'west',
    name: 'HAIP × AI Safety Summits',
    zh: '广岛 AI 进程 × 布莱奇利峰会机制',
    type: 'process',
    year: 2023,
    base: 'G7 进程 + 主办国接力峰会',
    scope: '全球邀约，议程由少数技术强国先发',
    status: '持续演进',
    maturity: '发展中',
    lead: 'G7 主席国；英国发起的 AI Safety Summit 系列及后续主办国',
    members: '无统一会员名册；政府、前沿模型公司、研究者按届参与',
    mandate: '广岛进程聚焦先进 AI 的国际指导原则、企业行为准则和报告框架；安全峰会聚焦前沿模型风险、评测与国际科学协作。',
    why: '两条线共同把“前沿模型安全”推上元首和部长议程，但不是同一个组织：前者更偏 G7 软法，后者更偏峰会协调。',
    limits: '自愿承诺居多；代表性、跟踪问责与对开源模型的适用方式仍有争议。',
    outputs: ['国际指导原则', '企业行为准则', '报告框架', '峰会宣言与安全研究网络'],
    scores: { reach: 4, authority: 3, execution: 3, south: 2 },
    source: { label: 'G7 广岛进程（日本外务省）', url: 'https://www.mofa.go.jp/policy/economy/summit/hiroshima23/en/documents/' },
    source2: { label: '布莱奇利宣言（英国政府）', url: 'https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration' },
  },
  {
    id: 'unesco',
    category: 'un',
    name: 'UNESCO AI Ethics',
    zh: 'UNESCO《人工智能伦理问题建议书》及实施体系',
    type: 'framework',
    year: 2021,
    base: '联合国专门机构的规范性文件与实施工具',
    scope: 'UNESCO 193 个会员国',
    status: '实施中',
    maturity: '成熟',
    lead: 'UNESCO 社会与人文科学部门',
    members: '由会员国大会通过；并非一个名为“AI 伦理委员会”的常设监管机关',
    mandate: '以人权、尊严、公平、环境和文化多样性为基础，为各国提供伦理影响评估与准备度评估方法。',
    why: '它是首个获得全球会员国通过的 AI 伦理规范性文书，优势在价值共识和发展中国家能力建设。',
    limits: '建议书原则上自愿实施，国家落实深度不一；UNESCO 不直接执法。',
    outputs: ['伦理建议书', '准备度评估 RAM', '伦理影响评估 EIA', '全球伦理治理观测站'],
    correction: '名称校正：官方核心不是“UNESCO 人工智能伦理委员会”，而是建议书、实施工具与观测站组成的体系。',
    scores: { reach: 5, authority: 4, execution: 3, south: 5 },
    source: { label: 'UNESCO 建议书', url: 'https://www.unesco.org/en/legal-affairs/recommendation-ethics-artificial-intelligence' },
  },
  {
    id: 'itu',
    category: 'un',
    name: 'ITU · AI for Good',
    zh: '国际电信联盟 AI 标准与“AI 向善”平台',
    type: 'organization',
    year: 2017,
    base: '联合国专门机构 + 标准化与召集平台',
    scope: '全球',
    status: '运行中',
    maturity: '成熟',
    lead: 'ITU，联动数十个联合国机构',
    members: 'ITU 会员国、部门成员、学界与联合国伙伴',
    mandate: '通过 ITU-T 标准工作和 AI for Good 平台，把技术标准、可持续发展场景与跨机构合作连接起来。',
    why: '与偏伦理的 UNESCO 不同，ITU 的比较优势是通信基础设施、技术标准和产业工程接口。',
    limits: 'AI for Good 本身更像召集与项目平台；技术标准的采用仍依赖成员和市场。',
    outputs: ['技术标准', '焦点组', 'AI for Good 峰会', '可持续发展用例'],
    scores: { reach: 5, authority: 4, execution: 4, south: 4 },
    source: { label: 'ITU · AI for Good', url: 'https://aiforgood.itu.int/' },
  },
  {
    id: 'gdc',
    category: 'un',
    name: 'Global Digital Compact',
    zh: '联合国全球数字契约',
    type: 'framework',
    year: 2024,
    base: '联合国大会通过的全球政治承诺',
    scope: '联合国全体会员国',
    status: '进入实施与评审阶段',
    maturity: '发展中',
    lead: '联合国大会与数字和新兴技术办公室',
    members: '由 193 个会员国谈判；同时开放多利益相关方参与和自愿背书',
    mandate: '把数字鸿沟、数据治理、网络空间和 AI 治理放进同一全球框架，并建立国际 AI 科学小组和全球政策对话。',
    why: '这是目前最具普遍代表性的 AI 政治框架，也为联合国层面的常设科学评估与政策对话提供制度入口。',
    limits: '它是契约而非条约；真正影响取决于科学小组、政策对话、融资和国家实施。',
    outputs: ['五大目标', '国际 AI 科学小组', '全球 AI 政策对话', '能力建设与融资议程'],
    scores: { reach: 5, authority: 4, execution: 2, south: 5 },
    source: { label: '联合国全球数字契约', url: 'https://www.un.org/global-digital-compact/en' },
  },
  {
    id: 'waico',
    category: 'south',
    name: 'WAICO',
    zh: '世界人工智能合作组织',
    type: 'organization',
    year: 2026,
    base: '新设政府间合作组织',
    scope: '全球，面向全球南方扩展',
    status: '2026-07-17 成立 · 早期建制',
    maturity: '新生',
    lead: '中国倡议，总部拟设上海',
    members: '首批 29 个国家签署成立协定（以各国后续批准和官方名录为准）',
    mandate: '促进 AI 国际合作、普惠发展、能力建设与全球治理，降低技术、算力和人才鸿沟。',
    why: '它提供了一条区别于 G7/OECD 路线、以主权平等和发展权为重点的政府间制度通道。',
    limits: '章程、治理结构、预算、成员义务和项目机制尚处公开信息早期；现阶段不宜高估执行力。',
    outputs: ['成立协定', '后续治理架构待公布', '预期能力建设与合作项目'],
    scores: { reach: 3, authority: 3, execution: 1, south: 5 },
    source: { label: '印度尼西亚经济统筹部', url: 'https://ekon.go.id/publikasi/detail/7017/indonesia-resmi-jadi-founding-member-waico-menko-airlangga-tegaskan-komitmen-untuk-jembatani-kesenjangan-ai-global' },
  },
  {
    id: 'sco',
    category: 'south',
    name: 'SCO AI Cooperation',
    zh: '上合组织人工智能合作机制',
    type: 'process',
    year: 2023,
    base: '区域组织内的元首声明与合作议程',
    scope: '欧亚区域',
    status: '议程深化中',
    maturity: '发展中',
    lead: '上合组织成员国',
    members: '上合组织成员国；可联动观察员和对话伙伴',
    mandate: '围绕发展与治理、能力建设、技术应用、标准和安全深化政府间合作。',
    why: '上合机制能把 AI 嵌入既有的元首外交、产业与区域合作网络，政治动员力高于单一项目平台。',
    limits: '尚无独立 AI 常设机构；合作成果多散见于声明、论坛和双多边项目。',
    outputs: ['元首声明', '能力建设倡议', '会议与示范合作'],
    scores: { reach: 3, authority: 3, execution: 2, south: 5 },
    source: { label: '上合组织 AI 合作声明', url: 'https://chn.sectsco.org/20250902/1964324.html' },
  },
  {
    id: 'au',
    category: 'south',
    name: 'AU Continental AI Strategy',
    zh: '非盟《大陆人工智能战略》',
    type: 'framework',
    year: 2024,
    base: '非盟大陆级战略',
    scope: '非洲大陆',
    status: '实施起步',
    maturity: '发展中',
    lead: '非盟委员会与成员国',
    members: '非盟成员国',
    mandate: '以“以非洲为中心、发展导向、负责任”为主线，推进治理、技能、数据、基础设施、研发和区域协同。',
    why: '它不是复制欧美风险治理，而是把语言、数据主权、基础设施和发展优先级放到 AI 战略中心。',
    limits: '成员国能力和资源差异大；大陆战略需要国家立法、融资与区域经济共同体承接。',
    outputs: ['大陆战略', '政策协调', '能力与基础设施路线', '区域合作'],
    scores: { reach: 4, authority: 3, execution: 2, south: 5 },
    source: { label: '非盟大陆 AI 战略', url: 'https://au.int/en/documents/20240809/continental-artificial-intelligence-strategy' },
  },
  {
    id: 'elac',
    category: 'south',
    name: 'eLAC',
    zh: '拉美和加勒比数字议程 AI 合作框架',
    type: 'workingGroup',
    year: 2005,
    base: '部长级数字议程与滚动行动计划',
    scope: '拉美和加勒比',
    status: 'eLAC2026 实施中',
    maturity: '成熟',
    lead: '区域部长级会议；联合国拉加经委会提供技术支持',
    members: '区域各国政府及多利益相关方观察员',
    mandate: '以数字发展为大框架，在新兴技术、数字治理、公共部门转型中推进 AI 政策协同、能力建设和经验共享。',
    why: 'eLAC 的价值在“长期滚动”：AI 不是孤立倡议，而是进入数字基础设施、生产力和政府转型的区域机制。',
    limits: '不是 AI 专门组织；目标较宽，落实依赖工作组和各国政策资源。',
    outputs: ['数字议程', '部长级会议', '工作组', '指标与政策实验'],
    scores: { reach: 3, authority: 3, execution: 3, south: 5 },
    source: { label: 'eLAC2026 官方议程', url: 'https://elac.cepal.org/agenda-gobernanza.html' },
  },
  {
    id: 'brics',
    category: 'south',
    name: 'BRICS AI Study Group',
    zh: '金砖国家人工智能研究组 / 合作议程',
    type: 'workingGroup',
    year: 2021,
    base: '金砖通信与科技合作下的专题机制',
    scope: '金砖成员与伙伴网络',
    status: '持续扩展',
    maturity: '发展中',
    lead: '金砖轮值主席国、通信与科技主管部门',
    members: '金砖成员国及相关研究和产业网络',
    mandate: '围绕关键技术、算法、标准、应用场景、治理和全球南方能力共享开展研究与合作。',
    why: '成员扩容后，它可能成为连接大型新兴经济体算力、数据、科研和政策议程的重要接口。',
    limits: '“研究组”“工作组”和峰会倡议并非单一强机构；项目连续性受轮值主席国影响。',
    outputs: ['专题研究组', '部长宣言', '联合研究与交流', '治理立场协调'],
    scores: { reach: 4, authority: 2, execution: 2, south: 5 },
    source: { label: 'BRICS 未来网络研究院 AI 组', url: 'https://www.bifn.org/study_groups/ai_sg.html' },
  },
  {
    id: 'ircai',
    category: 'regional',
    name: 'IRCAI',
    zh: 'UNESCO 赞助下的国际人工智能研究中心',
    type: 'institute',
    year: 2020,
    base: '设于斯洛文尼亚的 UNESCO 二类中心',
    scope: '全球研究网络，欧洲为基地',
    status: '运行中',
    maturity: '成熟',
    lead: '斯洛文尼亚政府、Jožef Stefan Institute；UNESCO 赞助体系',
    members: '研究中心与全球合作网络，不是国家会员制组织',
    mandate: '用 AI 推进联合国可持续发展目标，连接研究、项目发现、资金和规模化应用。',
    why: '它代表“研究—SDG 项目—全球网络”的落地路径，而非政府间规则谈判。',
    limits: '“欧洲—拉美 AI 研究所”并非其准确官方定位；治理约束力和区域政策协调功能有限。',
    outputs: ['研究网络', '全球 Top 100', 'SDG 项目', '能力与政策活动'],
    correction: '名称校正：IRCAI 是位于斯洛文尼亚、面向全球的 UNESCO 二类中心，不是专门的“欧洲—拉美研究所”。',
    scores: { reach: 4, authority: 2, execution: 4, south: 4 },
    source: { label: 'IRCAI 官方站', url: 'https://ircai.org/' },
  },
  {
    id: 'asean',
    category: 'regional',
    name: 'ASEAN AI Governance',
    zh: '东盟数字总体规划与 AI 治理协作',
    type: 'workingGroup',
    year: 2021,
    base: '东盟数字部长机制下的区域规则协作',
    scope: '东南亚',
    status: '指南迭代中',
    maturity: '成熟',
    lead: '东盟数字部长会议及相关工作组',
    members: '东盟成员国，联动产业和对话伙伴',
    mandate: '在数字一体化框架中推进可互操作的 AI 治理与伦理指南，并扩展到生成式 AI 风险。',
    why: '东盟偏好务实、行业友好和渐进式协调，是在欧美硬法与纯自愿原则之间寻找区域互操作性的典型。',
    limits: '指南不具强制约束力；成员国法制和数字能力差异显著。',
    outputs: ['AI 治理与伦理指南', '生成式 AI 扩展指南', '区域工作组', '能力建设'],
    scores: { reach: 3, authority: 3, execution: 4, south: 5 },
    source: { label: 'ASEAN AI 指南', url: 'https://asean.org/book/asean-guide-on-ai-governance-and-ethics/' },
  },
  {
    id: 'arab-ai-alliance',
    category: 'regional',
    name: 'Arab AI Alliance',
    zh: '阿拉伯人工智能联盟（非 GCC 官方机构）',
    type: 'platform',
    year: 2024,
    base: '新兴行业 / 专家倡议',
    scope: '阿拉伯地区',
    status: '倡议早期 · 官方性有限',
    maturity: '新生',
    lead: '区域专家与产业网络',
    members: '公开会员与治理结构信息有限',
    mandate: '推动阿拉伯地区负责任 AI、研究协作、人才和本地语境下的治理讨论。',
    why: '海湾国家在算力、资本和国家战略上高度活跃，但截至当前，没有足够证据把这一倡议称为“海合会官方 AI 联盟”。',
    limits: '权威性、成员构成、项目和与 GCC 的正式关系均需进一步核验；不应与 GCC 政府间机制等同。',
    outputs: ['倡议网络', '政策与产业讨论', '潜在研究合作'],
    correction: '名称校正：建议写作“阿拉伯人工智能联盟（行业倡议）”；若讨论海湾六国，应写“GCC 国家 AI 合作与国家战略集群”。',
    scores: { reach: 2, authority: 1, execution: 1, south: 4 },
    source: { label: 'Arab AI Alliance', url: 'https://arabaialliance.com/' },
  },
]

export const SCORE_META = [
  { id: 'reach', label: '覆盖广度', note: '地理与成员代表性' },
  { id: 'authority', label: '制度权威', note: '政治授权与规范分量' },
  { id: 'execution', label: '执行抓手', note: '项目、标准、资金与跟踪' },
  { id: 'south', label: '南方参与', note: '发展中经济体议程能见度' },
]

export const TIMELINE = [
  { year: '2017', label: 'ITU 启动 AI for Good' },
  { year: '2019', label: 'OECD AI 原则获通过' },
  { year: '2020', label: 'GPAI、OECD.AI 与 IRCAI 成形' },
  { year: '2021', label: 'UNESCO 建议书；东盟数字总体规划' },
  { year: '2023', label: '广岛 AI 进程与布莱奇利峰会' },
  { year: '2024', label: '全球数字契约、非盟战略、ASEAN AI 指南' },
  { year: '2025', label: '区域机制扩容，安全报告框架继续推进' },
  { year: '2026', label: 'WAICO 在上海成立；UN 科学小组进入运行期' },
]

export const TAKEAWAYS = [
  {
    no: '01',
    title: '全球 AI 治理不是一座“世界政府”，而是一套制度拼图。',
    body: 'OECD 擅长定义和指标，UNESCO 擅长伦理共识，ITU 擅长标准，G7 机制聚焦前沿安全，区域组织负责把原则翻译成本地政策。',
  },
  {
    no: '02',
    title: '真正的分野是“风险优先”还是“发展与能力优先”。',
    body: '西方先发机制更关注前沿模型风险与可信规则；非盟、eLAC、东盟、金砖和 WAICO 更强调算力、技能、本地数据与参与权。两者不是非此即彼。',
  },
  {
    no: '03',
    title: '软法并不等于没有影响力。',
    body: '自愿原则可以通过采购、标准、企业报告、资金条件和监管互认进入硬约束；判断机制影响力，要看它能否形成持续的执行接口。',
  },
]
