export const REPORT_DATE = '2026-07-21'

export const SOURCES = {
  openclawChannels: {
    name: 'OpenClaw 官方文档：Chat channels',
    publisher: 'OpenClaw',
    date: '2026-07-21 抓取',
    url: 'https://docs.openclaw.ai/channels',
    tier: '官方一手',
  },
  openclawGithub: {
    name: 'openclaw/openclaw GitHub API',
    publisher: 'GitHub',
    date: '2026-07-21 快照',
    url: 'https://api.github.com/repos/openclaw/openclaw',
    tier: '平台一手',
  },
  openclawNpm: {
    name: 'npm downloads API：openclaw',
    publisher: 'npm',
    date: '2026-06-21—2026-07-20',
    url: 'https://api.npmjs.org/downloads/point/2026-06-21:2026-07-20/openclaw',
    tier: '平台一手',
  },
  openclawSystems: {
    name: 'How Peter Steinberger built OpenClaw',
    publisher: 'Fast Company',
    date: '2026-06-18',
    url: 'https://www.fastcompany.com/91550800/how-peter-steinberger-built-openclaw',
    tier: '媒体采访',
  },
  clawhubApi: {
    name: 'ClawHub 公共 Skill 目录 API',
    publisher: 'ClawHub / OpenClaw',
    date: '2026-07-21 全量分页快照',
    url: 'https://clawhub.ai/api/v1/skills?limit=200&sort=downloads',
    tier: '平台一手 + 本站分类',
  },
  clawhubTelemetry: {
    name: 'ClawHub 安装遥测口径',
    publisher: 'OpenClaw',
    date: '2026-07-21 抓取',
    url: 'https://docs.openclaw.ai/clawhub/telemetry',
    tier: '官方一手',
  },
  agentSkillsPaper: {
    name: 'Agent Skills: A Data-Driven Analysis of Claude Skills',
    publisher: 'Bosch Research / CMU（arXiv 预印本）',
    date: '数据截至 2026-02-05',
    url: 'https://arxiv.org/abs/2602.08004',
    tier: '学术研究',
  },
  skillselion: {
    name: 'The State of AI Agent Skills 2026',
    publisher: 'Skillselion',
    date: '2026-07-13',
    url: 'https://skillselion.com/state-of-ai-agent-skills-2026',
    tier: '第三方目录',
  },
  questmobile: {
    name: '2026 年 AI 应用市场发展半年报',
    publisher: 'QuestMobile 研究院',
    date: '2026-07-14',
    url: 'https://www.questmobile.com.cn/research/report/2076954943839809537/',
    tier: '第三方监测',
  },
  aicpb: {
    name: '全球 AI 产品榜·应用榜（App）',
    publisher: 'AICPB',
    date: '2026 年 6 月版',
    url: 'https://www.aicpb.com/zh/ai-rankings/products/global-ai-rankings/apps',
    tier: '第三方监测',
  },
  workbuddySkills: {
    name: 'WorkBuddy：新建任务栏与技能',
    publisher: '腾讯云',
    date: '2026-07-16',
    url: 'https://cloud.tencent.com/document/product/1831/134391',
    tier: '官方一手',
  },
  workbuddyChannels: {
    name: 'WorkBuddy：助理（远程任务）',
    publisher: '腾讯云',
    date: '2026-07-20',
    url: 'https://cloud.tencent.com/document/product/1831/134392',
    tier: '官方一手',
  },
  workbuddyYuanbao: {
    name: 'WorkBuddy：元宝机器人接入指南',
    publisher: '腾讯云',
    date: '2026-07-20',
    url: 'https://cloud.tencent.com/document/product/1831/134437',
    tier: '官方一手',
  },
  tencentQ1: {
    name: '腾讯 2026 年第一季度业绩',
    publisher: '腾讯',
    date: '截至 2026-03-31',
    url: 'https://static.www.tencent.com/uploads/2026/05/13/aaeed028d215a9612da4b41aca17708b.pdf',
    tier: '公司披露',
  },
  xiaowei: {
    name: '微信 AI 助手“小微”灰度上线',
    publisher: 'IT之家（引述腾讯客服与微信开发者信息）',
    date: '2026-06-20',
    url: 'https://www.ithome.com/0/966/534.htm',
    tier: '媒体核验',
  },
  tokenChina: {
    name: 'Token 成为支撑智能经济有序运转的价值标尺',
    publisher: '数字中国建设峰会 / 人民邮电报',
    date: '2026-06-23',
    url: 'https://www.digitalchina.gov.cn/2026/szzg/xyzx/202606/t20260623_5336965.htm',
    tier: '权威报告转引',
  },
  agentTokenPaper: {
    name: 'How Do AI Agents Spend Your Money?',
    publisher: 'Stanford / MIT / Michigan 等（arXiv 预印本）',
    date: '2026-04',
    url: 'https://arxiv.org/abs/2604.22750',
    tier: '学术研究',
  },
  agentMarket: {
    name: 'China Enterprise Agentic AI Market Size & Outlook',
    publisher: 'Grand View Research',
    date: '2025—2030 预测',
    url: 'https://www.grandviewresearch.com/horizon/outlook/enterprise-agentic-ai-market/china',
    tier: '第三方市场预测',
  },
}

export const METRICS = [
  {
    id: 'openclaw-channels',
    group: 'supply',
    label: 'OpenClaw 已文档化 Channel',
    value: '29 个',
    signal: '官方清单',
    tone: 'cyan',
    definition: 'OpenClaw 官方 Channels 页面列出的消息、短信、电话与 WebChat 入口总数。',
    method: '逐项计数：3 个 core + 1 个 bundled plugin + 22 个 official plugin + 3 个 external plugin。',
    boundary: '这是可接入渠道数量，不是已启用渠道、活跃连接数或消息发送量。',
    sourceIds: ['openclawChannels'],
  },
  {
    id: 'communication-skills',
    group: 'supply',
    label: 'ClawHub 通信类 Skill',
    value: '666 个',
    signal: '本站测算',
    tone: 'blue',
    definition: '名称与描述明确指向邮件、IM、消息通知、SMS/iMessage 或电话执行的唯一 Skill slug。',
    method: '全量分页抓取 ClawHub 公共目录，按 slug 去重；排除文档发布、账号验证、纯文案及只有平台名但无通信动作的条目。',
    boundary: '不是官方分类；相似功能仍可能重复。若只看 IM/消息/SMS/电话并排除邮件，则为 287 个。',
    sourceIds: ['clawhubApi'],
  },
  {
    id: 'communication-downloads',
    group: 'adoption',
    label: '通信 Skill 累计下载',
    value: '128.7 万次',
    signal: '本站测算',
    tone: 'blue',
    definition: '上述 666 个唯一 slug 在 ClawHub 展示的 downloads 字段之和。',
    method: '379 个邮件类与 287 个非邮件通信类汇总；精确快照值 1,286,804。',
    boundary: '下载不是独立用户、活跃用户或运行调用；同一用户、自动化与升级可能重复贡献。',
    sourceIds: ['clawhubApi'],
  },
  {
    id: 'communication-installs',
    group: 'adoption',
    label: '通信 Skill 可观测安装',
    value: '4.18 万次',
    signal: '遥测样本',
    tone: 'violet',
    definition: 'ClawHub 对上述通信 Skill 展示的 installs 字段之和，精确快照值 41,765。',
    method: '登录 CLI 且未关闭遥测时，上报 best-effort 安装事件；按 Skill 汇总后求和。',
    boundary: '关闭遥测或未登录的安装不会被记录；跨 Skill 求和不能去重为全站唯一用户。',
    sourceIds: ['clawhubApi', 'clawhubTelemetry'],
  },
  {
    id: 'skill-ecosystem',
    group: 'supply',
    label: '跨生态 Agent Skill',
    value: '60,540 个',
    signal: '第三方目录',
    tone: 'violet',
    definition: 'Skillselion 在 skills.sh 与 GitHub 来源中收录的 Agent Skill 条目。',
    method: '第三方目录截至 2026-07-13 的自动更新计数。',
    boundary: '不是去重后的独立能力数，也不是 ClawHub 单一市场规模；论文显示 46.3% 条目与其他条目共享规范化名称。',
    sourceIds: ['skillselion', 'agentSkillsPaper'],
  },
  {
    id: 'ecosystem-installs',
    group: 'adoption',
    label: '工具生态累计安装',
    value: '1.3 亿次',
    signal: '组合口径',
    tone: 'amber',
    definition: 'Skillselion 收录的 Skill、MCP Server、Marketplace 等 81,616 个工具的 combined installs。',
    method: '第三方目录汇总注册表安装数据。',
    boundary: '不能写成“Skill 调用 1.3 亿次”：它不只包含 Skill，也不是运行时函数调用或任务执行次数。',
    sourceIds: ['skillselion'],
  },
  {
    id: 'team-communication',
    group: 'supply',
    label: '论文样本：Team Communication',
    value: '698 个',
    signal: '学术样本',
    tone: 'cyan',
    definition: '论文对 skills.sh 40,285 条 Skill 的分类结果，范围含 Slack/Discord 消息、邮件、日历安排与会议管理。',
    method: '2026-02-05 冻结样本；Team Communication 占全部条目的 1.7%，平均每个 Skill 196 次安装。',
    boundary: '口径比“IM/短信/电话”更宽，且不是当前全市场实时计数。698×196≈13.7 万仅为基于四舍五入均值的推算。',
    sourceIds: ['agentSkillsPaper'],
  },
  {
    id: 'openclaw-distribution',
    group: 'adoption',
    label: 'OpenClaw 近 30 日 npm 下载',
    value: '1,183.8 万次',
    signal: '平台 API',
    tone: 'green',
    definition: 'npm 对 openclaw 包在 2026-06-21 至 2026-07-20 的下载请求计数。',
    method: 'npm point downloads API 返回 11,838,000。',
    boundary: '包含首次安装、升级、CI、镜像与自动化拉取，不能等同 OpenClaw 用户数。',
    sourceIds: ['openclawNpm'],
  },
  {
    id: 'openclaw-systems',
    group: 'adoption',
    label: 'OpenClaw 运行系统估计',
    value: '约 50 万套',
    signal: '媒体口径',
    tone: 'green',
    definition: 'Fast Company 人物报道所述，全球约有半百万套 systems 正在运行 OpenClaw。',
    method: '媒体采访口径，未公开去重方法与统计后台。',
    boundary: 'system/instance 不是 unique user 或 MAU；自托管产品目前无统一官方用户数。',
    sourceIds: ['openclawSystems'],
  },
  {
    id: 'github-stars',
    group: 'adoption',
    label: 'OpenClaw GitHub Stars',
    value: '38.36 万',
    signal: '平台快照',
    tone: 'green',
    definition: 'GitHub 官方 API 返回的 openclaw/openclaw stargazers_count。',
    method: '2026-07-21 09:55（北京时间）读取为 383,608；同刻 forks 为 80,584。',
    boundary: 'Star 是关注度代理，不是安装、使用或付费用户。',
    sourceIds: ['openclawGithub'],
  },
  {
    id: 'doubao-mau',
    group: 'audience',
    label: '豆包国内活跃用户',
    value: '3.82 亿',
    signal: '第三方监测',
    tone: 'red',
    definition: 'QuestMobile 披露的 2026 年 6 月豆包活跃用户规模。',
    method: '与千问 1.67 亿、DeepSeek 1.29 亿采用同一 QuestMobile 监测口径。',
    boundary: '不与 AICPB 的全球 App MAU 混算；两家机构覆盖范围、去重与估算方法不同。',
    sourceIds: ['questmobile'],
  },
  {
    id: 'ai-native-apps',
    group: 'audience',
    label: '中国 AI 原生 App 整体活跃',
    value: '4.99 亿',
    signal: '第三方监测',
    tone: 'red',
    definition: 'QuestMobile 披露的 2026 年 6 月中国 AI 原生 App 整体活跃用户规模。',
    method: '同比增长 85.4%；同份报告给出的 AI 原生 App 月人均使用次数为 92.7 次。',
    boundary: '是 AI 原生 App 行业合计，不是去重后的全体 AI 用户，也不是单个产品 MAU。',
    sourceIds: ['questmobile'],
  },
  {
    id: 'doubao-global',
    group: 'audience',
    label: '豆包全球 AI App 排名',
    value: '第 2 名',
    signal: '第三方榜单',
    tone: 'red',
    definition: 'AICPB 2026 年 6 月全球 AI 应用榜按 App MAU 排名；豆包估计 MAU 3.2431 亿。',
    method: '榜单第 1 为 ChatGPT；豆包列第 2。',
    boundary: '“全球第二”只适用于 AICPB 的 AI App MAU 榜单，不能扩写为所有 AI 产品或综合市场份额第二。',
    sourceIds: ['aicpb'],
  },
  {
    id: 'doubao-depth',
    group: 'audience',
    label: '豆包 10 分钟以上用户占比',
    value: '27.5%',
    signal: '第三方监测',
    tone: 'red',
    definition: 'QuestMobile 统计的 2026 年 6 月豆包当月使用时长达到 10 分钟以上的活跃用户占比。',
    method: '同一报告给出的 DeepSeek、Kimi 对照值分别为 30.0% 和 26.1%；豆包较 2025 年同期增加 2.2 个百分点。',
    boundary: '这是使用深度分层占比，不是日均使用时长、留存率或付费率。',
    sourceIds: ['questmobile'],
  },
  {
    id: 'workbuddy-growth',
    group: 'audience',
    label: 'WorkBuddy 三个月活跃增幅',
    value: '+115.3%',
    signal: '第三方监测',
    tone: 'red',
    definition: 'QuestMobile 披露的腾讯 WorkBuddy 近三个月活跃用户规模增幅。',
    method: '比较期为报告所述“近三个月”，披露增幅、未披露绝对活跃用户数。',
    boundary: '这是相对增幅，不是 MAU 115.3 万，也不能推出留存或付费用户规模。',
    sourceIds: ['questmobile'],
  },
  {
    id: 'workbuddy-skills',
    group: 'supply',
    label: 'WorkBuddy 内置技能包',
    value: '20+ 个',
    signal: '官方产品口径',
    tone: 'cyan',
    definition: '腾讯云产品文档披露的 WorkBuddy 内置技能包数量级，覆盖文档、报表、海报和文件整理等。',
    method: '产品文档直接披露，同时说明兼容 OpenClaw 社区技能导入与自然语言创建自定义技能。',
    boundary: '20+ 是全部内置技能包，不是通信类 Skill 数量，也不代表用户实际启用或调用次数。',
    sourceIds: ['workbuddySkills'],
  },
  {
    id: 'workbuddy-entrances',
    group: 'supply',
    label: 'WorkBuddy 远程消息入口',
    value: '5+1 个',
    signal: '官方文档合并',
    tone: 'cyan',
    definition: '远程任务概述列出的微信、企业微信、QQ、钉钉、飞书 5 个平台，加上独立的元宝机器人接入指南。',
    method: '对腾讯云两份当前文档交叉计数，合并为 5 个主平台 + 1 个元宝入口。',
    boundary: '页面表格、概述文案和产品版本可能不同步；因此比直接写“固定六大 Channel”更严谨。',
    sourceIds: ['workbuddyChannels', 'workbuddyYuanbao'],
  },
  {
    id: 'wechat-mau',
    group: 'audience',
    label: '微信及 WeChat 合并 MAU',
    value: '14.32 亿',
    signal: '公司披露',
    tone: 'red',
    definition: '腾讯披露的微信及 WeChat 合并月活跃账户数。',
    method: '截至 2026-03-31，较上年同期 14.02 亿增长 2%。',
    boundary: '是账户数而非自然人数，更不是微信“小微”的灰度用户数。',
    sourceIds: ['tencentQ1'],
  },
  {
    id: 'token-china',
    group: 'economy',
    label: '中国日均 Token 调用',
    value: '>140 万亿',
    signal: '报告口径',
    tone: 'amber',
    definition: '《Token 驱动智能经济研究报告（2026年）》披露的我国日均 Token 调用量。',
    method: '截至 2026 年 3 月；报道表述为两年内超千倍增长。',
    boundary: '覆盖中国总体模型调用，不等于通信 Skill Token，也不能用来推算单个 Channel 收入。',
    sourceIds: ['tokenChina'],
  },
  {
    id: 'agent-token',
    group: 'economy',
    label: 'Agentic Coding Token 放大',
    value: '约 1,000×',
    signal: '研究样本',
    tone: 'amber',
    definition: '论文样本中，Agentic Coding 任务相较 code reasoning 与 code chat 的 Token 消耗量级。',
    method: '研究分析 8 个前沿模型在编码代理任务中的执行轨迹；同一任务不同运行最高相差 30 倍。',
    boundary: '只证明特定编码代理样本中的放大效应，不能写成“通信 Skill 平均提升 Token 1000 倍”。',
    sourceIds: ['agentTokenPaper'],
  },
  {
    id: 'agent-market',
    group: 'economy',
    label: '中国企业 Agentic AI 市场预测',
    value: '$19.38 亿',
    signal: '2030E',
    tone: 'amber',
    definition: 'Grand View Research 对中国 enterprise agentic AI 市场 2030 年收入的预测。',
    method: '2024 年估计为 1.932 亿美元，2025—2030 年预测 CAGR 为 47.5%。',
    boundary: '这是相邻的企业 Agentic AI 市场，不是 Skill 市场收入，更不是通信 Skill 市场规模。',
    sourceIds: ['agentMarket'],
  },
]

export const COMMUNICATION_CATEGORIES = [
  { name: '邮件', skills: 379, downloads: 636400, installs: 20370 },
  { name: '电话 / Voice Call', skills: 29, downloads: 223907, installs: 7343 },
  { name: '办公与社区 IM', skills: 111, downloads: 217163, installs: 7073 },
  { name: '消费级 IM', skills: 75, downloads: 132569, installs: 4411 },
  { name: '通用消息与通知', skills: 45, downloads: 57545, installs: 1974 },
  { name: 'SMS / iMessage', skills: 27, downloads: 19220, installs: 594 },
]

export const CHANNEL_SEGMENTS = [
  { label: 'Core 内置', value: 3, examples: 'iMessage、Telegram、WebChat' },
  { label: 'Bundled', value: 1, examples: 'Reef' },
  { label: 'Official plugin', value: 22, examples: 'Slack、Feishu、SMS、Voice Call 等' },
  { label: 'External plugin', value: 3, examples: 'WeChat、Yuanbao、Zalo ClawBot' },
]

export const CASES = [
  {
    id: 'openclaw',
    kicker: '开源底座',
    name: 'OpenClaw',
    headline: '把通信入口扩成跨平台 Agent Gateway',
    summary: '29 个 Channel 已覆盖 IM、协同软件、短信、电话和 WebChat；但生态热度不等于真实用户，用户规模只能用运行系统、npm 下载与 GitHub 关注度做代理。',
    facts: ['29 个文档化 Channel', '近 30 日 npm 下载 1,183.8 万', '约 50 万运行系统（媒体口径）'],
    sourceIds: ['openclawChannels', 'openclawNpm', 'openclawSystems'],
  },
  {
    id: 'workbuddy',
    kicker: '办公 Agent',
    name: '腾讯 WorkBuddy',
    headline: '把消息入口变成远程任务控制面',
    summary: '官方概述列出微信、企业微信、QQ、钉钉、飞书 5 个平台，另有元宝机器人独立接入指南，因此可描述为 5+1 个远程入口；不同文档与版本的展示并不完全一致。',
    facts: ['近三个月活跃规模 +115.3%', '5 个平台 + 1 个元宝入口', '内置 20+ 技能包'],
    sourceIds: ['questmobile', 'workbuddyChannels', 'workbuddyYuanbao', 'workbuddySkills'],
  },
  {
    id: 'xiaowei',
    kicker: '超级入口',
    name: '微信“小微”',
    headline: '从对话回答迈向原生通信动作',
    summary: '灰度能力包括文字/语音操作微信、发送消息、拨打电话与调起小程序。微信本体拥有 14.32 亿合并 MAU，但腾讯未披露“小微”灰度用户数，二者不能画等号。',
    facts: ['微信及 WeChat 14.32 亿 MAU', '可发消息 / 拨电话', '灰度用户数未披露'],
    sourceIds: ['tencentQ1', 'xiaowei'],
  },
  {
    id: 'doubao',
    kicker: '大众入口',
    name: '豆包',
    headline: '先取得用户规模，再向 Agent 执行层延展',
    summary: 'QuestMobile 监测其国内活跃用户为 3.82 亿；AICPB 的全球 AI App 榜单将其列为第 2。两个数据来自不同机构，只能分别使用，不能拼成同一趋势序列。',
    facts: ['国内活跃用户 3.82 亿', 'AICPB 全球 AI App 第 2', '10 分钟以上用户占比 27.5%'],
    sourceIds: ['questmobile', 'aicpb'],
  },
]

export const RECOMMENDATIONS = [
  ['先做结果指标', '不要只数 Channel 与 Skill；同时跟踪送达率、有效回复率、任务完成率、人工接管率、投诉率和单位成功任务成本。'],
  ['Skill 与 Channel 解耦', '把“催收、预约、客服升级”等业务流程做成可复用 Skill，把平台认证、会话和消息格式留给 Channel。'],
  ['从第一天建设权限', '采用最小权限、收件人白名单、高风险确认、频控、全链路审计与一键撤销。'],
  ['把 Token 当成本层', 'Token 会随规划、工具调用、重试和长上下文放大，但商业计费最终应向有效会话或完成任务靠拢。'],
]

export function sourceList(ids) {
  return ids.map((id) => ({ id, ...SOURCES[id] }))
}
