export const MARKET_GROUPS = [
  { id: 'all', label: '全部市场' },
  { id: 'rates', label: '利率' },
  { id: 'fx', label: '外汇' },
  { id: 'equity', label: '股票' },
  { id: 'fixed-income', label: '债券' },
  { id: 'crypto', label: '加密' },
  { id: 'options', label: '期权' },
]

export const MARKET_TYPES = [
  { id: 'all', label: '现货 + 衍生品' },
  { id: 'spot', label: '只看现货' },
  { id: 'derivative', label: '只看衍生品' },
]

export const BASIS_META = {
  cash: { label: '现货成交额', tone: 'emerald' },
  notional: { label: '名义金额', tone: 'amber' },
  premium: { label: '权利金估算', tone: 'violet' },
  mixed: { label: '混合口径', tone: 'blue' },
}

export const SOURCES = [
  { id: 'bis-fx', label: 'BIS · 2025 全球外汇调查', url: 'https://www.bis.org/publications/202509-commentary-otc-derivatives' },
  { id: 'bis-ir', label: 'BIS · 2025 利率衍生品', url: 'https://www.bis.org/publications/qr-202512/goodbye-libor-hello-basis-traders-unpacking-surge-global-interest-rate-derivatives-turnover' },
  { id: 'sifma-ust', label: 'SIFMA · 2025 美国国债', url: 'https://www.sifma.org/wp-content/uploads/2025/10/SIFMA-Research-Quarterly-Fixed-Income-IT-4Q25.pdf' },
  { id: 'cboe-us', label: 'Cboe · 2025 美国股票市场', url: 'https://www.cboe.com/insights/posts/2025-u-s-equities-year-in-review' },
  { id: 'wfe-equity', label: 'WFE · 全球股票订单簿', url: 'https://focus.world-exchanges.org/statistics/articles/trends-value-share-trading-through-electronic-order-books-eob' },
  { id: 'cme', label: 'CME · 市场日均名义金额', url: 'https://www.cmegroup.com/markets.html' },
  { id: 'occ', label: 'OCC · 2025 美国期权', url: 'https://www.theocc.com/newsroom/views/2026/01-05-occ-annual-2025-and-december-2025-volume' },
  { id: 'coingecko-annual', label: 'CoinGecko · 2025 加密市场', url: 'https://www.coingecko.com/research/publications/2025-annual-crypto-report' },
  { id: 'coingecko-rwa', label: 'CoinGecko · 2026 TradFi on Crypto Exchanges', url: 'https://www.coingecko.com/research/publications/tradfi-on-crypto-exchanges-report-2026' },
]

export const MARKETS = [
  {
    id: 'exchange-ir-derivatives',
    name: '场内利率衍生品',
    shortName: '场内利率',
    dailyUsdBn: 17400,
    group: 'rates',
    type: 'derivative',
    basis: 'notional',
    period: '2025-04 日均',
    sourceId: 'bis-ir',
    definition: '交易所里的短期利率期货、政府债券期货及相应期权。',
    takeaway: '全球最大的一组日成交名义金额，主要由短期利率期货和国债期货推动。',
    caveat: '一张合约可代表很大本金；名义金额远大于实际保证金和每日盈亏。',
    compositionKind: 'qualitative',
    composition: [
      { name: '短期利率期货', note: 'SOFR、ESTR、SONIA 等，最大头' },
      { name: '政府债券期货', note: '美国、德国、日本等国债期限品种' },
      { name: '期权', note: '利率期货期权与国债期货期权' },
    ],
  },
  {
    id: 'global-fx',
    name: '全球外汇市场',
    shortName: '全部外汇',
    dailyUsdBn: 9600,
    group: 'fx',
    type: 'mixed',
    basis: 'mixed',
    period: '2025-04 日均',
    sourceId: 'bis-fx',
    definition: '银行、机构与企业之间的现货、掉期、远期和期权交易总和。',
    takeaway: '外汇市场最大部分是掉期，不是我们日常理解的即时换汇。',
    caveat: '包含约 3 万亿美元现货，也包含约 6.6 万亿美元衍生品；不能再与“外汇现货”相加。',
    compositionKind: 'value',
    composition: [
      { name: '外汇掉期', value: 4000 },
      { name: '外汇现货', value: 3000 },
      { name: '远期', value: 1800 },
      { name: '外汇期权', value: 672 },
      { name: '货币掉期及其他', value: 128 },
    ],
  },
  {
    id: 'otc-ir-derivatives',
    name: '场外利率衍生品',
    shortName: '场外利率',
    dailyUsdBn: 7900,
    group: 'rates',
    type: 'derivative',
    basis: 'notional',
    period: '2025-04 日均',
    sourceId: 'bis-ir',
    definition: '银行和机构通过场外协议交易的利率掉期、远期利率协议与期权。',
    takeaway: '隔夜指数掉期 OIS 已占约三分之二。',
    caveat: '约 24% 属于回转、压缩等非直接价格发现交易。',
    compositionKind: 'value',
    composition: [
      { name: 'OIS', value: 5100 },
      { name: '其他利率掉期', value: 1900 },
      { name: 'FRA', value: 617 },
      { name: '利率期权及其他', value: 283 },
    ],
  },
  {
    id: 'fx-spot',
    name: '全球外汇现货',
    shortName: '外汇现货',
    dailyUsdBn: 3000,
    group: 'fx',
    type: 'spot',
    basis: 'cash',
    period: '2025-04 日均',
    sourceId: 'bis-fx',
    definition: '按当前汇率完成两种货币交换的现货交易。',
    takeaway: '即便只看现货，外汇规模仍远大于股票或加密现货。',
    caveat: '它已经包含在“全球外汇市场 9.6 万亿美元”中。',
    compositionKind: 'qualitative',
    composition: [
      { name: '美元相关货币对', note: '美元出现在约 89% 的外汇交易一侧' },
      { name: '欧元、日元、英镑', note: '最主要的非美元货币' },
      { name: '人民币及其他货币', note: '份额较小但体量仍很大' },
    ],
  },
  {
    id: 'cme-equity-index',
    name: 'CME 股指期货与期权',
    shortName: 'CME 股指',
    dailyUsdBn: 1500,
    group: 'equity',
    type: 'derivative',
    basis: 'notional',
    period: '当前公开日均',
    sourceId: 'cme',
    definition: 'CME 上以标普 500、纳指 100、罗素 2000、道指等为标的的期货与期权。',
    takeaway: '单一交易所的股指衍生品名义成交额即可超过全球股票公开订单簿。',
    caveat: '构成占比按合约张数计算，不代表相同的名义金额占比。',
    compositionKind: 'share',
    composition: [
      { name: '标普 500 系列', value: 59 },
      { name: '纳指 100 系列', value: 33 },
      { name: '罗素 2000', value: 4 },
      { name: '道指及其他', value: 4 },
    ],
  },
  {
    id: 'us-equities',
    name: '美国股票全部场所',
    shortName: '美国股票',
    dailyUsdBn: 1100,
    group: 'equity',
    type: 'spot',
    basis: 'cash',
    period: '2025 日均',
    sourceId: 'cboe-us',
    definition: '美国上市股票和 ETF 在交易所、做市商、暗池及其他场所的合并成交。',
    takeaway: '超过一半的股票成交量发生在交易所之外。',
    caveat: '场所构成按成交股数统计；低价股会令股数占比与美元占比产生差异。',
    compositionKind: 'share',
    composition: [
      { name: '场外 / TRF', value: 50.6 },
      { name: 'NYSE / ICE', value: 19.0 },
      { name: 'Nasdaq', value: 14.4 },
      { name: 'Cboe', value: 9.4 },
      { name: '其他交易所', value: 6.6 },
    ],
  },
  {
    id: 'us-treasury',
    name: '美国国债现货',
    shortName: '美国国债',
    dailyUsdBn: 1055.5,
    group: 'fixed-income',
    type: 'spot',
    basis: 'cash',
    period: '2025 日均',
    sourceId: 'sifma-ust',
    definition: '短期国库券、中长期附息国债、通胀保值债券与浮息国债的二级市场交易。',
    takeaway: '中长期附息国债贡献约八成现货成交。',
    caveat: '这是美国国债现货，不包括国债期货、回购和利率掉期。',
    compositionKind: 'value',
    composition: [
      { name: '中长期附息国债', value: 860 },
      { name: '短期国库券', value: 185 },
      { name: '浮息国债', value: 6.5 },
      { name: 'TIPS', value: 4 },
    ],
  },
  {
    id: 'global-equity-orderbooks',
    name: '全球股票公开订单簿',
    shortName: '全球股票订单簿',
    dailyUsdBn: 680,
    group: 'equity',
    type: 'spot',
    basis: 'cash',
    period: '2025 Q1 日均估算',
    sourceId: 'wfe-equity',
    definition: 'WFE 统计的全球交易所电子订单簿股票成交。',
    takeaway: '美洲约一半，亚太约四成，欧洲、中东和非洲约一成以内。',
    caveat: '不完整包含美国场外做市、暗池和所有跨市场成交，不能与美国“全部场所”直接相加。',
    compositionKind: 'share',
    composition: [
      { name: '美洲', value: 52 },
      { name: '亚太', value: 41 },
      { name: '欧洲、中东和非洲', value: 7 },
    ],
  },
  {
    id: 'crypto-derivatives',
    name: '全球加密衍生品',
    shortName: '加密衍生品',
    dailyUsdBn: 305,
    group: 'crypto',
    type: 'derivative',
    basis: 'notional',
    period: '2025 全年折算',
    sourceId: 'coingecko-annual',
    definition: '中心化、链上和传统受监管场所中的加密永续、交割合约与期权。',
    takeaway: '永续合约贡献绝大部分成交。',
    caveat: '包含下方“加密永续”与 CME 加密衍生品，不能重复相加。',
    compositionKind: 'value',
    composition: [
      { name: '永续合约', value: 255 },
      { name: '交割合约、期权等', value: 50 },
    ],
  },
  {
    id: 'crypto-perpetuals',
    name: '全球加密永续合约',
    shortName: '加密永续',
    dailyUsdBn: 255,
    group: 'crypto',
    type: 'derivative',
    basis: 'notional',
    period: '2025 全年折算',
    sourceId: 'coingecko-annual',
    definition: '没有固定到期日、通过资金费率锚定现货价格的加密衍生品。',
    takeaway: '中心化交易所仍占约 93%，链上永续约占 7%。',
    caveat: '同一批保证金可以反复开平仓，因此成交额不代表新增资金。',
    compositionKind: 'value',
    composition: [
      { name: '中心化交易所', value: 236.2 },
      { name: '链上 DEX', value: 18.4 },
    ],
  },
  {
    id: 'crypto-spot',
    name: '全球加密现货',
    shortName: '加密现货',
    dailyUsdBn: 69,
    group: 'crypto',
    type: 'spot',
    basis: 'cash',
    period: '2025 全年折算',
    sourceId: 'coingecko-annual',
    definition: 'BTC、ETH、稳定币和其他代币在中心化交易所与链上 DEX 的即时交易。',
    takeaway: '永续合约日成交通常约为加密现货的 3 至 5 倍。',
    caveat: '不同数据商覆盖的交易所不同，活跃日与冷清日可以相差数倍。',
    compositionKind: 'qualitative',
    composition: [
      { name: '中心化交易所', note: '常态约 85%–90%' },
      { name: '链上 DEX', note: '常态约 10%–15%，高峰超过 20%' },
      { name: '主要资产', note: 'BTC、ETH 与稳定币计价交易对' },
    ],
  },
  {
    id: 'us-listed-options',
    name: '美国上市期权权利金',
    shortName: '美国期权',
    dailyUsdBn: 37,
    group: 'options',
    type: 'derivative',
    basis: 'premium',
    period: '2025 日均估算',
    sourceId: 'occ',
    definition: '美国个股、ETF与指数期权买方实际支付的权利金估算。',
    takeaway: '每天约 6,060 万张；指数期权张数少，但单张平均权利金更高。',
    caveat: '约 370 亿美元不是底层资产名义金额；期权对应的股票或指数风险规模远大于权利金。',
    compositionKind: 'share',
    composition: [
      { name: '个股期权', value: 54.4 },
      { name: 'ETF 期权', value: 37.3 },
      { name: '指数期权', value: 8.3 },
    ],
  },
  {
    id: 'cme-crypto',
    name: 'CME 加密期货与期权',
    shortName: 'CME 加密',
    dailyUsdBn: 12,
    group: 'crypto',
    type: 'derivative',
    basis: 'notional',
    period: '2025 日均',
    sourceId: 'cme',
    definition: 'CME 上受监管的比特币、以太坊等期货与期权。',
    takeaway: '规模小于加密原生交易所，但机构化和清算结构不同。',
    caveat: '已包含在部分“全球加密衍生品”统计中。',
    compositionKind: 'qualitative',
    composition: [
      { name: 'Bitcoin 系列', note: '标准与微型期货、期权' },
      { name: 'Ether 系列', note: '标准与微型期货、期权' },
      { name: '其他资产', note: 'SOL、XRP 等新增产品' },
    ],
  },
  {
    id: 'rwa-perpetuals',
    name: '加密平台 TradFi / RWA 永续',
    shortName: 'RWA 永续',
    dailyUsdBn: 11.2,
    group: 'crypto',
    type: 'derivative',
    basis: 'notional',
    period: '2026-05 月均折算',
    sourceId: 'coingecko-rwa',
    definition: '加密交易所中跟踪股票、商品、外汇和上市前资产的永续合约。',
    takeaway: '2026 年 5 月月成交约 3,472 亿美元，但股票永续只是其中一部分。',
    caveat: '这是快速增长的新市场，月度波动极大，不能把单月数据当长期均值。',
    compositionKind: 'qualitative',
    composition: [
      { name: '外汇与商品', note: 'RWA 永续的重要组成' },
      { name: '股票永续', note: '2026-05 约 340 亿美元/月' },
      { name: 'Pre-IPO', note: '规模小、价格发现风险更高' },
    ],
  },
  {
    id: 'tokenized-equity-perpetuals',
    name: '代币化股票永续',
    shortName: '股票永续',
    dailyUsdBn: 1.1,
    group: 'equity',
    type: 'derivative',
    basis: 'notional',
    period: '2026-05 月均折算',
    sourceId: 'coingecko-rwa',
    definition: '加密平台上跟踪 Nvidia、Tesla 等股票价格、但不提供股票所有权的永续合约。',
    takeaway: '月成交约 340 亿美元，仍不到传统股票市场的 1%。',
    caveat: '没有底层股票所有权；闭市期间还存在指数价格、溢价和流动性风险。',
    compositionKind: 'qualitative',
    composition: [
      { name: '热门股票', note: 'Nvidia、Tesla、Micron 等' },
      { name: '主要平台', note: 'Binance、Hyperliquid 等' },
      { name: '相对规模', note: '不足传统股票成交的 1%' },
    ],
  },
]

export const STOCK_MARKETS = [
  {
    id: 'us',
    name: '美国全部股票场所',
    dailyUsdBn: 1100,
    period: '2025 日均',
    note: '包含交易所与场外；下列场所比例按成交股数，不宜机械换算成美元。',
    sourceId: 'cboe-us',
    segments: [
      { name: '场外 / TRF', share: 50.6, detail: '其中约 81.3% 为主经纪商/做市商成交，约 18.7% 为 ATS 或暗池' },
      { name: 'NYSE / ICE', share: 19.0, detail: 'NYSE、NYSE Arca、NYSE American、NYSE National 等' },
      { name: 'Nasdaq', share: 14.4, detail: 'Nasdaq主市场、BX、PSX' },
      { name: 'Cboe', share: 9.4, detail: 'EDGX、BZX、BYX、EDGA' },
      { name: '其他', share: 6.6, detail: 'IEX、MEMX、MIAX、NSX、LTSE 等' },
    ],
  },
  {
    id: 'china',
    name: '中国 A 股',
    dailyUsdBn: 238,
    period: '2025 全年折算',
    note: '全年超过 405 万亿元人民币；交易活跃度随月份明显变化。',
    sourceLabel: '上交所 / 深交所年度统计',
    sourceUrl: 'https://english.sse.com.cn/news/newsrelease/voice/c/c_20251224_10802769.shtml',
    segments: [
      { name: '深圳证券交易所', share: 58, detail: '主板、创业板、ETF 等；股票成交通常高于上交所' },
      { name: '上海证券交易所', share: 42, detail: '主板、科创板、ETF 等' },
      { name: '北京证券交易所', share: 0.3, detail: '中小企业市场，成交占比不足 1%；此处份额仅作量级提示' },
    ],
  },
  {
    id: 'japan',
    name: '日本交易所集团',
    dailyUsdBn: 45,
    period: '2025 约数',
    note: '主要集中于东京证券交易所；年度与财年口径会产生差异。',
    sourceLabel: 'JPX 2025 交易概览',
    sourceUrl: 'https://www.jpx.co.jp/english/corporate/news/news-releases/0063/20251230-01.html',
    segments: [
      { name: 'Prime', share: 76, detail: '大型成熟公司，贡献绝大多数股票成交' },
      { name: 'Standard / Growth', share: 7, detail: '中型与成长型公司' },
      { name: 'ETF / REIT / 其他', share: 17, detail: 'ETF、ETN、REIT 与场外大宗等' },
    ],
  },
  {
    id: 'hong-kong',
    name: '香港交易所',
    dailyUsdBn: 32,
    period: '2025 日均',
    note: '现金市场日均 2,498 亿港元；南向港股通已是重要成交来源。',
    sourceLabel: 'HKEX 2025 市场回顾',
    sourceUrl: 'https://www.hkexgroup.com/Media-Centre/Insight/Insight/2026/HKEX-Insight/What-Drove-Hong-Kong-Markets-in-2025?sc_lang=en',
    segments: [
      { name: '主板股票', share: 70, detail: '大型公司与中资企业为主；份额为结构示意' },
      { name: '南向交易', share: 24, detail: '2025 日均成交 1,211 亿港元，但双边统计不可直接视为净流入' },
      { name: 'ETF / REIT / 其他', share: 6, detail: '结构性产品和其他证券' },
    ],
  },
  {
    id: 'euronext',
    name: 'Euronext',
    dailyUsdBn: 14.2,
    period: '2025 日均',
    note: '覆盖巴黎、阿姆斯特丹、米兰、布鲁塞尔、都柏林、里斯本、奥斯陆等市场。',
    sourceLabel: 'Euronext 2025 全年业绩',
    sourceUrl: 'https://www.euronext.com/sites/default/files/2026-02/Euronext%20-%20PR%20-%20Q4%20and%20FY%202025%20results.pdf',
    segments: [
      { name: '股票', share: 83, detail: '多个欧洲国家的大中型上市公司' },
      { name: 'ETF / 基金等', share: 17, detail: '结构示意；Euronext 统计口径含多种现金产品' },
    ],
  },
  {
    id: 'india-nse',
    name: '印度 NSE',
    dailyUsdBn: 13.3,
    period: 'FY2024–25 日均',
    note: '现金市场日均 112,963 crore 卢比；1 crore 等于 1,000 万卢比。',
    sourceLabel: 'NSE FY2024–25 年报',
    sourceUrl: 'https://nsearchives.nseindia.com/web/sites/default/files/inline-files/NSE_Integrated_Annual_Report_for_FY_2024-25.pdf',
    segments: [
      { name: 'NSE 现金股票', share: 93.6, detail: '占印度交易所股票现金市场绝大部分' },
      { name: '其他', share: 6.4, detail: 'BSE 等市场；这里只用于展示印度市场集中度' },
    ],
  },
  {
    id: 'deutsche-boerse',
    name: '德意志交易所股票',
    dailyUsdBn: 6.2,
    period: '2025 全年折算',
    note: '仅股票约 13,777 亿欧元/年；另有大量 ETF、ETN、债券和证书成交。',
    sourceLabel: 'Deutsche Börse 2025 现金市场统计',
    sourceUrl: 'https://www.cashmarket.deutsche-boerse.com/cash-en/Stay-Informed/newsroom/press-releases/Deutsche-B-rse-Cash-Market-Annual-Statistics-2025-and-Turnover-Figures-December-4881848',
    segments: [
      { name: 'Xetra 股票', share: 98, detail: '德国股票公开订单簿的核心场所' },
      { name: '法兰克福股票', share: 2, detail: '专家撮合等交易' },
    ],
  },
]

export const PRODUCT_CONCEPTS = [
  {
    id: 'spot',
    name: '现货',
    question: '我买到了什么？',
    answer: '资产本身',
    example: '买 10 股苹果，账户里持有 10 股。',
    ownership: '通常有所有权或实益权益',
    expiry: '没有到期日',
    leverage: '现金买入通常没有',
    maxLoss: '最多跌到资产接近零',
  },
  {
    id: 'futures',
    name: '期货',
    question: '我答应了什么？',
    answer: '未来按规则结算',
    example: '约定月底按合约价格结算苹果价格。',
    ownership: '通常不直接拥有底层资产',
    expiry: '有固定到期日',
    leverage: '通常有保证金杠杆',
    maxLoss: '可能超过初始保证金',
  },
  {
    id: 'perpetual',
    name: '永续合约',
    question: '为什么能一直开着？',
    answer: '用资金费率代替到期',
    example: '不买股票，只对价格涨跌持续结算。',
    ownership: '没有底层资产所有权',
    expiry: '没有固定到期日',
    leverage: '通常较高，可能强平',
    maxLoss: '保证金可迅速亏完',
  },
  {
    id: 'options',
    name: '期权',
    question: '我买到了什么？',
    answer: '未来选择买卖的权利',
    example: '先付订金，未来可以按约定价买，也可放弃。',
    ownership: '买方获得权利，卖方承担义务',
    expiry: '有到期日',
    leverage: '权利金形成非线性杠杆',
    maxLoss: '买方通常最多损失权利金',
  },
]

export function sourceFor(item) {
  if (item.sourceUrl) return { label: item.sourceLabel, url: item.sourceUrl }
  return SOURCES.find((source) => source.id === item.sourceId)
}
