export const DYNASTIES = [
  { id: 'tang', label: '唐', range: '618—907', color: '#b4532a', count: '名录不全', note: '进士科在唐固定下来，“状元”起初多指第一名。徐松《登科记考》能复原一部分名次，缺榜、同名和后世追称都很多，不宜写成一份完整总名单。' },
  { id: 'song', label: '宋', range: '960—1279', color: '#c6974c', count: '约 118', note: '通行名录把北宋、南宋殿试第一合计为一百一十余人。科次、改名和是否算特奏名，各书仍有出入，页面只收事迹能对上《宋史》或登科录的人。' },
  { id: 'yuan', label: '辽金元', range: '916—1368', color: '#7186a2', count: '另册', note: '辽、金有进士。元朝科举时开时停，蒙古、色目为右榜，汉人、南人为左榜，左右榜各有第一，不能直接并进明清那份状元总数。' },
  { id: 'ming', label: '明', range: '1368—1644', color: '#9a3b32', count: '89 科', note: '通行口径是明朝殿试 89 科。洪武三十年南北榜要把被废的春榜和重开的夏榜分开算；黄观在靖难后被除名，有的名单因此漏掉他。' },
  { id: 'qing', label: '清', range: '1644—1905', color: '#3f5c4e', count: '114 人', note: '清朝开科 112 次，状元 114 人：顺治年间满汉分榜，多出两名。光绪三十年（1904）刘春霖是最后一科，次年科举停罢。' },
]

export const STEPS = [
  { name: '乡试', title: '举人', first: '解元', text: '省一级考试。取中者为举人，第一名称解元。明清乡试通常三年一科，遇庆典另开恩科。' },
  { name: '会试', title: '贡士', first: '会元', text: '举人进京再考。取中者为贡士，第一名称会元。会试决定谁有资格参加殿试，名次还不是最终状元。' },
  { name: '殿试', title: '进士', first: '状元', text: '皇帝策问。一甲三名赐进士及第：第一状元，第二榜眼，第三探花。二甲赐进士出身，三甲赐同进士出身。明清原则上殿试不再黜落。' },
]

export const PEOPLE = [
  {
    id: 'sun-fujia', dynasty: 'tang', year: 622, name: '孙伏伽', place: '贝州', exam: '武德五年',
    headline: '常被称作唐代第一位进士第一',
    summary: '武德五年登第，后来做到大理少卿、民部侍郎。唐初进士科刚成为常科，当时文书并不稳定使用“状元”二字。',
    after: '以谏官知名，多次上疏论宫中游猎与赏罚。',
    fact: '两《唐书》有传，确认他是唐初进士。把他写成“中国历史上第一位状元”，依赖的是后世对“第一名”的追称。',
    caution: { level: '名号后起', title: '“第一位状元”是后设称号', text: '隋唐之际第一名的记载并不完整。孙伏伽适合作为进士科早期样本，不适合当成一份从他开始连续编号的总账起点。' },
    keywords: ['唐初', '进士', '第一名'],
    source: 'https://zh.wikisource.org/wiki/舊唐書/卷75',
    sourceLabel: '《旧唐书》本传',
  },
  {
    id: 'he-zhizhang', dynasty: 'tang', year: 695, name: '贺知章', place: '越州', exam: '证圣元年',
    headline: '诗名大于榜名的早期样本',
    summary: '《登科记考》把他列为证圣元年进士第一。他后来以文词、草书和“四明狂客”留在文学史里，榜次本身仍要回到登科记系统核对。',
    after: '官至秘书监，天宝初请为道士还乡。',
    fact: '李白《送贺宾客归越》写的是还乡，不是殿试。诗名与状元名次是两件事。',
    caution: { level: '名录复原', title: '唐榜很多靠《登科记考》复原', text: '徐松据笔记、方志和诗序补榜。贺知章这一条可以使用，但不宜说成当时就有一份官方“金榜扫描件”。' },
    keywords: ['登科记考', '诗人', '越州'],
    source: 'https://zh.wikipedia.org/wiki/%E8%B4%BA%E7%9F%A5%E7%AB%A0',
    sourceLabel: '贺知章条目',
  },
  {
    id: 'wang-wei', dynasty: 'tang', year: 721, name: '王维', place: '河东', exam: '开元九年',
    headline: '文学史上的王维，榜次仍有争议',
    summary: '《唐才子传》等后出材料说他开元九年进士第一。两《唐书》本传只确认进士及第，没有把“状元”写成定案。',
    after: '官终尚书右丞，诗画并传。',
    fact: '可以确定的是进士身份与文学成就。状元名次属于后出说法，页面把它标成争议，不放进已核名单。',
    caution: { level: '名次争议', title: '不要用一首诗反推他是状元', text: '《赋得清如玉壶冰》常被当成应试诗流传。作品真伪、是否即当年试题、名次是否第一，要分开核。' },
    keywords: ['争议', '开元', '诗人'],
    source: 'https://zh.wikisource.org/wiki/舊唐書/卷190下',
    sourceLabel: '《旧唐书·文苑传》',
  },
  {
    id: 'lv-mengzheng', dynasty: 'song', year: 977, name: '吕蒙正', place: '河南', exam: '太平兴国二年',
    headline: '状元后来两度入相',
    summary: '太平兴国二年进士第一，是宋初由殿试拔擢、再进入中枢的典型。他三次拜相，中间两次罢相，仕途并不等于一榜定终身。',
    after: '太宗、真宗两朝宰相，以持重和识人留名。',
    fact: '《宋史》本传写明他举进士第一。',
    caution: { level: '叙事夸张', title: '“破窑”故事不是登科录', text: '后世戏曲把吕蒙正写成寒窑苦读。早年贫困或有影子，完整的戏文情节不能当成太平兴国二年的史料。' },
    keywords: ['宰相', '宋初', '进士第一'],
    source: 'https://zh.wikisource.org/zh-hans/宋史/卷265',
    sourceLabel: '《宋史》本传',
  },
  {
    id: 'zhang-xiaoxiang', dynasty: 'song', year: 1154, name: '张孝祥', place: '历阳', exam: '绍兴二十四年',
    headline: '高宗读卷后拔为第一',
    summary: '绍兴二十四年进士。本传记载宋高宗读到他的卷子，擢为第一，授秘书省正字。他后来以词名世，《六州歌头》写的是中状元之后的时局，不是殿试卷。',
    after: '历任中书舍人、建康留守等，隆兴间力主恢复。',
    fact: '《宋史》说“高宗即擢孝祥为第一”。同榜名次争议主要来自秦桧与其子秦埙的关系，拔置经过应以本传为准。',
    caution: { level: '作品误植', title: '《念奴娇·过洞庭》不是殿试对策', text: '这首词写于后来过洞庭时。把它说成“状元卷”，是把文学代表作和考试文本叠在一起。' },
    keywords: ['高宗', '词人', '绍兴'],
    source: 'https://zh.wikisource.org/zh-hans/宋史/卷389',
    sourceLabel: '《宋史》本传',
  },
  {
    id: 'wen-tianxiang', dynasty: 'song', year: 1256, name: '文天祥', place: '吉州庐陵', exam: '宝祐四年',
    headline: '本列第五，理宗亲擢第一',
    summary: '宝祐四年五月殿试。详定官原拟第五，宋理宗改为第一。覆考检点试卷官王应麟称他的卷子“古谊若龟鉴，忠肝如铁石”。同榜还有谢枋得、陆秀夫。',
    after: '德祐以后组织抗元，至元十九年（1283）就义。',
    fact: '《宝祐四年登科录》留有策题、考官和文天祥对策。这是宋元状元里文献最完整的一份殿试文本。',
    caution: { level: '文本边界', title: '《过零丁洋》写在中状元二十年后', text: '祥兴元年（1279）被俘后的诗，不是宝祐四年的对策。两份文本都重要，时间不能并成一件事。' },
    keywords: ['对策', '王应麟', '宝祐'],
    image: '/images/zhuangyuan/wentianxiang.jpg',
    imageAlt: '文天祥线描立像',
    imageCredit: 'https://commons.wikimedia.org/wiki/File:Wen_Tianxiang.jpg',
    source: 'https://zh.wikisource.org/wiki/%E5%BE%A1%E8%A9%A6%E7%AD%96%E4%B8%80%E9%81%93%EF%BC%88%E6%9C%89%E9%A1%8C%EF%BC%89',
    sourceLabel: '维基文库《御试策》',
  },
  {
    id: 'wu-bozong', dynasty: 'ming', year: 1371, name: '吴伯宗', place: '金溪', exam: '洪武四年',
    headline: '明朝首科状元',
    summary: '洪武四年辛亥科是明朝第一次会试、殿试，吴伯宗以第一名授礼部员外郎。首科取士人数和后来的三年一科并不相同。',
    after: '曾出使安南，官至武英殿大学士。',
    fact: '《明史》本传确认洪武四年进士第一。',
    caution: { level: '口径', title: '首科不等于后来的标准流程', text: '洪武朝开科、停科反复多次。用清代“三年一科、殿试不黜落、授修撰”的流程回看洪武四年，会把制度写早。' },
    keywords: ['明朝首科', '洪武', '金溪'],
    source: 'https://zh.wikisource.org/zh-hans/明史/卷137',
    sourceLabel: '《明史》本传',
  },
  {
    id: 'huang-guan', dynasty: 'ming', year: 1391, name: '黄观', place: '贵池', exam: '洪武二十四年',
    headline: '会试、殿试皆第一，靖难后被除名',
    summary: '洪武二十四年会试第一、殿试第一，累官礼部右侍郎。建文朝改侍中。燕师渡江后他募兵上游，闻京师失守，投江而死。朱棣下令除其名籍。',
    after: '名籍被削，后来的状元名单因此常漏掉他。',
    fact: '《明史》写明“二十四年会试、廷试皆第一”，也写了投江与除名。',
    caution: { level: '名录残缺', title: '不要把他自动算成三元', text: '会元加状元有本传依据。乡试解元缺少同样硬的记载，所以他不是明代可以稳妥计入的“连中三元”。' },
    keywords: ['除名', '靖难', '会元'],
    source: 'https://zh.wikisource.org/zh-hans/明史/卷143',
    sourceLabel: '《明史》本传',
  },
  {
    id: 'shang-lu', dynasty: 'ming', year: 1445, name: '商辂', place: '淳安', exam: '正统十年',
    headline: '明代可以坐实的唯一三元',
    summary: '乡试、会试、殿试皆第一，正统十年状元。后来进入内阁，参与英宗、宪宗两朝政局，也经历夺门之变后的罢斥与复出。',
    after: '官至谨身殿大学士，卒谥文毅。',
    fact: '《明史》开卷即写“举乡试第一，正统十年会试、殿试皆第一”。三元在这里是三次第一的事实，不是美称。',
    caution: { level: '稀缺不是神话', title: '三元少，是因为三级考试各自排名', text: '乡试、会试、殿试的考生池和评判标准都不同。一个人三次第一罕见，但不需要再附加灵异或天命叙事。' },
    keywords: ['三元', '内阁', '正统'],
    source: 'https://zh.wikisource.org/zh-hans/明史/卷176',
    sourceLabel: '《明史》本传',
  },
  {
    id: 'yang-shen', dynasty: 'ming', year: 1511, name: '杨慎', place: '新都', exam: '正德六年',
    headline: '状元之后的命运由大礼议改写',
    summary: '正德六年状元，授翰林院修撰。嘉靖三年因大礼议率群臣哭谏，遭廷杖，谪戍云南永昌，从此几乎终身在戍所。',
    after: '在云南写作、编书，《升庵集》的篇幅远大于一纸殿试卷。',
    fact: '《明史》确认正德六年殿试第一，以及廷杖、永远充军。',
    caution: { level: '作品误植', title: '《临江仙》不是状元卷', text: '“滚滚长江东逝水”是他后来的词，清初毛宗岗本《三国演义》用它作卷首。词的流传很广，考试原文仍是正德六年的对策。' },
    keywords: ['大礼议', '云南', '升庵'],
    source: 'https://zh.wikisource.org/zh-hans/明史/卷192',
    sourceLabel: '《明史》本传',
  },
  {
    id: 'fu-yijian', dynasty: 'qing', year: 1646, name: '傅以渐', place: '聊城', exam: '顺治三年',
    headline: '清朝汉榜第一位状元',
    summary: '顺治三年丙戌科殿试第一，授弘文院修撰。入关之初的科次、满汉分榜和后来稳定的翰林体制还没有完全叠合。',
    after: '官至武英殿大学士，曾纂修《明史》《太宗实录》。',
    fact: '顺治三年是清入关后首科。傅以渐是这一科汉榜第一。满榜状元要到后来分榜时另计。',
    caution: { level: '口径', title: '114 人里包含分榜', text: '若只数汉人状元，会少于 114。页面采用“112 科、114 名”的通行口径，并单独标明分榜。' },
    keywords: ['清朝首科', '大学士', '聊城'],
    source: 'https://zh.wikipedia.org/zh-hans/%E5%82%85%E4%BB%A5%E6%B8%90',
    sourceLabel: '傅以渐条目',
  },
  {
    id: 'qian-qi', dynasty: 'qing', year: 1781, name: '钱棨', place: '长洲', exam: '乾隆四十六年',
    headline: '清代第一位连中三元',
    summary: '乾隆四十四年江苏乡试第一，四十六年会试、殿试皆第一。乾隆因此给江苏和考官题诗，三元再次变成朝廷公开谈论的事。',
    after: '授翰林院修撰，出任云南学政，死在任上。',
    fact: '乡试、会试、殿试三次第一都有科年可查，是清代两名三元里较早的一位。',
    caution: { level: '荣誉之后', title: '三元没有保证后来的官阶', text: '钱棨止于学政。状元的起家官是从六品修撰，之后的升迁仍看差遣、考语和年资。' },
    keywords: ['三元', '长洲', '乾隆'],
    source: 'https://zh.wikipedia.org/wiki/%E9%92%B1%E6%A3%A8',
    sourceLabel: '钱棨条目',
  },
  {
    id: 'chen-jichang', dynasty: 'qing', year: 1820, name: '陈继昌', place: '临桂', exam: '嘉庆二十五年',
    headline: '最后一位连中三元',
    summary: '嘉庆十八年广西乡试解元，二十五年会元、状元。他是清代第二位、也是最后一位三元，籍贯在广西临桂，不在江浙考生最密集的州县。',
    after: '授修撰，后任内阁中书、山东兖沂曹济道等职。',
    fact: '三次第一的科年清楚。此后直到 1905 年停科，没有再出现三元。',
    caution: { level: '地理标签', title: '江苏状元多，不等于别省没有第一', text: '清代 114 名状元里江苏 49 人，占最大份额。陈继昌说明名次仍可能出在配额和考场之外的省分。' },
    keywords: ['三元', '临桂', '最后'],
    source: 'https://zh.wikipedia.org/wiki/%E9%99%88%E7%BB%A7%E6%98%8C',
    sourceLabel: '陈继昌条目',
  },
  {
    id: 'weng-tonghe', dynasty: 'qing', year: 1856, name: '翁同龢', place: '常熟', exam: '咸丰六年',
    headline: '状元、帝师，也是政局中的人',
    summary: '咸丰六年丙辰科状元，授修撰。后来两度入值毓庆宫，授读光绪，历任户部、工部尚书，并两入军机。戊戌年被开缺回籍。',
    after: '回常熟后以书法和日记留世。日记是看晚清决策的第一手材料，不是殿试卷。',
    fact: '状元身份与 1898 年开缺都有清实录和本人日记可对照。',
    caution: { level: '角色过多', title: '帝师不等于他一人决定变法', text: '翁同龢影响光绪的读书与人事，但甲午、戊戌的决策还有军机、总理衙门和慈禧。把一位状元写成全部政局的开关，会夸大翰林出身的权力。' },
    keywords: ['帝师', '常熟', '戊戌'],
    image: '/images/zhuangyuan/weng.jpg',
    imageAlt: '翁同龢晚年照片',
    imageCredit: 'https://commons.wikimedia.org/wiki/File:Weng_Tonghe.jpg',
    source: 'https://zh.wikipedia.org/wiki/%E7%BF%81%E5%90%8C%E9%BE%A4',
    sourceLabel: '翁同龢条目',
  },
  {
    id: 'zhang-jian', dynasty: 'qing', year: 1894, name: '张謇', place: '海门', exam: '光绪二十年',
    headline: '四十一岁中状元，随后去办纱厂',
    summary: '光绪二十年甲午恩科状元，授修撰。中日开战同年，他很快离开词臣路径，在南通办大生纱厂、垦牧和师范，把状元身份用成地方实业的信用。',
    after: '清末立宪中参与筹备，民国后仍以南通事业为主。',
    fact: '生于 1853 年，中状元在 1894 年。大生纱厂 1899 年开车。时间顺序说明实业发生在中状元之后。',
    caution: { level: '因果简化', title: '状元身份帮他集资，但不生产棉纱', text: '科举名次提供了信任和官绅网络。工厂能不能转，取决于机器、棉花、资本和市场。两件事都要写。' },
    keywords: ['南通', '大生', '实业'],
    image: '/images/zhuangyuan/zhangjian.jpg',
    imageAlt: '张謇肖像照片',
    imageCredit: 'https://commons.wikimedia.org/wiki/File:Zhang_Jian.jpg',
    source: 'https://zh.wikipedia.org/wiki/%E5%BC%A0%E8%B5%9B',
    sourceLabel: '张謇条目',
  },
  {
    id: 'liu-chunlin', dynasty: 'qing', year: 1904, name: '刘春霖', place: '肃宁', exam: '光绪三十年',
    headline: '甲辰科状元，也是最后一位',
    summary: '光绪三十年为慈禧七旬万寿所开的甲辰恩科，刘春霖殿试第一，授修撰。光绪三十一年（1905）诏准停罢科举，他因此成为这一制度的最后一名状元。',
    after: '后来任福建提学使、直隶教育厅厅长等职，1942 年卒于北平。',
    fact: '科年、籍贯和“最后一名”都成立：1904 年之后没有再举行殿试。',
    caution: { level: '未证传闻', title: '慈禧因名字吉祥才点他为状元？', text: '殿试卷进呈时姓名弥封，阅卷者先看不到“春霖”“肃宁”。把名次解释成避讳“珍”字或厌广东，缺少能打开弥封的证据。' },
    keywords: ['末科', '甲辰', '1904'],
    image: '/images/zhuangyuan/liuchunlin.jpg',
    imageAlt: '刘春霖照片',
    imageCredit: 'https://commons.wikimedia.org/wiki/File:%E5%8A%89%E6%98%A5%E9%9C%96.jpg',
    source: 'https://zh.wikipedia.org/wiki/%E5%8A%89%E6%98%A5%E9%9C%96',
    sourceLabel: '刘春霖条目',
  },
]

export const TEXTS = [
  {
    id: 'wen-ce',
    personId: 'wen-tianxiang',
    kind: '殿试对策',
    title: '文天祥《御试策》',
    meta: '宝祐四年（1256）五月 · 策问与对策均存',
    original: '臣对：恭惟皇帝陛下，处常之久，当泰之交……然临御浸久，持循浸熟，而算计见效，犹未有以大快圣心者。……臣以为道非无验之物也。道之功化甚深也，而不可以为近；道之证效甚迟也，而不可以为速。……维天之命，於穆不已，天地之所以为天地也。……法天之不息而已。',
    gloss: '理宗问：我按二帝三王之道做了三十多年，天变、民生、财政和边防为什么还看不到成效？文天祥的回答把“没有立刻见效”从失败里拆出来：道的作用深，所以不能当成眼前的小事；验证来得慢，所以不能用几个月的政绩去催。他用《诗经》“维天之命，於穆不已”作依据，要求政治像天体运行一样持续，而不是靠一次改制度换来速效。',
    note: '引文按维基文库所收《御试策一道》节取，中间省略以省略号标出。王应麟“古谊若龟鉴，忠肝如铁石”是考官评语，写在登科录的阅读传统里，不是对策正文。',
    href: 'https://zh.wikisource.org/wiki/%E5%BE%A1%E8%A9%A6%E7%AD%96%E4%B8%80%E9%81%93%EF%BC%88%E6%9C%89%E9%A1%8C%EF%BC%89',
    hrefLabel: '阅读对策全文',
  },
  {
    id: 'yang-ci',
    personId: 'yang-shen',
    kind: '中状元之后',
    title: '杨慎《临江仙》',
    meta: '写于正德六年（1511）中状元之后 · 不是殿试卷',
    original: '滚滚长江东逝水，浪花淘尽英雄。是非成败转头空。青山依旧在，几度夕阳红。\n白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢。古今多少事，都付笑谈中。',
    gloss: '上片说人事会被时间冲走，江山还在。下片把评判交给江边看惯兴亡的渔樵，英雄叙事最后变成可被谈论、也可被放下的故事。杨慎写它时已经离开翰林，长期在云南戍所。词里的空，对着的是大礼议之后的贬谪，不是金榜题名当天的情绪。',
    note: '这首词后来被清初《三国演义》毛评本放在卷首，传播远超过杨慎的殿试对策。使用时要标明：它是状元的文学作品，不是中状元的考卷。',
    href: 'https://zh.wikisource.org/zh-hans/明史/卷192',
    hrefLabel: '对照《明史》本传里的贬谪',
  },
  {
    id: 'ce-form',
    personId: 'wen-tianxiang',
    kind: '文体',
    title: '一份殿试对策在回答什么',
    meta: '以宝祐四年策问为例 · 题目与答卷分开',
    original: '朕以寡昧之资，承祖宗之业，愿治，于兹历年……子大夫熟之复之，勿激勿泛，以副朕详延之意。',
    gloss: '策问通常先自谦，再摆出一组同时存在的问题：天象、民生、人才、国计、边防。它要求考生解释“为什么做了还没有效果”，并给出可以持续的办法。文天祥没有把这些问题拆成五份独立的政策清单，而是用“不息”把它们收成一个时间尺度：见效慢，不构成放弃的理由。',
    note: '明清殿试也沿用策问，但格式更固定：起收有套语，直指皇帝处要抬写。读后世抄本时，先分清哪一段是题目、哪一段是答卷、哪一段是考官批语。',
    href: 'https://zh.wikisource.org/wiki/%E5%AF%B6%E7%A5%90%E5%9B%9B%E5%B9%B4%E7%99%BB%E7%A7%91%E9%8C%B2_(%E5%9B%9B%E5%BA%AB%E5%85%A8%E6%9B%B8%E6%9C%AC)',
    hrefLabel: '打开《宝祐四年登科录》',
  },
]

export const RESOURCES = [
  { title: '文天祥《御试策一道》', note: '策问、对策的公有领域整理本。核对原文用这一份，不用转述。', href: 'https://zh.wikisource.org/wiki/%E5%BE%A1%E8%A9%A6%E7%AD%96%E4%B8%80%E9%81%93%EF%BC%88%E6%9C%89%E9%A1%8C%EF%BC%89', kind: '原文' },
  { title: '《宝祐四年登科录》', note: '文天祥榜题名、考官和策题。四库提要说明了脱漏的人名，统计同榜时不要只信一种抄本。', href: 'https://zh.wikisource.org/zh-hans/%E5%AF%B6%E7%A5%90%E5%9B%9B%E5%B9%B4%E7%99%BB%E7%A7%91%E9%8C%B2_(%E5%9B%9B%E5%BA%AB%E5%85%A8%E6%9B%B8%E6%9C%AC)', kind: '登科录' },
  { title: '《宋史》《明史》本传', note: '吕蒙正、张孝祥、文天祥、吴伯宗、黄观、商辂、杨慎的科年与官历，以本传为第一入口。', href: 'https://zh.wikisource.org/wiki/宋史', kind: '正史' },
  { title: '清朝状元列表', note: '112 科、114 人，以及江苏 49 人等分省数字的公开整理。分省边界用的是清代省名。', href: 'https://zh.wikipedia.org/zh-hans/%E6%B8%85%E6%9C%9D%E7%8A%B6%E5%85%83%E5%88%97%E8%A1%A8', kind: '名录' },
  { title: '刘春霖', note: '末科科年、弥封制度和“慈禧点名”传闻的辨析写在条目正文里。', href: 'https://zh.wikipedia.org/wiki/%E5%8A%89%E6%98%A5%E9%9C%96', kind: '人物' },
  { title: '徐松《登科记考》', note: '唐代进士名次的主要复原工作。唐代表格凡是标“名录复原”的，都要回到这本书而不是只看诗话。', href: 'https://zh.wikipedia.org/wiki/%E7%99%BB%E7%A7%91%E8%AE%B0%E8%80%83', kind: '考据' },
  { title: '商衍鎏《清代科举考试述录》', note: '末科探花所写的制度实录，讲清乡试、会试、殿试、朝考和翰林馆选。适合查流程，不代替每一科的题名录。', href: 'https://zh.wikipedia.org/wiki/%E5%95%86%E8%A1%8D%E9%90%B4', kind: '制度' },
  { title: '公共领域图像', note: '文天祥线描、翁同龢、张謇、刘春霖四帧来自维基共享资源。人物页图片说明附有文件页链接。', href: 'https://commons.wikimedia.org/wiki/File:Wen_Tianxiang.jpg', kind: '图像' },
]

export const CAUTIONS = [
  { level: '名号后起', tone: 'amber' },
  { level: '名录复原', tone: 'amber' },
  { level: '名次争议', tone: 'red' },
  { level: '叙事夸张', tone: 'red' },
  { level: '作品误植', tone: 'blue' },
  { level: '文本边界', tone: 'blue' },
  { level: '口径', tone: 'blue' },
  { level: '名录残缺', tone: 'amber' },
  { level: '稀缺不是神话', tone: 'blue' },
  { level: '荣誉之后', tone: 'blue' },
  { level: '地理标签', tone: 'blue' },
  { level: '角色过多', tone: 'amber' },
  { level: '因果简化', tone: 'amber' },
  { level: '未证传闻', tone: 'red' },
]
