export const PHASES = [
  { id: 'founding', label: '开国定制', range: '1368—1402', color: '#c84a3a' },
  { id: 'expansion', label: '永宣扩张', range: '1402—1435', color: '#d99a42' },
  { id: 'recovery', label: '危机与修复', range: '1435—1505', color: '#7f9b82' },
  { id: 'turn', label: '中期转折', range: '1505—1572', color: '#7186a2' },
  { id: 'late', label: '晚明危局', range: '1572—1644', color: '#8e6e91' },
]

export const EMPERORS = [
  {
    id: 'hongwu', order: 1, phase: 'founding', temple: '太祖', era: '洪武', name: '朱元璋', reign: '1368—1398', start: 1368, end: 1398, years: 30, accessionAge: 40,
    succession: '开国', capital: '南京', image: '/images/ming-emperors/hongwu.jpg', imagePosition: '50% 18%',
    headline: '从淮右布衣到制度奠基者',
    summary: '结束元末割据，建立明朝；以里甲、卫所、赋役黄册等制度重组基层，又以废丞相、兴大狱把权力高度集中于皇帝。',
    achievement: '统一主要汉地；恢复农业生产；重建基层户籍、赋役与军政体系。',
    cost: '胡惟庸案后废中书省与丞相，皇权负荷陡增；蓝玉案等大狱造成广泛株连。',
    keywords: ['开国', '废丞相', '卫所', '洪武大案'],
    scores: { statecraft: 5, military: 5, economy: 4, stability: 3 },
    fact: '洪武十三年（1380）胡惟庸案后，丞相制度被废，六部直接对皇帝负责。',
    legend: { title: '“鞋拔子脸”到底像不像？', level: '有据争议', text: '传世洪武像同时有端庄圆脸与长脸异相两套。学界常从宫廷礼仪像、民间讽刺像或后世摹本解释差异，无法仅凭画像确认真容。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷1',
  },
  {
    id: 'jianwen', order: 2, phase: 'founding', temple: '惠帝', era: '建文', name: '朱允炆', reign: '1398—1402', start: 1398, end: 1402, years: 4, accessionAge: 21,
    succession: '嫡系继承', capital: '南京',
    headline: '削藩太急，给了燕王起兵的窗口',
    summary: '试图削弱诸王、调整洪武严政；燕王朱棣以“靖难”为名起兵，四年后攻入南京。',
    achievement: '释放部分洪武朝获罪官员，尝试宽政与制度修正。',
    cost: '削藩次序与手段失当；中央军统筹失利，最终失国。',
    keywords: ['削藩', '靖难之役', '南京失守'],
    scores: { statecraft: 2, military: 1, economy: 3, stability: 1 },
    fact: '建文四年（1402）燕军入南京，宫中起火，朱允炆此后下落在可靠史料中没有定论。',
    legend: { title: '建文帝出家逃亡？', level: '未证传闻', text: '僧人出亡、流寓云贵、远走海外等版本长期流行；“尸体未明”留下叙事空间，但现存材料不足以锁定其结局。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷4',
  },
  {
    id: 'yongle', order: 3, phase: 'expansion', temple: '成祖', era: '永乐', name: '朱棣', reign: '1402—1424', start: 1402, end: 1424, years: 22, accessionAge: 42,
    succession: '武力夺位', capital: '北京',
    headline: '夺位者，也是帝国尺度的重塑者',
    summary: '迁都北京、修建紫禁城，五征蒙古，派郑和下西洋，组织编纂《永乐大典》，帝国的军政与外交半径显著扩大。',
    achievement: '北京成为长期政治中心；郑和船队远航；设奴儿干都司；文化工程规模空前。',
    cost: '靖难与清洗造成巨大政治创伤；北征、迁都和大型工程消耗财政与民力。',
    keywords: ['迁都北京', '郑和下西洋', '永乐大典', '五征漠北'],
    scores: { statecraft: 5, military: 5, economy: 3, stability: 4 },
    fact: '北京宫城在永乐年间营建，1421 年正式迁都；同年南京仍保留一套中央机构。',
    legend: { title: '郑和船队是为寻找建文帝？', level: '后世推测', text: '寻访建文帝常被当作下西洋的隐秘动机，但官方诏令、朝贡贸易与海上秩序更有直接史料支撑；“寻帝说”难作主因定论。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷5',
  },
  {
    id: 'hongxi', order: 4, phase: 'expansion', temple: '仁宗', era: '洪熙', name: '朱高炽', reign: '1424—1425', start: 1424, end: 1425, years: 0.8, accessionAge: 46,
    succession: '嫡系继承', capital: '北京',
    headline: '十个月的刹车：从扩张转向休养',
    summary: '在位不足一年，停止大规模远征，起用“三杨”等文臣，赦免部分建文旧臣，政策基调转向宽和节俭。',
    achievement: '减免赋税、平反冤狱、收缩远征，为“仁宣之治”定下方向。',
    cost: '在位过短，多项政策只能由宣宗延续和检验。',
    keywords: ['休养生息', '三杨', '仁宣之治'],
    scores: { statecraft: 4, military: 2, economy: 4, stability: 4 },
    fact: '从即位到去世不足一年，是明代在位时间第二短的皇帝。',
    legend: { title: '“胖死”能解释全部吗？', level: '后世推测', text: '画像与记载都强调其体态肥胖、行动不便，但具体死因缺乏现代医学证据，把早逝简单归结为肥胖仍属推断。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷8',
  },
  {
    id: 'xuande', order: 5, phase: 'expansion', temple: '宣宗', era: '宣德', name: '朱瞻基', reign: '1425—1435', start: 1425, end: 1435, years: 10, accessionAge: 26,
    succession: '嫡系继承', capital: '北京', image: '/images/ming-emperors/xuande.jpg', imagePosition: '50% 20%',
    headline: '能理政，也会画画和斗蟋蟀',
    summary: '平定汉王朱高煦叛乱，延续仁宗休养政策；宣德时期常与洪熙合称“仁宣之治”，宫廷艺术也达到高峰。',
    achievement: '中央决策较协调，边防与财政相对稳定；宣德瓷器和宫廷绘画成为时代名片。',
    cost: '撤出交趾标志此前南方扩张失败；宦官教育与参政空间继续扩大。',
    keywords: ['仁宣之治', '宣德炉', '宫廷艺术', '交趾撤军'],
    scores: { statecraft: 4, military: 4, economy: 4, stability: 5 },
    fact: '宣宗有传世书画作品；宫廷确有征集蟋蟀的记录，“促织天子”并非完全虚构。',
    legend: { title: '爱斗蟋蟀就是昏君？', level: '标签失真', text: '嗜好有史料基础，但它与其行政表现并不互相排斥。用一个宫廷爱好概括十年统治，会遮蔽财政、边防和用人。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷9',
  },
  {
    id: 'yingzong', order: 6, phase: 'recovery', temple: '英宗', era: '正统 / 天顺', name: '朱祁镇', reign: '1435—1449；1457—1464', start: 1435, end: 1464, years: 22, accessionAge: 8,
    succession: '幼主继位 / 复辟', capital: '北京',
    headline: '一生两次登基，中间做过俘虏和太上皇',
    summary: '亲征瓦剌在土木堡被俘，回京后被幽禁；1457 年经“夺门之变”复位。晚年废除宫妃殉葬，留下少见的人道改革。',
    achievement: '复位后政治逐步恢复；临终废止延续已久的宫妃殉葬。',
    cost: '土木堡之变损失精锐并使皇帝被俘；复辟后杀于谦成为重大污点。',
    keywords: ['土木堡之变', '北狩', '夺门之变', '废殉葬'],
    scores: { statecraft: 2, military: 1, economy: 3, stability: 2 },
    fact: '他是明代唯一使用两个年号、两次即位的皇帝。',
    legend: { title: '王振挟持皇帝亲征？', level: '有据争议', text: '宦官王振对仓促亲征负有重要责任，但皇帝本人并非完全没有决策权；把失败全推给一个宦官，会简化军政系统的共同失误。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷10',
  },
  {
    id: 'jingtai', order: 7, phase: 'recovery', temple: '代宗', era: '景泰', name: '朱祁钰', reign: '1449—1457', start: 1449, end: 1457, years: 8, accessionAge: 21,
    succession: '危局拥立', capital: '北京',
    headline: '北京保卫战中的应急皇帝',
    summary: '英宗被俘后受命即位，支持于谦组织北京保卫战，稳住土木堡后的政局；后来更换太子，加剧与英宗一系的冲突。',
    achievement: '守住北京、整顿军备，使明朝没有在 1449 年的危机中崩溃。',
    cost: '储位安排削弱合法性；病重时被“夺门之变”推翻，死后礼遇一度被削。',
    keywords: ['北京保卫战', '于谦', '易储', '夺门之变'],
    scores: { statecraft: 4, military: 4, economy: 3, stability: 3 },
    fact: '于谦主张坚守北京并组织防务，瓦剌未能迫使明廷南迁。',
    legend: { title: '夺门之变真的“救了国家”？', level: '叙事争议', text: '英宗复位时景泰帝病重且无在世皇子，政权交接本可另行安排；“夺门”更多是政治集团抢先控制局面，并非唯一救国路径。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷11',
  },
  {
    id: 'chenghua', order: 8, phase: 'recovery', temple: '宪宗', era: '成化', name: '朱见深', reign: '1464—1487', start: 1464, end: 1487, years: 23, accessionAge: 17,
    succession: '嫡系继承', capital: '北京',
    headline: '从平反于谦到“西厂”政治',
    summary: '即位初为于谦等平反，荆襄流民治理有所推进；中后期内廷与特务机构扩张，汪直掌西厂造成政治恐惧。',
    achievement: '平反土木堡后冤案；处置荆襄流民并设置郧阳府；成化瓷器精美。',
    cost: '宦官与传奉官膨胀；西厂侦缉扩大；宫廷支出上升。',
    keywords: ['平反于谦', '西厂', '万贵妃', '成化斗彩'],
    scores: { statecraft: 3, military: 3, economy: 3, stability: 3 },
    fact: '成化十三年设西厂，由汪直主持；其权势虽盛，机构也曾两次被裁撤。',
    legend: { title: '万贵妃让后宫所有孕妇堕胎？', level: '叙事夸张', text: '万贵妃受宠及后宫斗争有史料依据，但“尽害皇嗣”的完整故事高度依赖后出叙事，细节互相矛盾，不能照单全收。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷13',
  },
  {
    id: 'hongzhi', order: 9, phase: 'recovery', temple: '孝宗', era: '弘治', name: '朱祐樘', reign: '1487—1505', start: 1487, end: 1505, years: 18, accessionAge: 17,
    succession: '嫡系继承', capital: '北京',
    headline: '勤政与共治，明中期少见的稳态',
    summary: '整顿吏治，起用刘健、李东阳、谢迁等大臣，朝政相对清明，后世称“弘治中兴”。',
    achievement: '抑制内廷干政，重视阁臣与科道，财政和行政秩序得到修复。',
    cost: '后期也有斋醮、外戚与纸面整饬问题；中兴未解决军屯衰败等深层矛盾。',
    keywords: ['弘治中兴', '内阁共治', '勤政', '张皇后'],
    scores: { statecraft: 5, military: 3, economy: 4, stability: 5 },
    fact: '弘治朝内阁“三老”刘健、李东阳、谢迁形成较稳定的决策班底。',
    legend: { title: '中国史上唯一“一夫一妻”的皇帝？', level: '流行说法', text: '孝宗长期仅与张皇后共同生活、未见其他妃嫔生育，这一形象有依据；但严格套用现代“一夫一妻制”概念并不准确。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷15',
  },
  {
    id: 'zhengde', order: 10, phase: 'turn', temple: '武宗', era: '正德', name: '朱厚照', reign: '1505—1521', start: 1505, end: 1521, years: 16, accessionAge: 14,
    succession: '嫡系继承', capital: '北京',
    headline: '把皇权活成个人冒险的少年天子',
    summary: '宠信刘瑾，又在铲除刘瑾后亲自北巡、南征；应州之役与平宁王之乱使他拥有不同于刻板“玩乐皇帝”的军事面。',
    achievement: '诛刘瑾；亲临边塞；迅速处置宁王叛乱后的权力格局。',
    cost: '豹房与巡幸扰动行政；宠臣政治反复；无嗣导致旁支入继和“大礼议”。',
    keywords: ['刘瑾', '豹房', '应州之役', '宁王之乱'],
    scores: { statecraft: 2, military: 4, economy: 2, stability: 2 },
    fact: '正德十二年亲赴宣府一线，此后把“大将军朱寿”作为个人军政身份。',
    legend: { title: '豹房只是“动物园和淫乐场”？', level: '叙事简化', text: '豹房确是宫外活动中心，也有奢靡记载；但它同时承担皇帝另建近侍、军官与情报网络的政治功能。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷16',
  },
  {
    id: 'jiajing', order: 11, phase: 'turn', temple: '世宗', era: '嘉靖', name: '朱厚熜', reign: '1521—1567', start: 1521, end: 1567, years: 45, accessionAge: 14,
    succession: '旁支入继', capital: '北京',
    headline: '四十五年权术：不常上朝，不等于失去控制',
    summary: '以“大礼议”重塑皇统和臣属关系；中后期长期居西苑修道，严嵩专权，东南倭患与北方俺答威胁同时加剧。',
    achievement: '牢牢控制皇权与人事；中后期抗倭体系逐渐成熟，出现张居正等后续改革人才。',
    cost: '大礼议与廷杖重创士大夫；财政紧张、宫廷工程频繁；庚戌之变暴露京防。',
    keywords: ['大礼议', '壬寅宫变', '严嵩', '倭患'],
    scores: { statecraft: 4, military: 2, economy: 2, stability: 2 },
    fact: '嘉靖二十一年宫女试图勒杀皇帝，史称“壬寅宫变”；此后皇帝更加远离大内。',
    legend: { title: '几十年不上朝就是几十年不理政？', level: '概念误读', text: '嘉靖长期不举行常朝，但仍通过票拟、批红、密疏和召对操纵大臣。不上朝与不掌权不是同一件事。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷17',
  },
  {
    id: 'longqing', order: 12, phase: 'turn', temple: '穆宗', era: '隆庆', name: '朱载坖', reign: '1567—1572', start: 1567, end: 1572, years: 5, accessionAge: 29,
    succession: '嫡系继承', capital: '北京',
    headline: '五年松绑：海贸与北部和平打开窗口',
    summary: '解除部分海禁，允许福建月港民间海外贸易；“俺答封贡”缓和北部边患，徐阶、高拱、张居正先后进入权力核心。',
    achievement: '隆庆开关推动合法海贸；与蒙古右翼实现封贡互市；社会经济获得喘息。',
    cost: '内阁倾轧激烈；本人健康不佳、在位短，政策稳定性依赖继承者。',
    keywords: ['隆庆开关', '俺答封贡', '月港', '内阁更替'],
    scores: { statecraft: 4, military: 4, economy: 5, stability: 4 },
    fact: '1567 年福建月港获准开展民间海外贸易，海禁由绝对禁止转向有限许可。',
    legend: { title: '“开放海禁”就是全面开放？', level: '概念误读', text: '隆庆开关意义重大，但口岸、航线和对象都有限制，对日贸易仍受禁；它是有限合法化，不是近代式自由贸易。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷19',
  },
  {
    id: 'wanli', order: 13, phase: 'late', temple: '神宗', era: '万历', name: '朱翊钧', reign: '1572—1620', start: 1572, end: 1620, years: 48, accessionAge: 9,
    succession: '幼主继位', capital: '北京',
    headline: '最长在位：前十年改革，后三十年拉扯',
    summary: '前期由张居正主持考成法、清丈和赋役整顿；中后期围绕国本之争与官僚集团长期对抗，辽东战争与财政压力持续上升。',
    achievement: '张居正改革提高财政与行政动员；万历三大征维护边疆秩序；商业和白银经济活跃。',
    cost: '长期缺朝造成职位空缺和决策迟滞；矿税与辽饷加重社会负担；萨尔浒之败改变东北局势。',
    keywords: ['张居正改革', '万历三大征', '国本之争', '萨尔浒'],
    scores: { statecraft: 3, military: 3, economy: 3, stability: 2 },
    fact: '万历在位 48 年，是明代在位最久的皇帝；定陵发掘使其遗骸与随葬制度留下现代考古记录。',
    legend: { title: '“万历怠政”源于吸食鸦片？', level: '证据不足', text: '腿疾、肥胖、心理与政治对抗均有讨论；从骨骼或药物残留推到“鸦片成瘾”证据链很弱，不能当作定论。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷20',
  },
  {
    id: 'taichang', order: 14, phase: 'late', temple: '光宗', era: '泰昌', name: '朱常洛', reign: '1620（29 天）', start: 1620, end: 1620.08, years: 0.08, accessionAge: 38,
    succession: '嫡系继承', capital: '北京',
    headline: '二十九天，把宫廷医疗变成政治案件',
    summary: '长期受“国本之争”影响，登基后不足一月去世；此前“梃击案”与随后“红丸案”“移宫案”合称晚明三案。',
    achievement: '即位后罢矿税使、发内帑犒边，释放调整朝政的信号。',
    cost: '健康恶化与宫廷用药失控，政策来不及展开；死因争论加剧党争。',
    keywords: ['晚明三案', '红丸案', '国本之争', '短祚'],
    scores: { statecraft: 2, military: 1, economy: 3, stability: 1 },
    fact: '从即位到去世约 29 天，是明代在位最短的皇帝。',
    legend: { title: '一颗“红丸”毒死皇帝？', level: '重大争议', text: '服红丸后病情一度被描述为好转，次日暴亡；误治、毒杀或原病恶化均有人主张，材料深受党争立场影响，无法验尸定案。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷21',
  },
  {
    id: 'tianqi', order: 15, phase: 'late', temple: '熹宗', era: '天启', name: '朱由校', reign: '1620—1627', start: 1620, end: 1627, years: 7, accessionAge: 15,
    succession: '嫡系继承', capital: '北京', image: '/images/ming-emperors/tianqi.jpg', imagePosition: '50% 15%',
    headline: '木工天赋与权力外包的危险组合',
    summary: '魏忠贤与客氏势力膨胀，东林党人遭系统打击；辽东战事恶化，但孙承宗、袁崇焕等仍构筑关宁防线。',
    achievement: '宁远之战击退努尔哈赤；部分边防体系在财政困境中维持。',
    cost: '阉党清洗破坏官僚信任；党争与军饷问题恶化；天启大爆炸加深社会恐慌。',
    keywords: ['魏忠贤', '东林党争', '宁远大捷', '木工'],
    scores: { statecraft: 1, military: 2, economy: 2, stability: 1 },
    fact: '天启六年王恭厂附近发生巨大爆炸，原因至今无定论；史料明确记录了严重伤亡与破坏。',
    legend: { title: '天启帝只会做木匠、完全不识字？', level: '标签夸张', text: '他喜爱木作、厌烦政务的形象有来源，但“文盲木匠”是后世标签化表达；皇帝仍接受过基本教育并参与关键任命。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷22',
  },
  {
    id: 'chongzhen', order: 16, phase: 'late', temple: '思宗', era: '崇祯', name: '朱由检', reign: '1627—1644', start: 1627, end: 1644, years: 17, accessionAge: 16,
    succession: '兄终弟及', capital: '北京',
    headline: '越勤政，越暴露系统已经没有容错',
    summary: '铲除魏忠贤后试图重整朝纲，但频繁更换大臣、辽东与农民战争并发，加上财政、灾荒与疫病，最终李自成攻入北京。',
    achievement: '迅速清除阉党核心；勤于批阅与召对；多次尝试整顿军政和财政。',
    cost: '多疑急切、用人反复；处死袁崇焕等削弱前线；多战线与税负让国家动员走向崩溃。',
    keywords: ['清算阉党', '袁崇焕', '农民战争', '甲申之变'],
    scores: { statecraft: 2, military: 2, economy: 1, stability: 1 },
    fact: '1644 年 4 月北京失守，崇祯在煤山自缢；明朝中央政权终结，南明政权随后延续。',
    legend: { title: '“君非亡国之君，臣皆亡国之臣”？', level: '责任争论', text: '这句概括强化了勤政悲剧形象，却会把制度、财政、气候、战争和皇帝用人责任切开。亡国是多因素叠加，不宜只归咎群臣。' },
    source: 'https://zh.wikisource.org/zh-hans/明史/卷23',
  },
]

export const EVENTS = [
  { year: 1368, title: '明朝建立', text: '朱元璋在南京即皇帝位，国号“大明”。', type: '政权' },
  { year: 1380, title: '废丞相', text: '胡惟庸案后，中书省与丞相制度被废。', type: '制度' },
  { year: 1402, title: '靖难结束', text: '燕王朱棣攻入南京，建文帝失踪。', type: '战争' },
  { year: 1405, title: '郑和首下西洋', text: '七次远航由此开始，最远抵达东非沿岸与红海区域。', type: '海洋' },
  { year: 1421, title: '迁都北京', text: '北京成为帝国首都，南京保留陪都机构。', type: '制度' },
  { year: 1449, title: '土木堡之变', text: '英宗被俘；于谦组织北京保卫战。', type: '战争' },
  { year: 1457, title: '夺门之变', text: '英宗复位，景泰朝终结，于谦被杀。', type: '政变' },
  { year: 1517, title: '正德北巡', text: '武宗亲赴边塞，自称“威武大将军朱寿”。', type: '皇权' },
  { year: 1524, title: '大礼议廷杖', text: '嘉靖帝以议礼重塑君臣权力关系。', type: '制度' },
  { year: 1567, title: '隆庆开关', text: '月港有限开放民间海外贸易。', type: '海洋' },
  { year: 1573, title: '张居正改革', text: '考成法推动行政问责，随后清丈与赋役整顿展开。', type: '改革' },
  { year: 1592, title: '援朝战争开始', text: '明军入朝抗击日本侵略，成为万历三大征中规模最大者。', type: '战争' },
  { year: 1619, title: '萨尔浒之战', text: '明军败于后金，辽东战略转入守势。', type: '战争' },
  { year: 1626, title: '宁远之战', text: '袁崇焕守宁远，后金攻势受挫。', type: '战争' },
  { year: 1644, title: '北京失守', text: '李自成入北京，崇祯自缢；清军随后入关。', type: '政权' },
]

export const SOURCES = [
  { title: '《明史》本纪（原文）', note: '16 帝基本纪与列传入口；清代官修史书，使用时仍需注意成书时代与褒贬框架。', href: 'https://zh.wikisource.org/zh-hans/明史', kind: '一手/官修史书' },
  { title: '明朝君主列表', note: '用于快速核对年号、在位顺序与两次即位等基础年代。', href: 'https://zh.wikipedia.org/wiki/明朝君主列表', kind: '开放资料' },
  { title: 'Defining Yongle', note: '大都会艺术博物馆关于永乐时期宫廷艺术、迁都与对外联系的专题。', href: 'https://www.metmuseum.org/exhibitions/listings/2005/yongle-imperial-art', kind: '博物馆' },
  { title: '明清皇家陵寝', note: '联合国教科文组织对明孝陵、明十三陵等遗产价值与范围的说明。', href: 'https://whc.unesco.org/en/list/1004', kind: '世界遗产' },
  { title: '明代帝王肖像分类', note: '本页人物配图的公共领域文件与版权信息入口。', href: 'https://commons.wikimedia.org/wiki/Category:Portraits_of_Emperors_of_the_Ming_Dynasty', kind: '图像档案' },
  { title: '明代历史总览', note: '用于交叉核对朝代起讫、迁都、制度和全球背景的基础概览。', href: 'https://www.britannica.com/topic/Ming-dynasty-Chinese-history', kind: '百科全书' },
]

export const COMPARISON_ROWS = [
  { key: 'reign', label: '在位' },
  { key: 'accessionAge', label: '即位年龄', format: (value) => `${value} 岁` },
  { key: 'succession', label: '上位方式' },
  { key: 'capital', label: '主要都城' },
  { key: 'achievement', label: '主要遗产' },
  { key: 'cost', label: '统治代价' },
]

export const SCORE_LABELS = {
  statecraft: '治理', military: '军事', economy: '经济', stability: '稳定',
}
