export const DIGITAL_HUMAN_SELF_HOSTED_PROVIDER = 'self-hosted-sadtalker'
export const DIGITAL_HUMAN_REPLICATE_PROVIDER = 'replicate-sadtalker'
export const DIGITAL_HUMAN_DEFAULT_PROVIDER = DIGITAL_HUMAN_SELF_HOSTED_PROVIDER
export const DIGITAL_HUMAN_PROVIDERS = new Set([
  DIGITAL_HUMAN_SELF_HOSTED_PROVIDER,
  DIGITAL_HUMAN_REPLICATE_PROVIDER,
])
