export const AGENT_OPS_ROOT = '/Users/tuaran/Documents/codex/agent-ops'
export const AGENT_OPS_EXTERNAL_URL = 'https://ops.2aran.com/'
export const AGENT_OPS_LOCAL_URL = 'http://localhost:4179'

export const AUTOMATION_REGISTRY = [
  {
    id: 'github-auto-follow',
    name: 'GitHub 自动 Follow',
    repository: 'github-auto-follow',
    scope: 'cloud',
    trigger: '云端定时 / 事件触发',
    entry: 'GitHub API 自动化',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['follow 记录', '目标账号清单', 'API 响应日志'],
    riskLevel: 'high',
    autoRun: true,
    reviewRequired: true,
    description: '云端自动执行 GitHub follow 动作，必须限制频率、白名单和失败重试。',
  },
  {
    id: 'frontendnext-hourly-ingest',
    name: 'FrontendNext 每时抓取更新',
    repository: 'frontend-weekly-digest-cn',
    scope: 'cloud',
    trigger: '每小时',
    entry: 'https://frontendnext.com/',
    lastRun: '运行中，待接入状态回写',
    successRate: '待统计',
    artifacts: ['抓取快照', '新增链接', '去重记录'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: false,
    description: '云端定时抓取前端与 AI Agent 信息源，更新 FrontendNext 小时级情报池。',
  },
  {
    id: 'frontendnext-daily-brief',
    name: 'FrontendNext 每日汇总',
    repository: 'frontend-weekly-digest-cn',
    scope: 'cloud',
    trigger: '每日',
    entry: 'https://frontendnext.com/',
    lastRun: '运行中，待接入状态回写',
    successRate: '待统计',
    artifacts: ['每日摘要', '候选选题', '发布草稿'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '基于小时级抓取结果生成每日汇总，进入人工确认后发布或归档。',
  },
  {
    id: 'autopilot-security-scan',
    name: '站点安全巡检（Autopilot）',
    repository: 'tuaran-home-page',
    scope: 'cloud',
    trigger: '每周一 09:17（北京）',
    entry: 'https://github.com/TUARAN/tuaran-home-page/actions/workflows/security-scan.yml',
    lastRun: '2026-07-31 14:20 成功',
    successRate: '最近成功',
    artifacts: ['安全报告 JSON', '待修 Issue', 'Draft PR'],
    riskLevel: 'high',
    autoRun: true,
    reviewRequired: true,
    description: 'GitHub Actions 每周扫描依赖漏洞、敏感文件与安全响应头，DeepSeek 分诊后自动建待修 Issue，可自动修复项开 Draft PR；merge 由站长人工完成。',
  },
  {
    id: 'autopilot-perf-scan',
    name: '站点性能巡检（Autopilot）',
    repository: 'tuaran-home-page',
    scope: 'cloud',
    trigger: '每两周周三 09:17（北京，偶数周）',
    entry: 'https://github.com/TUARAN/tuaran-home-page/actions/workflows/perf-scan.yml',
    lastRun: '2026-07-31 14:20 成功',
    successRate: '最近成功',
    artifacts: ['性能报告 JSON', '待修 Issue'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '每两周扫描静态资源体积、超大源文件与构建 chunk，DeepSeek 过滤噪音并给出修复建议；涉及重构的问题保留 Issue 转人工。',
  },
  {
    id: 'autopilot-design-scan',
    name: '站点设计巡检（Autopilot）',
    repository: 'tuaran-home-page',
    scope: 'cloud',
    trigger: '每月 1 日 09:17（北京）',
    entry: 'https://github.com/TUARAN/tuaran-home-page/actions/workflows/design-scan.yml',
    lastRun: '2026-07-31 14:19 成功',
    successRate: '最近成功',
    artifacts: ['设计报告 JSON', '修复建议'],
    riskLevel: 'low',
    autoRun: true,
    reviewRequired: true,
    description: '每月扫描 Tailwind 类审计与 img alt 可访问性，DeepSeek 汇总修复建议；info 级问题不自动建 Issue，由站长决定是否处理。',
  },
  {
    id: 'x-morning-greeting',
    name: 'X 每日早安问候',
    repository: 'tuaran-home-page',
    scope: 'cloud',
    trigger: '每天 08:00（北京时间，GitHub Actions 00:00 UTC）',
    entry: 'https://github.com/TUARAN/tuaran-home-page/actions/workflows/morning-greeting.yml',
    lastRun: '运行中（最近一次结果见运行记录）',
    successRate: '待统计',
    artifacts: ['X 发帖结果', '运行日志'],
    riskLevel: 'low',
    autoRun: true,
    reviewRequired: false,
    description:
      '每天北京时间 08:00 自动向 X 发布固定早安问候。规则：文案模板固定于 lib/morningGreeting.js（“今日是 X月X号”按当天自动替换，其余文字保持站长暂定内容），由 GitHub Actions 定时调用站内 POST /api/distribution/x/greeting，接口校验 MORNING_GREETING_SECRET 后使用站长 X 账号（X OAuth 1.0a）发帖；发帖结果写入 site_settings 运行记录。本后台可一键暂停/恢复：暂停后定时触发直接返回 423 跳过，不会发布任何内容。',
  },
  {
    id: 'frontend-weekly-medium-translate',
    name: '前端周刊 Medium 抓取翻译',
    repository: 'frontend-weekly-digest-cn',
    scope: 'local',
    trigger: '手动 / 周期性',
    entry: '本地前端周刊工作流',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['Medium 原文', '中文翻译稿', '周刊候选条目'],
    riskLevel: 'medium',
    autoRun: false,
    reviewRequired: true,
    description: '本地抓取 Medium 前端文章，翻译并整理为前端周刊候选内容。',
  },
  {
    id: 'openclaw-issue-pr',
    name: 'OpenClaw Issues 解决并提 PR',
    repository: 'openclaw-issue-pr-tool',
    scope: 'local',
    trigger: '手动 / 每 2 天候选扫描',
    entry: '/Users/tuaran/Documents/codex/openclaw-issue-pr-tool',
    lastRun: '已有 worktree 运行记录，待统一回写',
    successRate: '待统计',
    artifacts: ['Issue 候选清单', '修复分支', 'Pull Request'],
    riskLevel: 'high',
    autoRun: false,
    reviewRequired: true,
    description: '本地扫描 OpenClaw 低风险 issue，生成修复、运行测试，并在确认后提交 PR。',
  },
  {
    id: 'digital-employee-weekly',
    name: '数字员工周报',
    repository: 'agent-ops',
    scope: 'local',
    trigger: '每周',
    entry: '本地数字员工周报工作流',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['周报 Markdown', '任务进展摘要', '风险与下周计划'],
    riskLevel: 'medium',
    autoRun: false,
    reviewRequired: true,
    description: '汇总数字员工相关工作、自动化运行结果和下周推进计划。',
  },
  {
    id: 'syncblog-queue',
    name: '研究文章分发队列',
    repository: 'agent-ops',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['syncblog-queue.json', 'syncblog-queue.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '把研究文章整理成分发队列，生成待同步清单和 Markdown 产物，发布前保留人工确认。',
  },
  {
    id: 'employeehub-triage',
    name: 'EmployeeHub 自动进化巡检',
    repository: 'agent-ops',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['employeehub-triage.json', 'employeehub-triage.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '巡检 EmployeeHub 相关需求、任务和异常，沉淀下一轮自动进化建议。',
  },
  {
    id: 'blogger-metrics-summary',
    name: '博主联盟指标报告',
    repository: 'agent-ops',
    scope: 'local',
    trigger: '每日 / 每周 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['blogger-metrics-summary.json', 'blogger-metrics-summary.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '汇总博主联盟关键指标和阶段性变化，输出可归档的指标报告。',
  },
  {
    id: 'lead-radar',
    name: '潜在客户雷达',
    repository: 'agent-ops',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['lead-radar.csv', 'lead-radar.json', 'lead-radar.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '扫描潜在客户线索并生成雷达结果，供后续人工筛选和跟进。',
  },
]

export const OPS_RECENT_RUNS = [
  {
    id: '2026-06-17T091812-000Z_world-cup-collect',
    taskId: 'world-cup-collect',
    taskName: '世界杯比分采集',
    repository: 'agent-ops',
    status: 'success',
    reviewStatus: 'not_required',
    startedAt: '2026-06-17T09:18:12.000Z',
    durationMs: 1512,
    artifacts: ['wc_matches (104)', 'wc_standings (40)', 'wc_scorers (25)'],
  },
  {
    id: '2026-07-31T142013Z_autopilot-security',
    taskId: 'autopilot-security-scan',
    taskName: '站点安全巡检（Autopilot）',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-07-31T14:18:39.000Z',
    durationMs: 94000,
    artifacts: ['security-2026-07-31.json', 'Issue #47', 'PR #48'],
  },
  {
    id: '2026-07-31T142007Z_autopilot-performance',
    taskId: 'autopilot-perf-scan',
    taskName: '站点性能巡检（Autopilot）',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-07-31T14:18:41.000Z',
    durationMs: 86000,
    artifacts: ['performance-2026-07-31.json', 'Issue #46'],
  },
  {
    id: '2026-07-31T141956Z_autopilot-design',
    taskId: 'autopilot-design-scan',
    taskName: '站点设计巡检（Autopilot）',
    status: 'success',
    reviewStatus: 'not_required',
    startedAt: '2026-07-31T14:18:45.000Z',
    durationMs: 71000,
    artifacts: ['design-2026-07-31.json', '8 处 alt 建议'],
  },
  {
    id: '2026-06-05T025353-252Z_content-sync',
    taskId: 'syncblog-queue',
    taskName: '研究文章分发队列',
    status: 'success',
    reviewStatus: 'approved',
    startedAt: '2026-06-05T02:53:53.254Z',
    durationMs: 44,
    artifacts: ['syncblog-queue.json', 'syncblog-queue.md'],
  },
  {
    id: '2026-06-05T025320-802Z_employeehub-evolve',
    taskId: 'employeehub-triage',
    taskName: 'EmployeeHub 自动进化巡检',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:20.803Z',
    durationMs: 121,
    artifacts: ['employeehub-triage.json', 'employeehub-triage.md'],
  },
  {
    id: '2026-06-05T025320-800Z_blogger-metrics',
    taskId: 'blogger-metrics-summary',
    taskName: '博主联盟指标报告',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:20.802Z',
    durationMs: 49,
    artifacts: ['blogger-metrics-summary.json', 'blogger-metrics-summary.md'],
  },
  {
    id: '2026-06-05T025313-095Z_lead-radar',
    taskId: 'lead-radar',
    taskName: '潜在客户雷达',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:13.097Z',
    durationMs: 50,
    artifacts: ['lead-radar.csv', 'lead-radar.json', 'lead-radar.md'],
  },
]

export function registryEntryText(item) {
  return JSON.stringify(
    {
      id: item.id,
      name: item.name,
      repository: item.repository,
      scope: item.scope,
      trigger: item.trigger,
      entry: item.entry,
      lastRun: item.lastRun,
      successRate: item.successRate,
      artifacts: item.artifacts,
      riskLevel: item.riskLevel,
      autoRun: item.autoRun,
      reviewRequired: item.reviewRequired,
    },
    null,
    2
  )
}
