export const AGENT_OPS_ROOT = '/Users/tuaran/Documents/codex/agent-ops'
export const AGENT_OPS_EXTERNAL_URL = 'https://ops.2aran.com/'
export const AGENT_OPS_LOCAL_URL = 'http://localhost:4179'

export const AUTOMATION_REGISTRY = [
  {
    id: 'github-auto-follow',
    name: 'GitHub 自动 Follow',
    scope: 'cloud',
    trigger: '云端定时 / 事件触发',
    entry: 'GitHub API 自动化',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['follow 记录', '目标账号清单', 'API 响应日志'],
    riskLevel: 'high',
    autoRun: true,
    reviewRequired: true,
    description: '云端自动执行 GitHub follow 动作，必须限制频率、白名单和失败重试。',
  },
  {
    id: 'frontendnext-hourly-ingest',
    name: 'FrontendNext 每时抓取更新',
    scope: 'cloud',
    trigger: '每小时',
    entry: 'https://frontendnext.com/',
    lastRun: '运行中，待接入状态回写',
    successRate: '待统计',
    artifacts: ['抓取快照', '新增链接', '去重记录'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: false,
    description: '云端定时抓取前端与 AI Agent 信息源，更新 FrontendNext 小时级情报池。',
  },
  {
    id: 'frontendnext-daily-brief',
    name: 'FrontendNext 每日汇总',
    scope: 'cloud',
    trigger: '每日',
    entry: 'https://frontendnext.com/',
    lastRun: '运行中，待接入状态回写',
    successRate: '待统计',
    artifacts: ['每日摘要', '候选选题', '发布草稿'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '基于小时级抓取结果生成每日汇总，进入人工确认后发布或归档。',
  },
  {
    id: 'frontend-weekly-medium-translate',
    name: '前端周刊 Medium 抓取翻译',
    scope: 'local',
    trigger: '手动 / 周期性',
    entry: '本地前端周刊工作流',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['Medium 原文', '中文翻译稿', '周刊候选条目'],
    riskLevel: 'medium',
    autoRun: false,
    reviewRequired: true,
    description: '本地抓取 Medium 前端文章，翻译并整理为前端周刊候选内容。',
  },
  {
    id: 'openclaw-issue-pr',
    name: 'OpenClaw Issues 解决并提 PR',
    scope: 'local',
    trigger: '手动 / 每 2 天候选扫描',
    entry: '/Users/tuaran/Documents/codex/openclaw-issue-pr-tool',
    lastRun: '已有 worktree 运行记录，待统一回写',
    successRate: '待统计',
    artifacts: ['Issue 候选清单', '修复分支', 'Pull Request'],
    riskLevel: 'high',
    autoRun: false,
    reviewRequired: true,
    description: '本地扫描 OpenClaw 低风险 issue，生成修复、运行测试，并在确认后提交 PR。',
  },
  {
    id: 'digital-employee-weekly',
    name: '数字员工周报',
    scope: 'local',
    trigger: '每周',
    entry: '本地数字员工周报工作流',
    lastRun: '待接入状态回写',
    successRate: '待统计',
    artifacts: ['周报 Markdown', '任务进展摘要', '风险与下周计划'],
    riskLevel: 'medium',
    autoRun: false,
    reviewRequired: true,
    description: '汇总数字员工相关工作、自动化运行结果和下周推进计划。',
  },
  {
    id: 'syncblog-queue',
    name: '研究文章分发队列',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['syncblog-queue.json', 'syncblog-queue.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '把研究文章整理成分发队列，生成待同步清单和 Markdown 产物，发布前保留人工确认。',
  },
  {
    id: 'employeehub-triage',
    name: 'EmployeeHub 自动进化巡检',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['employeehub-triage.json', 'employeehub-triage.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '巡检 EmployeeHub 相关需求、任务和异常，沉淀下一轮自动进化建议。',
  },
  {
    id: 'blogger-metrics-summary',
    name: '博主联盟指标报告',
    scope: 'local',
    trigger: '每日 / 每周 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['blogger-metrics-summary.json', 'blogger-metrics-summary.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '汇总博主联盟关键指标和阶段性变化，输出可归档的指标报告。',
  },
  {
    id: 'lead-radar',
    name: '潜在客户雷达',
    scope: 'local',
    trigger: '每日 / 手动',
    entry: AGENT_OPS_LOCAL_URL,
    lastRun: '2026/06/05 10:53',
    successRate: '最近成功',
    artifacts: ['lead-radar.csv', 'lead-radar.json', 'lead-radar.md'],
    riskLevel: 'medium',
    autoRun: true,
    reviewRequired: true,
    description: '扫描潜在客户线索并生成雷达结果，供后续人工筛选和跟进。',
  },
]

export const OPS_RECENT_RUNS = [
  {
    id: '2026-06-05T025353-252Z_content-sync',
    taskId: 'syncblog-queue',
    taskName: '研究文章分发队列',
    status: 'success',
    reviewStatus: 'approved',
    startedAt: '2026-06-05T02:53:53.254Z',
    durationMs: 44,
    artifacts: ['syncblog-queue.json', 'syncblog-queue.md'],
  },
  {
    id: '2026-06-05T025320-802Z_employeehub-evolve',
    taskId: 'employeehub-triage',
    taskName: 'EmployeeHub 自动进化巡检',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:20.803Z',
    durationMs: 121,
    artifacts: ['employeehub-triage.json', 'employeehub-triage.md'],
  },
  {
    id: '2026-06-05T025320-800Z_blogger-metrics',
    taskId: 'blogger-metrics-summary',
    taskName: '博主联盟指标报告',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:20.802Z',
    durationMs: 49,
    artifacts: ['blogger-metrics-summary.json', 'blogger-metrics-summary.md'],
  },
  {
    id: '2026-06-05T025313-095Z_lead-radar',
    taskId: 'lead-radar',
    taskName: '潜在客户雷达',
    status: 'success',
    reviewStatus: 'pending_review',
    startedAt: '2026-06-05T02:53:13.097Z',
    durationMs: 50,
    artifacts: ['lead-radar.csv', 'lead-radar.json', 'lead-radar.md'],
  },
]

export function registryEntryText(item) {
  return JSON.stringify(
    {
      id: item.id,
      name: item.name,
      scope: item.scope,
      trigger: item.trigger,
      entry: item.entry,
      lastRun: item.lastRun,
      successRate: item.successRate,
      artifacts: item.artifacts,
      riskLevel: item.riskLevel,
      autoRun: item.autoRun,
      reviewRequired: item.reviewRequired,
    },
    null,
    2
  )
}
