// Generated by scripts/generate-article-assets.mjs. Metadata only; no article bodies.
export const articles = [
  {
    "slug": "mcp-https-vs-stdio-architecture-design",
    "title": "MCP 走 HTTPS 还是 stdio：两种传输方式背后的架构与业务设计",
    "date": "2026-07-17",
    "href": "",
    "homeCategory": "AI 工程",
    "tags": [
      "MCP",
      "AI Agent",
      "Streamable HTTP",
      "stdio",
      "系统架构",
      "OAuth"
    ],
    "summary": "MCP 的 HTTPS 与 stdio 分别对应网络服务边界与本机进程边界两套架构。可从生命周期、鉴权、状态、扩缩容、安全、可观察性和业务场景出发，完成选型与混合设计。",
    "cover": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=75"
  },
  {
    "slug": "ai-project-complexity-governance",
    "title": "AI 能写完代码以后，复杂度成了真正的瓶颈",
    "date": "2026-07-17",
    "href": "",
    "homeCategory": "AI 工程",
    "tags": [
      "AI 编程",
      "软件架构",
      "复杂度治理",
      "数据库设计",
      "个人项目"
    ],
    "summary": "AI 降低了生产代码的成本，却没有降低理解系统的成本。以这个网站为例，讨论数据库范式、分层抽象、数据拆分、算法优化与 AI 协作边界，尝试给出一套让复杂系统重新可控的方法。",
    "cover": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=75"
  },
  {
    "slug": "diary-self-reflection",
    "title": "浮生日记（连载中）📓",
    "date": "2026-05-11",
    "href": "",
    "summary": "人生碌碌，竞短论长，却不道枯荣有数，得失难量。",
    "cover": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=60"
  },
  {
    "slug": "content-os-blogger-matrix-alliance",
    "title": "向大家介绍「开发者博主联盟」🚀",
    "date": "2026-01-08",
    "href": "",
    "sourceUrl": "https://juejin.cn/post/7595425302968696873",
    "summary": "今之创作，非乏才也，乏其制耳。有才而无制，则劳而不继；有制而能协，则文自生，利自分，业自成。",
    "cover": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=60"
  },
  {
    "slug": "openclaw-pr-anthropic-image-normalization",
    "title": "6 次被 OpenClaw 合并：从修一个提示，到修一条完整链路",
    "date": "2026-08-15",
    "href": "",
    "homeCategory": "开源贡献",
    "tags": [
      "OpenClaw",
      "开源贡献",
      "Pull Request",
      "ClawSweeper",
      "工程实践"
    ],
    "summary": "复盘我在 OpenClaw 主仓库被合并的 6 个 PR：每次遇到的问题、修复边界、评审后的持续改进与最终落地方式。",
    "cover": "/images/openclaw/pr-120104-merged.png"
  },
  {
    "slug": "ocr-comparison-paddleocr-vl",
    "title": "OCR的新高度？PaddleOCR-VL 与 DeepSeek-OCR 的技术与应用横评",
    "date": "2025-10-22",
    "href": "",
    "sourceUrl": "https://juejin.cn/post/7563860666349862962",
    "summary": "全面对比两大 OCR 方案的识别精度、部署体验与场景适配性，帮助团队快速选型。",
    "cover": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=60"
  },
  {
    "slug": "blogger-future-community",
    "title": "技术社区已死？博主何去何从？",
    "date": "2025-07-23",
    "href": "",
    "sourceUrl": "https://juejin.cn/post/7529964429057622067",
    "summary": "复盘 2024-2025 年技术社区生态，拆解创作者多平台运营的现实挑战与破局策略。",
    "cover": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=60"
  }
]
