export const DOMAIN_REGISTRY_UPDATED_AT = '2026-08-27'

export const DOMAIN_REGISTRY = [
  {
    id: 'main',
    domain: '2aran.com',
    recordType: 'CNAME',
    target: 'tuaran.pages.dev',
    platform: 'Cloudflare Pages',
    project: 'tuaran',
    audience: 'public',
    lifecycle: 'production',
    role: '内容主站与公共 API',
    proxy: 'proxied',
    status: 'active',
    statusDetail: 'Pages 自定义域与代理 DNS 均已生效。',
  },
  {
    id: 'admin',
    domain: 'admin.2aran.com',
    recordType: 'CNAME',
    target: 'tuaran-admin-git.pages.dev',
    platform: 'Cloudflare Pages',
    project: 'tuaran-admin-git',
    audience: 'private',
    lifecycle: 'production',
    role: '站长后台与管理 API',
    proxy: 'proxied',
    status: 'active',
    statusDetail: '独立 Pages 项目，仅站长访问。',
  },
  {
    id: 'rank',
    domain: 'rank.2aran.com',
    recordType: 'CNAME',
    target: 'tuaran.pages.dev',
    platform: 'Cloudflare Pages · Host 重写',
    project: 'tuaran',
    audience: 'public',
    lifecycle: 'production',
    role: '从夯到拉 AI 排行榜',
    proxy: 'proxied',
    status: 'active',
    statusDetail: '权威 DNS、Pages 自定义域、证书与 HTTP 验证均已生效。',
  },
  {
    id: 'gptplus',
    domain: 'gptplus.2aran.com',
    recordType: 'CNAME',
    target: 'tuaran-gptplus.pages.dev',
    platform: '独立静态 Pages',
    project: 'tuaran-gptplus',
    audience: 'public',
    lifecycle: 'production',
    role: 'GPT Plus 与 Pro 充值服务',
    proxy: 'proxied',
    status: 'active',
    statusDetail: '独立静态项目与自定义域均已生效。',
  },
  {
    id: 'poemcn',
    domain: 'poemcn.2aran.com',
    recordType: 'Worker route',
    target: 'poemcn',
    platform: 'Worker · Assets + D1 + Cron',
    project: 'poemcn',
    audience: 'public',
    lifecycle: 'production',
    role: '中国诗词阅读与数据采集',
    proxy: 'proxied',
    status: 'active',
    statusDetail: '独立 Worker、自定义域、D1 与定时采集均已配置。',
  },
  {
    id: 'workbuddy',
    domain: 'workbuddy.2aran.com',
    recordType: 'Worker route',
    target: 'workbuddy',
    platform: 'Worker · Assets + D1 + R2',
    project: 'workbuddy',
    audience: 'public',
    lifecycle: 'production',
    role: 'WorkBuddy 资源阅读与下载',
    proxy: 'proxied',
    status: 'active',
    statusDetail: '独立 Worker、自定义域、共用 D1 与私有 R2 已上线；身份由主站验证，无需复制签名密钥。',
  },
  {
    id: 'ollama',
    domain: 'ollama.2aran.com',
    recordType: 'Tunnel',
    target: 'ugreen-ollama-tunnel',
    platform: 'Cloudflare Tunnel',
    project: 'ugreen-ollama-tunnel',
    audience: 'private',
    lifecycle: 'production',
    role: 'NAS 本地模型受控入口',
    proxy: 'proxied',
    status: 'active',
    statusDetail: 'Tunnel 代理记录已启用；服务健康由 NAS 侧维护。',
  },
  {
    id: 'ops',
    domain: 'ops.2aran.com',
    recordType: 'Tunnel',
    target: 'agent-ops',
    platform: 'Cloudflare Tunnel',
    project: 'agent-ops',
    audience: 'private',
    lifecycle: 'legacy',
    role: '历史 Agent Ops 入口',
    proxy: 'proxied',
    status: 'legacy',
    statusDetail: '保留兼容；公开站逻辑已将该入口收敛到 /admin/ops。',
  },
]

export function getDomainRecord(domain) {
  return DOMAIN_REGISTRY.find((record) => record.domain === domain) || null
}
