const SOURCES = {
  analects: ['《论语》', 'https://zh.wikisource.org/wiki/論語'],
  laozi: ['《道德经》', 'https://zh.wikisource.org/wiki/道德經'],
  mencius: ['《孟子》', 'https://zh.wikisource.org/wiki/孟子'],
  zhuangzi: ['《庄子》', 'https://zh.wikisource.org/wiki/莊子'],
  xunzi: ['《荀子》', 'https://zh.wikisource.org/wiki/荀子'],
  sunzi: ['《孙子兵法》', 'https://zh.wikisource.org/wiki/孫子兵法'],
  lisao: ['《离骚》', 'https://zh.wikisource.org/wiki/離騷'],
  poetry: ['唐代诗文', 'https://zh.wikisource.org/wiki/Category:唐朝詩歌'],
  taoqian: ['陶渊明诗文', 'https://zh.wikisource.org/wiki/作者:陶淵明'],
  song: ['宋代诗文', 'https://zh.wikisource.org/wiki/Category:宋朝詩歌'],
}

function quote(id, text, author, sourceKey, sourceTitle) {
  const [defaultSource, sourceUrl] = SOURCES[sourceKey]
  return { id, text, author, source: sourceTitle || defaultSource, sourceUrl, enabled: true }
}

export const FAMOUS_QUOTES = [
  quote('analects-001', '学而时习之，不亦说乎？', '孔子', 'analects'),
  quote('analects-002', '有朋自远方来，不亦乐乎？', '孔子', 'analects'),
  quote('analects-003', '人不知而不愠，不亦君子乎？', '孔子', 'analects'),
  quote('analects-004', '巧言令色，鲜矣仁。', '孔子', 'analects'),
  quote('analects-005', '吾日三省吾身。', '曾子', 'analects'),
  quote('analects-006', '温故而知新，可以为师矣。', '孔子', 'analects'),
  quote('analects-007', '学而不思则罔，思而不学则殆。', '孔子', 'analects'),
  quote('analects-008', '知之为知之，不知为不知，是知也。', '孔子', 'analects'),
  quote('analects-009', '三人行，必有我师焉。', '孔子', 'analects'),
  quote('analects-010', '敏而好学，不耻下问。', '孔子', 'analects'),
  quote('analects-011', '己所不欲，勿施于人。', '孔子', 'analects'),
  quote('analects-012', '君子和而不同，小人同而不和。', '孔子', 'analects'),
  quote('analects-013', '岁寒，然后知松柏之后凋也。', '孔子', 'analects'),
  quote('analects-014', '工欲善其事，必先利其器。', '孔子', 'analects'),
  quote('analects-015', '逝者如斯夫，不舍昼夜。', '孔子', 'analects'),
  quote('analects-016', '德不孤，必有邻。', '孔子', 'analects'),
  quote('analects-017', '见贤思齐焉，见不贤而内自省也。', '孔子', 'analects'),
  quote('analects-018', '不患人之不己知，患不知人也。', '孔子', 'analects'),
  quote('analects-019', '过而不改，是谓过矣。', '孔子', 'analects'),
  quote('analects-020', '知者不惑，仁者不忧，勇者不惧。', '孔子', 'analects'),
  quote('laozi-001', '道可道，非常道；名可名，非常名。', '老子', 'laozi'),
  quote('laozi-002', '有无相生，难易相成。', '老子', 'laozi'),
  quote('laozi-003', '上善若水，水善利万物而不争。', '老子', 'laozi'),
  quote('laozi-004', '知人者智，自知者明。', '老子', 'laozi'),
  quote('laozi-005', '胜人者有力，自胜者强。', '老子', 'laozi'),
  quote('laozi-006', '知足者富，强行者有志。', '老子', 'laozi'),
  quote('laozi-007', '千里之行，始于足下。', '老子', 'laozi'),
  quote('laozi-008', '大方无隅，大器晚成。', '老子', 'laozi'),
  quote('laozi-009', '大音希声，大象无形。', '老子', 'laozi'),
  quote('laozi-010', '为学日益，为道日损。', '老子', 'laozi'),
  quote('laozi-011', '治大国，若烹小鲜。', '老子', 'laozi'),
  quote('laozi-012', '祸兮福所倚，福兮祸所伏。', '老子', 'laozi'),
  quote('laozi-013', '合抱之木，生于毫末。', '老子', 'laozi'),
  quote('laozi-014', '慎终如始，则无败事。', '老子', 'laozi'),
  quote('laozi-015', '信言不美，美言不信。', '老子', 'laozi'),
  quote('mencius-001', '仁者无敌。', '孟子', 'mencius'),
  quote('mencius-002', '老吾老，以及人之老。', '孟子', 'mencius'),
  quote('mencius-003', '幼吾幼，以及人之幼。', '孟子', 'mencius'),
  quote('mencius-004', '天时不如地利，地利不如人和。', '孟子', 'mencius'),
  quote('mencius-005', '得道者多助，失道者寡助。', '孟子', 'mencius'),
  quote('mencius-006', '富贵不能淫，贫贱不能移，威武不能屈。', '孟子', 'mencius'),
  quote('mencius-007', '生于忧患，死于安乐。', '孟子', 'mencius'),
  quote('mencius-008', '尽信书，则不如无书。', '孟子', 'mencius'),
  quote('mencius-009', '爱人者，人恒爱之。', '孟子', 'mencius'),
  quote('mencius-010', '敬人者，人恒敬之。', '孟子', 'mencius'),
  quote('mencius-011', '穷则独善其身，达则兼善天下。', '孟子', 'mencius'),
  quote('mencius-012', '不以规矩，不能成方圆。', '孟子', 'mencius'),
  quote('mencius-013', '舍生而取义者也。', '孟子', 'mencius'),
  quote('mencius-014', '仰不愧于天，俯不怍于人。', '孟子', 'mencius'),
  quote('mencius-015', '人有不为也，而后可以有为。', '孟子', 'mencius'),
  quote('zhuangzi-001', '吾生也有涯，而知也无涯。', '庄子', 'zhuangzi'),
  quote('zhuangzi-002', '相濡以沫，不如相忘于江湖。', '庄子', 'zhuangzi'),
  quote('zhuangzi-003', '人生天地之间，若白驹之过隙。', '庄子', 'zhuangzi'),
  quote('zhuangzi-004', '朴素而天下莫能与之争美。', '庄子', 'zhuangzi'),
  quote('zhuangzi-005', '至人无己，神人无功，圣人无名。', '庄子', 'zhuangzi'),
  quote('zhuangzi-006', '井蛙不可以语于海。', '庄子', 'zhuangzi'),
  quote('zhuangzi-007', '天地与我并生，而万物与我为一。', '庄子', 'zhuangzi'),
  quote('zhuangzi-008', '君子之交淡若水。', '庄子', 'zhuangzi'),
  quote('zhuangzi-009', '知其不可奈何而安之若命。', '庄子', 'zhuangzi'),
  quote('zhuangzi-010', '哀莫大于心死。', '庄子', 'zhuangzi'),
  quote('xunzi-001', '青，取之于蓝，而青于蓝。', '荀子', 'xunzi'),
  quote('xunzi-002', '不积跬步，无以至千里。', '荀子', 'xunzi'),
  quote('xunzi-003', '锲而不舍，金石可镂。', '荀子', 'xunzi'),
  quote('xunzi-004', '君子博学而日参省乎己。', '荀子', 'xunzi'),
  quote('xunzi-005', '道虽迩，不行不至。', '荀子', 'xunzi'),
  quote('sunzi-001', '知彼知己，百战不殆。', '孙武', 'sunzi'),
  quote('sunzi-002', '兵无常势，水无常形。', '孙武', 'sunzi'),
  quote('sunzi-003', '上兵伐谋，其次伐交。', '孙武', 'sunzi'),
  quote('sunzi-004', '不战而屈人之兵，善之善者也。', '孙武', 'sunzi'),
  quote('sunzi-005', '攻其无备，出其不意。', '孙武', 'sunzi'),
  quote('poetry-001', '路漫漫其修远兮，吾将上下而求索。', '屈原', 'lisao', '《离骚》'),
  quote('poetry-002', '长太息以掩涕兮，哀民生之多艰。', '屈原', 'lisao', '《离骚》'),
  quote('poetry-003', '亦余心之所善兮，虽九死其犹未悔。', '屈原', 'lisao', '《离骚》'),
  quote('poetry-004', '盛年不重来，一日难再晨。', '陶渊明', 'taoqian', '《杂诗》'),
  quote('poetry-005', '采菊东篱下，悠然见南山。', '陶渊明', 'taoqian', '《饮酒》'),
  quote('poetry-006', '奇文共欣赏，疑义相与析。', '陶渊明', 'taoqian', '《移居》'),
  quote('poetry-007', '海内存知己，天涯若比邻。', '王勃', 'poetry', '《送杜少府之任蜀州》'),
  quote('poetry-008', '落霞与孤鹜齐飞，秋水共长天一色。', '王勃', 'poetry', '《滕王阁序》'),
  quote('poetry-009', '大漠孤烟直，长河落日圆。', '王维', 'poetry', '《使至塞上》'),
  quote('poetry-010', '行到水穷处，坐看云起时。', '王维', 'poetry', '《终南别业》'),
  quote('poetry-011', '独在异乡为异客，每逢佳节倍思亲。', '王维', 'poetry', '《九月九日忆山东兄弟》'),
  quote('poetry-012', '长风破浪会有时，直挂云帆济沧海。', '李白', 'poetry', '《行路难》'),
  quote('poetry-013', '天生我材必有用，千金散尽还复来。', '李白', 'poetry', '《将进酒》'),
  quote('poetry-014', '两岸猿声啼不住，轻舟已过万重山。', '李白', 'poetry', '《早发白帝城》'),
  quote('poetry-015', '会当凌绝顶，一览众山小。', '杜甫', 'poetry', '《望岳》'),
  quote('poetry-016', '读书破万卷，下笔如有神。', '杜甫', 'poetry', '《奉赠韦左丞丈二十二韵》'),
  quote('poetry-017', '随风潜入夜，润物细无声。', '杜甫', 'poetry', '《春夜喜雨》'),
  quote('poetry-018', '野火烧不尽，春风吹又生。', '白居易', 'poetry', '《赋得古原草送别》'),
  quote('poetry-019', '同是天涯沦落人，相逢何必曾相识。', '白居易', 'poetry', '《琵琶行》'),
  quote('poetry-020', '日出江花红胜火，春来江水绿如蓝。', '白居易', 'poetry', '《忆江南》'),
  quote('poetry-021', '沉舟侧畔千帆过，病树前头万木春。', '刘禹锡', 'poetry', '《酬乐天扬州初逢席上见赠》'),
  quote('poetry-022', '旧时王谢堂前燕，飞入寻常百姓家。', '刘禹锡', 'poetry', '《乌衣巷》'),
  quote('poetry-023', '山重水复疑无路，柳暗花明又一村。', '陆游', 'song', '《游山西村》'),
  quote('poetry-024', '纸上得来终觉浅，绝知此事要躬行。', '陆游', 'song', '《冬夜读书示子聿》'),
  quote('poetry-025', '不畏浮云遮望眼，自缘身在最高层。', '王安石', 'song', '《登飞来峰》'),
  quote('poetry-026', '春风又绿江南岸，明月何时照我还。', '王安石', 'song', '《泊船瓜洲》'),
  quote('poetry-027', '不识庐山真面目，只缘身在此山中。', '苏轼', 'song', '《题西林壁》'),
  quote('poetry-028', '竹外桃花三两枝，春江水暖鸭先知。', '苏轼', 'song', '《惠崇春江晚景》'),
  quote('poetry-029', '问渠那得清如许？为有源头活水来。', '朱熹', 'song', '《观书有感》'),
  quote('poetry-030', '等闲识得东风面，万紫千红总是春。', '朱熹', 'song', '《春日》'),
]

export const DEFAULT_FAMOUS_QUOTE = FAMOUS_QUOTES[26]
