export const HOME_RECOMMENDATIONS = [
  {
    id: 'blogger-alliance',
    href: 'https://blogger-alliance.cn/',
    eyebrow: '立即加入',
    eyebrowEn: 'Join now',
    title: '博主联盟',
    titleEn: 'Blogger Alliance',
    desc: '连接 AI 产品方与技术博主，把产品曝光、内容种草和真实转化放进一个长期协作网络。',
    descEn: 'Connects AI products with tech bloggers — product exposure, content seeding and real conversion in one long-term network.',
    points: ['产品增长', '博主合作', '内容分发'],
    pointsEn: ['Product growth', 'Blogger collab', 'Content reach'],
    actionLabel: '进入博主联盟',
    actionLabelEn: 'Enter Blogger Alliance',
  },
  {
    id: 'frontendnext',
    href: 'https://frontendnext.com/',
    eyebrow: '推荐阅读',
    eyebrowEn: 'Recommended',
    title: '前端周看',
    titleEn: 'Frontend Weekly',
    desc: '持续追踪前端、AI Agent 与大模型工程，把值得关注的技术变化整理成可读情报。',
    descEn: 'Tracks frontend, AI Agents and LLM engineering, turning notable shifts into readable intel.',
    points: ['前端趋势', 'AI Agent', '大模型工程'],
    pointsEn: ['Frontend trends', 'AI Agent', 'LLM engineering'],
    actionLabel: '查看前端周看',
    actionLabelEn: 'Read Frontend Weekly',
  },
  {
    id: 'publishlab',
    href: 'https://publishlab.cc/',
    eyebrow: '创作工具',
    eyebrowEn: 'Creator tool',
    title: 'PublishLab',
    titleEn: 'PublishLab',
    desc: '面向创作者的 AI 写作与出版工具，把选题、写作、编辑和发布流程沉淀成系统。',
    descEn: 'AI writing and publishing tools for creators — turning topic, drafting, editing and publishing into a system.',
    points: ['AI 写作', '内容创作', '数字出版'],
    pointsEn: ['AI writing', 'Content', 'Publishing'],
    actionLabel: '使用 PublishLab',
    actionLabelEn: 'Use PublishLab',
  },
]
