/**
 * 站内资源条目，供知识库索引与首页推荐阅读共用。资料类（文字/文本内容）是资源的子集。
 * /bookmarks/*、/resources/* 有实质内容更新时，补 `updated`（日期或带时区时间），
 * RSS 会据此生成新的版本化 GUID，向已有订阅者发送更新通知。
 */
export const HOME_RESOURCE_ITEMS = [
  {
    title: '梁文锋投资者交流会：录音文字稿',
    summary: '一份约 3 小时 44 分钟投资者交流录音的 42 页文字稿，讨论 DeepSeek 的愿景、开源与商业化、AGI 路线、算力和国产芯片。',
    date: '2026-07-23',
    href: '/resources/liang-wenfeng-investor-meeting',
    resourceType: 'humanities-politics',
    subjects: ['ai_dev'],
    tagLabel: '资源库 · AI 与商业',
  },
  {
    title: '边缘智能体开发实战',
    summary: '从 Agent 原型到 Cloudflare 边缘 SaaS 的 6 章 16 节工程化课程目录与学习路线。',
    date: '2026-07-13',
    href: '/resources/edge-agent-development',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · Agent 开发',
  },
  {
    title: '安东尼学 AI',
    summary: '按机器学习、深度学习、NLP、计算机视觉与工程实践整理的 AI 经典书目和学习资料索引。',
    date: '2026-07-13',
    href: '/resources/ai-learning-library',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · AI 学习',
  },
  {
    title: 'Awesome Nano Banana Images',
    summary: '141 个 Nano Banana 与 Nano Banana Pro 图像生成、编辑案例，支持搜索、输入输出对比和一键复制提示词。',
    date: '2026-07-13',
    href: '/resources/nano-banana-gallery',
    resourceType: 'ai-dev',
    subjects: ['content_creation'],
    tagLabel: '资源库 · AI 视觉案例',
  },
  {
    title: 'GPT 不解释｜AI 音乐',
    summary: 'tuaran 的 AI 音乐单曲《GPT 不解释》。在站内卡片页查看曲目信息、跳转网易云音乐播放，并可一键分享。',
    date: '2026-07-10',
    href: '/resources/ai-music',
    resourceType: 'ai-music',
    tagLabel: '资源库 · AI 音乐',
  },
  {
    title: '壁纸下载',
    summary: '按主题整理的可下载壁纸资源，支持分类筛选与原图下载。',
    date: '2026-07-10',
    href: '/resources/wallpapers',
    resourceType: 'visual-assets',
    tagLabel: '资源库 · 视觉资源',
  },
  {
    title: '速通投资',
    summary: '把投资书单整理成一页可执行资源：价值投资、市场随机性、风险周期、财报、投资大师和金钱心理学。',
    date: '2026-07-09',
    href: '/resources/speedrun-investing',
    resourceType: 'humanities-politics',
    subjects: ['business_market'],
    tagLabel: '资源库 · 投资书单',
  },
  {
    title: '我的 RSS 订阅',
    summary: '我长期关注的博客与周刊订阅墙：阮一峰的网络日志等，可一键复制 feed 到你的阅读器。',
    date: '2026-06-29',
    href: '/resources/rss',
    resourceType: 'rss',
    tagLabel: '资源库 · RSS 订阅',
  },
  {
    title: '单篇封神的中国古典名篇',
    summary: '辞赋、唐诗宋词、政论奏疏、古文散文、祭文书信 —— 古典文学高密度原文索引，可检索、可引用。',
    date: '2026-05-20',
    href: '/classical-masterpieces',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 古典名篇',
  },
  {
    title: '儒释道 · 神仙体系',
    summary: '佛教五层果位、道教十级神格、儒家文庙道统 —— 三教神仙体系结构图。',
    date: '2026-05-21',
    href: '/ru-shi-dao',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 人文思想',
  },
  {
    title: '中国政治体制',
    summary: '中央与国务院组织结构、历届三中全会、领导层沿革（1971–至今）。',
    date: '2026-05-21',
    href: '/china-politics',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 政经资料',
  },
  {
    title: '历史资料：明清与三国',
    summary: '以时间线梳理三国、明清 —— 曹操、朱元璋、朱棣、嘉靖、张居正、万历、康熙、雍正的制度、权力与人物命运。',
    date: '2026-05-20',
    href: '/history/ming-qing',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 人文思想',
  },
  {
    title: '书目索引',
    summary: '正在读、想读、读书笔记和待写书单统一沉淀，作为长期输入与选题来源。',
    date: '2026-05-20',
    href: '/reading',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 书目索引',
  },
  {
    title: '推特资讯',
    summary: 'Twitter/X 上值得关注的前沿动态、技术观点与行业洞察。',
    date: '2026-05-20',
    href: '/bookmarks/twitter',
    resourceType: 'twitter',
    tagLabel: '资源库 · 推特资讯',
  },
  {
    title: 'YouTube 收藏',
    summary: '按主题整理的影像收藏：政治、历史、二战、纪录片与延伸资料。',
    date: '2026-05-20',
    href: '/bookmarks/youtube',
    resourceType: 'youtube',
    tagLabel: '资源库 · YouTube 收藏',
  },
  {
    title: '大模型教程',
    summary: '大语言模型（LLM）相关的优质教程、实践指南与技术文档。',
    date: '2026-05-20',
    href: '/bookmarks/llm-tutorials',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · 大模型教程',
  },
  {
    title: 'AI 工具',
    summary: '实用的 AI 工具、产品与服务推荐。',
    date: '2026-05-20',
    href: '/bookmarks/ai-tools',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · AI 工具',
  },
  {
    title: '开发资源',
    summary: '前端、后端、DevOps 等开发相关的优质资源与工具链。',
    date: '2026-05-20',
    href: '/bookmarks/dev-resources',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · 开发资源',
  },
  {
    title: 'Codex 学习资源收集',
    summary: '逸尘 X 链接帖归档：Codex 入门、记忆系统、Agent 开发、工具自动化与 Computer Use 案例。',
    date: '2026-06-29',
    href: '/resources/codex-learning-resource-map-yichen',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · Codex 学习',
  },
  {
    title: '置身 X 内：大厂职场文本存档合集',
    summary:
      '钉钉《置身钉内》×《置身钉外》、美团《置身团内》、小米《置身米内》、字节《置身 dou 内 / 抖内》——「置身 X 内」系列大厂职场文本，可切换对照阅读；配套观察见知识库「职场」分类。',
    date: '2026-06-26',
    href: '/resources/shen-zhi-ding-nei',
    resourceType: 'workplace',
    tagLabel: '资源库 · 职场资源',
  },
]
