/** 站内资源条目，供知识库索引与首页推荐阅读共用。资料类（文字/文本内容）是资源的子集。 */
export const HOME_RESOURCE_ITEMS = [
  {
    title: '我的 RSS 订阅',
    summary: '我长期关注的博客与周刊订阅墙：阮一峰的网络日志等，可一键复制 feed 到你的阅读器。',
    date: '2026-06-29',
    href: '/resources/rss',
    resourceType: 'external-archive',
    tagLabel: '资源库 · RSS 订阅',
  },
  {
    title: '单篇封神的中国古典名篇',
    summary: '辞赋、唐诗宋词、政论奏疏、古文散文、祭文书信 —— 古典文学高密度原文索引，可检索、可引用。',
    date: '2026-05-20',
    href: '/classical-masterpieces',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 古典名篇',
  },
  {
    title: '儒释道 · 神仙体系',
    summary: '佛教五层果位、道教十级神格、儒家文庙道统 —— 三教神仙体系结构图。',
    date: '2026-05-21',
    href: '/ru-shi-dao',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 人文思想',
  },
  {
    title: '中国政治体制',
    summary: '中央与国务院组织结构、历届三中全会、领导层沿革（1971–至今）。',
    date: '2026-05-21',
    href: '/china-politics',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 政经资料',
  },
  {
    title: '历史资料：明清与三国',
    summary: '以时间线梳理三国、明清 —— 曹操、朱元璋、朱棣、嘉靖、张居正、万历、康熙、雍正的制度、权力与人物命运。',
    date: '2026-05-20',
    href: '/history/ming-qing',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 人文思想',
  },
  {
    title: '书目索引',
    summary: '正在读、想读、读书笔记和待写书单统一沉淀，作为长期输入与选题来源。',
    date: '2026-05-20',
    href: '/reading',
    resourceType: 'humanities-politics',
    tagLabel: '资源库 · 书目索引',
  },
  {
    title: '推特资讯',
    summary: 'Twitter/X 上值得关注的前沿动态、技术观点与行业洞察。',
    date: '2026-05-20',
    href: '/bookmarks/twitter',
    resourceType: 'external-archive',
    tagLabel: '资源库 · 推特资讯',
  },
  {
    title: 'YouTube 收藏',
    summary: '按主题整理的影像收藏：政治、历史、二战、纪录片与延伸资料。',
    date: '2026-05-20',
    href: '/bookmarks/youtube',
    resourceType: 'external-archive',
    tagLabel: '资源库 · YouTube 收藏',
  },
  {
    title: '大模型教程',
    summary: '大语言模型（LLM）相关的优质教程、实践指南与技术文档。',
    date: '2026-05-20',
    href: '/bookmarks/llm-tutorials',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · 大模型教程',
  },
  {
    title: 'AI 工具',
    summary: '实用的 AI 工具、产品与服务推荐。',
    date: '2026-05-20',
    href: '/bookmarks/ai-tools',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · AI 工具',
  },
  {
    title: '开发资源',
    summary: '前端、后端、DevOps 等开发相关的优质资源与工具链。',
    date: '2026-05-20',
    href: '/bookmarks/dev-resources',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · 开发资源',
  },
  {
    title: 'Codex 学习资源收集',
    summary: '逸尘 X 链接帖归档：Codex 入门、记忆系统、Agent 开发、工具自动化与 Computer Use 案例。',
    date: '2026-06-29',
    href: '/resources/codex-learning-resource-map-yichen',
    resourceType: 'ai-dev',
    tagLabel: '资源库 · Codex 学习',
  },
  {
    title: '置身 X 内：大厂职场文本存档合集',
    summary:
      '钉钉《置身钉内》×《置身钉外》、美团《置身团内》、小米《置身米内》、字节《置身 dou 内 / 抖内》——「置身 X 内」系列大厂职场文本，可切换对照阅读；配套观察见知识库「职场」分类。',
    date: '2026-06-26',
    href: '/resources/shen-zhi-ding-nei',
    resourceType: 'workplace',
    tagLabel: '资源库 · 职场资料',
  },
]
