/** 站内资料与资源收藏条目，供知识库索引与首页推荐阅读共用。 */
export const HOME_RESOURCE_ITEMS = [
  {
    title: '单篇封神的中国古典名篇',
    summary: '辞赋、唐诗宋词、政论奏疏、古文散文、祭文书信 —— 古典文学高密度原文索引，可检索、可引用。',
    date: '2026-05-20',
    href: '/classical-masterpieces',
    resourceType: 'classics',
    tagLabel: '资料库 · 古典名篇',
  },
  {
    title: '儒释道 · 神仙体系',
    summary: '佛教五层果位、道教十级神格、儒家文庙道统 —— 三教神仙体系结构图。',
    date: '2026-05-21',
    href: '/ru-shi-dao',
    resourceType: 'humanities',
    tagLabel: '资料库 · 人文思想',
  },
  {
    title: '中国政治体制',
    summary: '中央与国务院组织结构、历届三中全会、领导层沿革（1971–至今）。',
    date: '2026-05-21',
    href: '/china-politics',
    resourceType: 'politics',
    tagLabel: '资料库 · 政经资料',
  },
  {
    title: '历史资料：明清与三国',
    summary: '以时间线梳理三国、明清 —— 曹操、朱元璋、朱棣、嘉靖、张居正、万历、康熙、雍正的制度、权力与人物命运。',
    date: '2026-05-20',
    href: '/history/ming-qing',
    resourceType: 'humanities',
    tagLabel: '资料库 · 人文思想',
  },
  {
    title: '书目索引',
    summary: '正在读、想读、读书笔记和待写书单统一沉淀，作为长期输入与选题来源。',
    date: '2026-05-20',
    href: '/reading',
    resourceType: 'books',
    tagLabel: '资料库 · 书目索引',
  },
  {
    title: '资源收藏',
    summary: 'AI 工具、开发资源、LLM 教程、Twitter / YouTube 收藏与外部材料入口。',
    date: '2026-05-20',
    href: '/bookmarks',
    resourceType: 'bookmarks',
    tagLabel: '资料库 · 资源收藏',
  },
]
