export const HOME_RECOMMENDATIONS = [
  {
    id: 'blogger-alliance',
    href: 'https://blogger-alliance.cn/',
    eyebrow: '立即加入',
    eyebrowEn: 'Join now',
    title: '博主联盟',
    titleEn: 'Blogger Alliance',
    desc: '连接 AI 产品方与技术博主，把产品曝光、内容种草和真实转化放进一个长期协作网络。',
    descEn: 'Connects AI products with tech bloggers — product exposure, content seeding and real conversion in one long-term network.',
    points: ['产品增长', '博主合作', '内容分发'],
    pointsEn: ['Product growth', 'Blogger collab', 'Content reach'],
    actionLabel: '进入博主联盟',
    actionLabelEn: 'Enter Blogger Alliance',
  },
  {
    id: 'frontendnext',
    href: 'https://frontendnext.com/',
    eyebrow: '推荐阅读',
    eyebrowEn: 'Recommended',
    title: '前端周看',
    titleEn: 'Frontend Weekly',
    desc: '持续追踪前端、AI Agent 与大模型工程，把值得关注的技术变化整理成可读情报。',
    descEn: 'Tracks frontend, AI Agents and LLM engineering, turning notable shifts into readable intel.',
    points: ['前端趋势', 'AI Agent', '大模型工程'],
    pointsEn: ['Frontend trends', 'AI Agent', 'LLM engineering'],
    actionLabel: '查看前端周看',
    actionLabelEn: 'Read Frontend Weekly',
  },
  {
    id: 'syncblog',
    href: 'https://syncblog.cn/',
    eyebrow: '内容同步',
    eyebrowEn: 'Content sync',
    title: '内容同步智能体',
    titleEn: 'SyncBlog',
    desc: '一次创作，自动同步分发到多个平台，把多平台发布流程交给 Agent。',
    descEn: 'A content sync agent — write once, auto-distribute across multiple platforms.',
    points: ['一次创作', '多平台同步', '自动分发'],
    pointsEn: ['Write once', 'Multi-platform sync', 'Auto distribute'],
    actionLabel: '使用内容同步智能体',
    actionLabelEn: 'Use SyncBlog',
  },
]
