export const SECONDARY_SITES = [
  {
    id: 'rank',
    label: '从夯到拉',
    labelEn: 'AI Tier List',
    href: 'https://rank.2aran.com/',
    domain: 'rank.2aran.com',
    category: 'AI 工具',
    deployment: '复用主站 Pages · Host 重写',
    deploymentDetail: '轻交互页面，无独立 API、数据库与定时任务。',
    desc: '一份可以自己拖、自己改的 AI 产品分级榜。',
    detail: '按真实使用体验把主流 AI 产品分成五档，支持拖拽换档、场景筛选、本机保存与一键复制。',
    tags: ['AI 排行榜', 'Tier List', '互动工具'],
  },
  {
    id: 'gptplus',
    label: 'GPT Plus 充值',
    labelEn: 'GPT Plus Recharge',
    href: 'https://gptplus.2aran.com/',
    domain: 'gptplus.2aran.com',
    category: 'AI 服务',
    deployment: '独立静态站 · 单独发布',
    deploymentDetail: '商业服务页面，保持独立品牌与发布节奏。',
    desc: 'ChatGPT Plus 与 Pro 订阅充值服务。',
    detail: '提供套餐选择、订单处理、进度查询与售后支持，适合个人订阅和企业采购。',
    tags: ['ChatGPT', 'Plus / Pro', '充值服务'],
  },
  {
    id: 'poemcn',
    label: '中国诗词',
    labelEn: 'Chinese Poetry',
    href: 'https://poemcn.2aran.com/',
    domain: 'poemcn.2aran.com',
    category: '文化资料',
    deployment: '独立 Worker · D1 + Cron',
    deploymentDetail: '自带搜索 API、独立数据库和定时内容采集。',
    desc: '持续扩充的历代诗文资料库。',
    detail: '按朝代、作者、体裁和主题整理古典诗文，持续补充原文、注释、译文与分类信息。',
    tags: ['古诗词', '古文', '传统文化'],
  },
  {
    id: 'workbuddy',
    label: 'WorkBuddy 资源库',
    labelEn: 'WorkBuddy Resource Library',
    href: 'https://workbuddy.2aran.com/',
    domain: 'workbuddy.2aran.com',
    category: '效率资源',
    deployment: '独立 Worker · D1 + R2',
    deploymentDetail: '资源目录与燃币权益使用 D1，受控阅读和下载文件存储在 R2。',
    desc: 'WorkBuddy 案例、教程、Prompt 模板与自动化实战资源库。',
    detail: '按场景整理 WorkBuddy 中文资料，游客可直接用燃币解锁，之后反复阅读和下载。',
    tags: ['WorkBuddy', '职场效率', '资源下载'],
  },
]
