export const SECONDARY_SITES = [
  {
    id: 'rank',
    label: '从夯到拉',
    labelEn: 'AI Tier List',
    href: 'https://rank.2aran.com/',
    domain: 'rank.2aran.com',
    category: 'AI 工具',
    desc: '一份可以自己拖、自己改的 AI 产品分级榜。',
    detail: '按真实使用体验把主流 AI 产品分成五档，支持拖拽换档、场景筛选、本机保存与一键复制。',
    tags: ['AI 排行榜', 'Tier List', '互动工具'],
  },
  {
    id: 'gptplus',
    label: 'GPT Plus 充值',
    labelEn: 'GPT Plus Recharge',
    href: 'https://gptplus.2aran.com/',
    domain: 'gptplus.2aran.com',
    category: 'AI 服务',
    desc: 'ChatGPT Plus 与 Pro 订阅充值服务。',
    detail: '提供套餐选择、订单处理、进度查询与售后支持，适合个人订阅和企业采购。',
    tags: ['ChatGPT', 'Plus / Pro', '充值服务'],
  },
  {
    id: 'poemcn',
    label: '中国诗词',
    labelEn: 'Chinese Poetry',
    href: 'https://poemcn.2aran.com/',
    domain: 'poemcn.2aran.com',
    category: '文化资料',
    desc: '持续扩充的历代诗文资料库。',
    detail: '按朝代、作者、体裁和主题整理古典诗文，持续补充原文、注释、译文与分类信息。',
    tags: ['古诗词', '古文', '传统文化'],
  },
]
