export const SECONDARY_SITES = [
  {
    id: 'weekly',
    label: '前端周看',
    labelEn: 'Frontend Weekly',
    href: 'https://weekly.2aran.com/',
    domain: 'weekly.2aran.com',
    category: '技术阅读',
    deployment: '独立 Pages · 共用主站账号',
    deploymentDetail: '独立部署的技术周刊，主站统一提供账号、燃币余额与签到；周刊阅读免费。',
    desc: '前端、AI Agent 与大模型工程周刊。',
    descEn: 'Weekly reading on frontend, AI agents and LLM engineering.',
    detail: '浏览技术文章、开源项目和工具动态，查阅历史周刊。',
    accessNote: '使用主站账号登录，查看燃币余额并签到；周刊阅读保持免费。',
    actionLabel: '打开子站',
    tags: ['前端', 'AI Agent', '技术周刊'],
  },
  {
    id: 'syncblog',
    label: 'AI 分发大师',
    labelEn: 'SyncBlog',
    href: 'https://syncblog.2aran.com/',
    domain: 'syncblog.2aran.com',
    category: '创作工具',
    deployment: '独立 Worker · 共用主站账号',
    deploymentDetail: '编辑与分发业务独立部署；原账号和 AI 额度保留，主站统一提供燃币余额与签到。',
    desc: 'Markdown 编辑、草稿管理与多平台分发。',
    descEn: 'Markdown editing, drafts and multi-platform distribution.',
    detail: '编辑 Markdown、管理草稿并同步到内容平台；可验证关联原账号，继续使用已有 AI 额度。',
    accessNote: '使用主站账号登录，查看燃币余额并签到；原 AI 额度保留，不新增扣费。',
    actionLabel: '打开子站',
    tags: ['Markdown', '多平台分发', '创作'],
  },
  {
    id: 'rank',
    label: '从夯到拉',
    labelEn: 'AI Tier List',
    href: 'https://rank.2aran.com/',
    domain: 'rank.2aran.com',
    category: 'AI 工具',
    deployment: '复用主站 Pages · Host 重写',
    deploymentDetail: '轻交互页面，无独立 API、数据库与定时任务。',
    desc: '一份可以自己拖、自己改的 AI 产品分级榜。',
    detail: '按真实使用体验把主流 AI 产品分成五档，支持拖拽换档、场景筛选、本机保存与一键复制。',
    tags: ['AI 排行榜', 'Tier List', '互动工具'],
  },
  {
    id: 'gptplus',
    label: 'GPT Plus 充值',
    labelEn: 'GPT Plus Recharge',
    href: 'https://gptplus.2aran.com/',
    domain: 'gptplus.2aran.com',
    category: 'AI 服务',
    deployment: '独立静态站 · 单独发布',
    deploymentDetail: '商业服务页面，保持独立品牌与发布节奏。',
    desc: 'ChatGPT Plus 与 Pro 订阅充值服务。',
    detail: '提供套餐选择、订单处理、进度查询与售后支持，适合个人订阅和企业采购。',
    tags: ['ChatGPT', 'Plus / Pro', '充值服务'],
  },
  {
    id: 'poemcn',
    label: '阿燃诗词',
    labelEn: 'Aran Poetry',
    href: 'https://poemcn.2aran.com/',
    domain: 'poemcn.2aran.com',
    category: '文化资料',
    deployment: '独立 Worker · D1 + Cron',
    deploymentDetail: '自带搜索 API、独立数据库和定时内容采集。',
    desc: '阿燃诗词：按诗名、作者和诗句查找古诗词与文言文。',
    detail: '按朝代、作者、体裁和主题整理古典诗文，持续补充原文、注释、译文与分类信息。',
    tags: ['古诗词', '古文', '传统文化'],
  },
  {
    id: 'workbuddy',
    label: 'WorkBuddy 资源库',
    labelEn: 'WorkBuddy Resource Library',
    href: 'https://workbuddy.2aran.com/',
    domain: 'workbuddy.2aran.com',
    category: '效率资源',
    deployment: '独立 Worker · D1 + R2',
    deploymentDetail: '资源目录与燃币权益使用 D1，受控阅读和下载文件存储在 R2。',
    desc: 'WorkBuddy 案例、教程、Prompt 模板与自动化实战资源库。',
    detail: '按场景整理 WorkBuddy 中文资料，游客可直接用燃币解锁，之后反复阅读和下载。',
    tags: ['WorkBuddy', '职场效率', '资源下载'],
  },
]
