// This file is rewritten by scripts/archive-spacex-video.mjs after a launch is verified.
// Keep the export as a plain array so the archive can run in Next.js' Edge runtime.
export const SPACEX_ARCHIVED_LAUNCHES = [
  {
    id: 'spacex-ussf-259-2026-09-17',
    publishedAt: '2026-09-17T01:07:56Z',
    kind: 'launch',
    topic: 'Falcon',
    title: 'USSF-259：分类载荷从范登堡升空',
    titleEn: 'USSF-259: Classified payload launched from Vandenberg',
    summary: 'Falcon 9 从加州范登堡太空军基地 SLC-4E 发射美国太空军 USSF-259 分类载荷，任务细节未公开。一级助推器 B1097 完成第 13 次飞行，并成功着陆“Of Course I Still Love You”无人船。',
    summaryEn: 'A Falcon 9 launched the U.S. Space Force\'s classified USSF-259 payload from SLC-4E at Vandenberg Space Force Base; mission details were not disclosed. Booster B1097 completed its 13th flight and landed on the droneship Of Course I Still Love You.',
    sourceLabel: 'SpaceX · USSF-259',
    sourceUrl: 'https://www.spacex.com/launches/ussf259',
    note: '发射成功 · 加州当地时间 2026.09.16 18:07:56 PDT · 载荷信息分类',
    noteEn: 'Launch successful · September 16, 2026 at 6:07:56 p.m. PDT · Classified payload',
    phase: 'previous',
    status: 'Launch Successful',
    video: {
      src: '/videos/ussf-259-liftoff-2026-09-17.mp4',
      label: 'USSF-259 从 SLC-4E 点火升空（T−0:09 至 T+0:22）',
      credit: '影像：SpaceX',
      postUrl: 'https://x.com/SpaceX/status/2100388085481578744',
    },
    originalLanguage: 'en',
    titleOriginal: 'USSF-259: Classified payload launched from Vandenberg',
    summaryOriginal: 'A Falcon 9 launched the U.S. Space Force\'s classified USSF-259 payload from SLC-4E at Vandenberg Space Force Base; mission details were not disclosed. Booster B1097 completed its 13th flight and landed on the droneship Of Course I Still Love You.',
    noteOriginal: 'Launch successful · September 16, 2026 at 6:07:56 p.m. PDT · Classified payload',
    titleTranslated: 'USSF-259：分类载荷从范登堡升空',
    summaryTranslated: 'Falcon 9 从加州范登堡太空军基地 SLC-4E 发射美国太空军 USSF-259 分类载荷，任务细节未公开。一级助推器 B1097 完成第 13 次飞行，并成功着陆“Of Course I Still Love You”无人船。',
    noteTranslated: '发射成功 · 加州当地时间 2026.09.16 18:07:56 PDT · 载荷信息分类',
  },
  {
    id: 'spacex-starlink-15-27-2026-09-20',
    publishedAt: '2026-09-20T01:47:00Z',
    kind: 'launch',
    topic: 'Starlink',
    title: 'Starlink 15-27：27 颗卫星进入低地球轨道',
    titleEn: 'Starlink 15-27: 27 satellites launched to low Earth orbit',
    summary: 'Falcon 9 从加州范登堡太空军基地 SLC-4E 发射。一级助推器 B1093 完成第 17 次飞行，并在“Of Course I Still Love You”无人船着陆；任务使用的一枚整流罩半体完成第 40 次飞行。',
    summaryEn: 'A Falcon 9 lifted off from SLC-4E at Vandenberg Space Force Base. Booster B1093 completed its 17th flight and landed on the droneship Of Course I Still Love You; one payload fairing half completed its 40th flight.',
    sourceLabel: 'SpaceX · Starlink 15-27',
    sourceUrl: 'https://x.com/SpaceX/status/2101489521615385011',
    note: '发射成功 · 加州当地时间 2026.09.19 18:47 PDT',
    noteEn: 'Launch successful · September 19, 2026 at 6:47 p.m. PDT',
    phase: 'previous',
    status: 'Launch Successful',
    video: {
      src: '/videos/starlink-15-27-fairing-separation-2026-09-20.mp4',
      label: '整流罩分离后的在轨画面（T+3:05）',
      credit: '影像：SpaceX',
      postUrl: 'https://x.com/SpaceX/status/2101489521615385011',
    },
    originalLanguage: 'en',
    titleOriginal: 'Starlink 15-27: 27 satellites launched to low Earth orbit',
    summaryOriginal: 'A Falcon 9 lifted off from SLC-4E at Vandenberg Space Force Base. Booster B1093 completed its 17th flight and landed on the droneship Of Course I Still Love You; one payload fairing half completed its 40th flight.',
    noteOriginal: 'Launch successful · September 19, 2026 at 6:47 p.m. PDT',
    titleTranslated: 'Starlink 15-27：27 颗卫星进入低地球轨道',
    summaryTranslated: 'Falcon 9 从加州范登堡太空军基地 SLC-4E 发射。一级助推器 B1093 完成第 17 次飞行，并在“Of Course I Still Love You”无人船着陆；任务使用的一枚整流罩半体完成第 40 次飞行。',
    noteTranslated: '发射成功 · 加州当地时间 2026.09.19 18:47 PDT',
  },
]
