export const TOOL_TYPE_META = [
  {
    id: 'direct',
    anchor: 'online',
    title: '在线服务与实用工具',
    titleEn: 'Online Tools & Services',
    description: '网页可用的文档处理、图片托管、链接管理、生活与活动工具。',
  },
  {
    id: 'extension',
    anchor: 'downloads',
    title: '插件与下载',
    titleEn: 'Extensions & Downloads',
    description: '可下载安装到本地环境的轻量工具。',
  },
  {
    id: 'x-platform',
    anchor: 'x-platform',
    title: 'X 平台工具',
    titleEn: 'X Platform Tools',
    description: '围绕 X 内容保存、账号关系管理和账号状态检查的实用工具。',
  },
  {
    id: 'analysis',
    anchor: 'analysis',
    title: '监测与分析工具',
    titleEn: 'Monitoring & Analysis',
    description: '面向公开信息采集、趋势观察和研判的交互式工作台。',
  },
  {
    id: 'ai-system',
    anchor: 'ai-systems',
    title: 'AI 能力系统',
    titleEn: 'AI Capability Systems',
    description: 'Skill、MCP 与 Prompt 三个系统，以及各自收录的能力、服务和任务模板。',
  },
  {
    id: 'ai-dev',
    anchor: 'ai-dev',
    title: 'AI 与开发工具',
    titleEn: 'AI & Dev Tools',
    description: '围绕 AI 工程、开发者工作流和工具链的入口。',
  },
  {
    id: 'index',
    anchor: 'indexes',
    title: '工具索引',
    titleEn: 'Tool Indexes',
    description: '按主题整理的外部工具、开发资源与选型地图。',
  },
]

export const TOOL_STATUS_META = {
  live: '可用',
  external: '外部',
  index: '索引',
  experiment: '实验',
}

export const TOOL_ITEMS = [
  {
    id: 'codex-model-switcher',
    title: 'Codex 模型切换器',
    href: '/resources/codex-model-switcher',
    type: 'extension',
    status: 'live',
    summary: 'macOS 窗口与菜单栏工具，在 OpenAI GPT 与已配置的 DeepSeek Provider 之间切换；另提供可交给 Codex 自动安装的 Skill。',
    tags: ['macOS', 'Codex', 'Skill'],
    priority: 100,
  },
  {
    id: 'github-follow',
    title: 'GitHub 批量关注',
    href: '/tools/github-follow',
    type: 'ai-dev',
    status: 'live',
    summary: '从用户名或仓库贡献者生成候选，检查资料并确认后批量关注；Token 仅由浏览器直连 GitHub。',
    tags: ['GitHub', '开源社区', '浏览器直连'],
    priority: 98,
  },
  {
    id: 'syncblog-publisher',
    title: 'Syncblog 同步助手',
    href: '/tools/syncblog-publisher',
    type: 'extension',
    status: 'live',
    summary: 'AI 分发大师配套浏览器扩展，利用本地登录状态将内容同步到多个平台。',
    tags: ['浏览器扩展', '内容分发', 'Syncblog'],
    priority: 99,
  },
  {
    id: 'openclaw-pr-helper',
    title: 'OpenClaw PR Helper',
    href: '/tools/openclaw-pr-helper',
    type: 'ai-dev',
    status: 'external',
    summary: '本地筛选低风险 Issue、生成真实验证证据，并以 dry-run 优先方式完成开源贡献。',
    tags: ['OpenClaw', 'GitHub PR', '本地 CLI'],
    priority: 94,
  },
  {
    id: 'multi-ip',
    title: '多出口 IP 工具',
    href: '/tools/multi-ip',
    type: 'direct',
    status: 'live',
    summary: '检测浏览器与 Cloudflare 边缘出口 IP，整理、去重并导出 HTTP/SOCKS5 代理池配置。',
    tags: ['IP 检测', '代理池', 'Cloudflare'],
    priority: 100,
  },
  {
    id: 'html-to-pdf',
    title: 'HTML 转 PDF',
    href: '/tools/html-to-pdf',
    type: 'direct',
    status: 'live',
    summary: '公开开源的本地 HTML 打印工具，支持 A4、缩放、背景保留和常见中文字体别名。',
    tags: ['PDF', 'HTML', '本地处理'],
    priority: 99,
  },
  {
    id: 'image-hosting',
    title: '图片 / 视频床',
    href: '/tools/image-hosting',
    type: 'direct',
    status: 'live',
    summary: '登录后上传图片或视频到站内 R2，生成公开分享页与文件直链；每个文件消耗 5 燃币。',
    tags: ['图片上传', '视频上传', '登录可用', '燃币'],
    priority: 97,
  },
  {
    id: 'digital-human',
    title: '数字人口播',
    href: '/tools/digital-human',
    type: 'direct',
    status: 'experiment',
    summary: '上传一张人物照片并输入中文文案，生成可以播放和下载的 AI 数字人口播视频。',
    tags: ['数字人', 'AI 视频', '登录可用'],
    priority: 96,
  },
  {
    id: 'voice-tasks',
    title: '语音记事',
    href: '/voice-tasks',
    type: 'direct',
    status: 'live',
    summary: '登录后点击麦克风说话，确认文字后保存待办或灵感；每个账户独立管理自己的记录。',
    tags: ['语音输入', '登录可用', '个人记事'],
    priority: 96,
  },
  {
    id: 'x-mutual-cleaner',
    title: 'X 互关清理助手',
    href: '/resources/x-mutual-cleaner-extension',
    type: 'x-platform',
    status: 'live',
    summary: 'Chrome 扩展：在 X Following 页面扫描没有回关你的账号，由用户确认后批量取消关注。',
    tags: ['Chrome 扩展', 'X/Twitter', '本地运行'],
    priority: 100,
  },
  {
    id: 'x-tweet-to-pdf',
    title: 'X 推文转 PDF',
    href: '/resources/x-tweet-to-pdf-extension',
    type: 'x-platform',
    status: 'live',
    summary: 'Chrome / Edge 扩展：提取当前推文的正文、作者、图片和原文链接，整理成干净的 A4 PDF。',
    tags: ['Chrome 扩展', 'X/Twitter', 'PDF'],
    priority: 99,
  },
  {
    id: '2aran-desktop',
    title: '2aran 桌面应用',
    href: '/resources/2aran-desktop',
    type: 'extension',
    status: 'experiment',
    summary: 'Windows 与 macOS 桌面客户端下载入口，后续承接站内工具、资源领取和本地工作流。',
    tags: ['桌面应用', 'Windows', 'macOS'],
    priority: 98,
  },
  {
    id: 'short-link',
    title: '站内转短',
    href: '/tools/short-link',
    type: 'direct',
    status: 'live',
    summary: '把链接转换成 2aran.com 短链；站内分享自动转短，外部链接由站长手动维护。',
    tags: ['短链', '站长工具', 'D1'],
    priority: 95,
  },
  {
    id: 'web-llm',
    title: '端侧大模型实验台',
    href: '/web-llm',
    type: 'ai-dev',
    status: 'experiment',
    summary: '浏览器端运行大模型的实验页面，用来观察 WebGPU、端侧推理和前端 AI 运行时。',
    tags: ['WebGPU', 'Browser LLM', '端侧推理'],
    priority: 92,
  },
  {
    id: 'auto-commit',
    title: 'AutoCommit',
    href: '/tools/auto-commit',
    type: 'ai-dev',
    status: 'live',
    summary: '选择日期区间与强度，预览 GitHub 贡献图，并向指定仓库创建带历史时间戳的提交。',
    tags: ['GitHub', '贡献图', '开发工作流'],
    priority: 96,
  },
  {
    id: 'stock-analysis',
    title: '交易分析',
    href: '/stock-analysis',
    type: 'analysis',
    status: 'live',
    summary: '浏览多标的、分钟级交易快照，从资金费率、量价背离、均线乖离、关键点位与风险信号等维度辅助研判。',
    tags: ['交易快照', '风险研判', '分钟级'],
    priority: 96,
  },
  {
    id: 'public-opinion',
    title: '舆情分析',
    href: '/public-opinion',
    type: 'analysis',
    status: 'experiment',
    summary: '采集公开内容，聚合热点话题，并从情绪、立场与风险维度观察讨论趋势。',
    tags: ['舆情监测', '趋势研判', '公开信息'],
    priority: 94,
  },
  {
    id: 'syncblog',
    title: 'AI 分发大师',
    href: 'https://syncblog.cn',
    type: 'direct',
    status: 'external',
    summary: '一次创作，多平台同步分发，把重复发布流程交给 Agent。',
    tags: ['内容分发', 'Agent', '外部产品'],
    priority: 90,
  },
  {
    id: 'x-violation-check',
    title: 'X 近期违规自查',
    href: 'https://x.com/i/flow/join-birdwatch',
    type: 'x-platform',
    status: 'external',
    summary: '打开 X Community Notes 加入流程，查看账号近期是否有影响参与资格的违规提示。',
    tags: ['X/Twitter', '账号状态', '外部工具'],
    priority: 89,
  },
  {
    id: 'skill-center',
    title: 'Skill 中心',
    href: '/skill-center',
    type: 'ai-system',
    status: 'live',
    summary: '模型与智能体的可复用能力系统，收录创作、研发、研究与个人工作流。',
    tags: ['创作与分发', '研发与交付', '研究与分析'],
    priority: 88,
  },
  {
    id: 'mcp-center',
    title: 'MCP 中心',
    href: '/mcp-center',
    type: 'ai-system',
    status: 'live',
    summary: '面向智能体的连接服务系统，集中提供可复制配置与调用说明。',
    tags: ['文章查询', '天气查询', '本地加解密'],
    priority: 87,
  },
  {
    id: 'prompt-center',
    title: 'Prompt 中心',
    href: '/prompt-center',
    type: 'ai-system',
    status: 'live',
    summary: '面向智能体的提示词经验与任务模板，覆盖调研、研发、创作、抽取和质量验证。',
    tags: ['通用任务', '研究分析', '研发交付'],
    priority: 86,
  },
  {
    id: 'toolkit-hub',
    title: '代码矿工',
    href: 'https://toolkit-hub.pages.dev/',
    type: 'ai-dev',
    status: 'external',
    summary: '面向开发者的工具集合与能力聚合入口。',
    tags: ['开发工具', '工具集合', 'Pages'],
    priority: 84,
  },
  {
    id: 'prompt-engineering',
    title: '提示词工程',
    href: 'https://awesome-prompt-seven.vercel.app/',
    type: 'ai-dev',
    status: 'external',
    summary: '围绕提示词整理、沉淀与复用的轻量产品实验。',
    tags: ['Prompt', 'AI 工具', '复用'],
    priority: 82,
  },
  {
    id: 'wallpapers',
    title: '壁纸下载',
    href: '/resources/wallpapers',
    type: 'direct',
    status: 'live',
    summary: '站内可下载壁纸资源入口，适合沉淀为视觉资源工具。',
    tags: ['下载', '视觉资源'],
    priority: 70,
  },
  {
    id: 'ai-tools',
    title: 'AI 工具索引',
    href: '/bookmarks/ai-tools',
    type: 'index',
    status: 'index',
    summary: '实用 AI 工具、产品与服务推荐，作为工具库的外部工具索引。',
    tags: ['AI 工具', '产品推荐', '索引'],
    priority: 68,
  },
  {
    id: 'dev-resources',
    title: '开发资源索引',
    href: '/bookmarks/dev-resources',
    type: 'index',
    status: 'index',
    summary: '前端、后端、DevOps、Cloudflare 和 AI 工程相关的开发资源与工具链。',
    tags: ['开发资源', 'DevOps', 'Cloudflare'],
    priority: 66,
  },
]

export function getToolItemsByType(type) {
  return TOOL_ITEMS
    .filter((item) => item.type === type)
    .sort((a, b) => b.priority - a.priority)
}

export function getToolTypeMeta(type) {
  return TOOL_TYPE_META.find((item) => item.id === type) || null
}
