export const WORKBUDDY_SKILL_METADATA = {
  'install-codex-model-switcher': {
    displayNameEn: 'Install Codex Model Switcher',
    descriptionEn: 'Install and safely configure the Codex Model Switcher on macOS without bundling credentials.',
    category: 'engineering',
    readiness: 'ready',
    readinessLabel: '可上传测试',
    note: '包含通用 macOS App、配置脚本、模型目录与兼容性说明；不含任何 API Key。',
    bundledRelease: 'codex-model-switcher',
  },
  'reinstall-codex-dream-skin': {
    displayNameEn: 'Reinstall Codex Dream Skin',
    descriptionEn: 'Safely reinstall, apply, verify, or restore a local Codex Desktop theme from an image on macOS.',
    category: 'engineering',
    disableModelInvocation: true,
    readiness: 'ready',
    readinessLabel: '可上传测试',
    note: '包含执行脚本；实际重启 Codex 前仍要求用户明确授权。',
  },
  'ruanyifeng-weekly-style': {
    displayNameEn: 'Chinese Tech Weekly Style',
    descriptionEn: 'Draft original Chinese technology newsletters with concise explanations, numbered observations, and curated links.',
    category: 'writing',
    readiness: 'needs-review',
    readinessLabel: '需命名复核',
    note: '包内已保留原创与身份边界；市场展示名称建议避免造成官方授权误解。',
  },
  'llm-productivity-directives': {
    displayNameEn: 'LLM Productivity Directives',
    descriptionEn: 'Apply concise rules for writing, research, and coding without self-reference, excess structure, or invented facts.',
    category: 'productivity',
    readiness: 'ready',
    readinessLabel: '可上传',
    note: '纯 SKILL.md，无外部服务、脚本或凭据依赖。',
  },
  'tuaran-profile': {
    displayNameEn: 'Tuaran Profile',
    descriptionEn: 'Introduce Tuaran consistently at different levels of detail using a maintained personal profile.',
    category: 'personal',
    readiness: 'ready',
    readinessLabel: '可上传',
    note: '纯 SKILL.md；提交前复核公开个人资料是否仍然准确。',
  },
  'publisher-format-review': {
    displayNameEn: 'Publisher Format Review',
    descriptionEn: 'Review and rewrite Chinese book chapters against practical publishing and editorial formatting rules.',
    category: 'writing',
    readiness: 'ready',
    readinessLabel: '可上传',
    note: '纯 SKILL.md，无外部服务依赖。',
  },
  'rich-data-research-page': {
    displayNameEn: 'Rich Data Research Page',
    descriptionEn: 'Turn multidimensional public data into a comparable, filterable, and shareable research page.',
    category: 'research',
    readiness: 'ready',
    readinessLabel: '可上传',
    note: '纯 SKILL.md；实际建站时仍需遵循目标项目的技术约束。',
  },
  'renwei-writing': {
    displayNameEn: 'Human Voice Editing',
    descriptionEn: 'Polish the user’s own writing while preserving their voice, lived detail, uncertainty, and natural rhythm.',
    category: 'writing',
    author: 'Orange & Cola',
    readiness: 'needs-license',
    readinessLabel: '需授权确认',
    note: '已包含参考资料和原许可证；商业市场上架前应由原作者确认授权范围。',
  },
}

export const WORKBUDDY_CONNECTORS = [
  {
    id: 'tuaran-articles',
    nameZh: '涂阿燃文章连接器',
    nameEn: 'Tuaran Articles',
    descriptionZh: '查询 2aran.com 的公开文章、专题调研和资源，支持最近更新与关键词搜索。',
    descriptionEn: 'Search public articles, research topics, and resources published on 2aran.com.',
    endpoint: 'https://2aran.com/api/mcp/articles',
    examplesZh: ['查询涂阿燃最近更新的 AI Agent 文章', '搜索站内与 MCP 有关的调研'],
    examplesEn: ['Show the latest AI Agent articles from Tuaran', 'Search 2aran.com research about MCP'],
    tools: ['get_recent_articles', 'search_articles'],
    minWorkbuddyVersion: '4.24.0',
    readiness: 'needs-oauth-test',
    readinessLabel: '待 OAuth 联调',
    note: '包结构可上传；公开发布前需用 WorkBuddy 完成 OAuth 2.1 + PKCE 实测。',
  },
  {
    id: 'tuaran-weather-test',
    nameZh: '天气查询测试连接器',
    nameEn: 'Weather Test Connector',
    descriptionZh: '按中英文城市名查询当前天气和未来预报，用于验证 WorkBuddy 的 MCP 连接。',
    descriptionEn: 'Query current weather and forecasts by city name to verify a WorkBuddy MCP connection.',
    endpoint: 'https://2aran.com/api/mcp/weather',
    examplesZh: ['查询广州现在的天气', '查看上海未来三天的天气预报'],
    examplesEn: ['Check the current weather in Guangzhou', 'Show the three-day forecast for Shanghai'],
    tools: ['get_current_weather', 'get_weather_forecast'],
    minWorkbuddyVersion: '4.24.0',
    readiness: 'test-only',
    readinessLabel: '仅测试',
    note: '无需登录，适合解析与调用测试；市场正式上架价值需要另行评估。',
  },
  {
    id: 'tuaran-local-crypto-demo',
    nameZh: '本地加解密 MCP 测试连接器',
    nameEn: 'Local Crypto MCP Demo',
    descriptionZh: '在 WorkBuddy 拉起的本地 Node.js 进程中执行 AES-256-GCM 加解密与运行检查。',
    descriptionEn: 'Run AES-256-GCM encryption, decryption, and runtime checks in a local Node.js MCP process.',
    examplesZh: ['在本地加密这段文字', '检查本地 MCP 的运行环境'],
    examplesEn: ['Encrypt this text in the local process', 'Inspect the local MCP runtime'],
    tools: ['local_encrypt_text', 'local_decrypt_text', 'local_runtime_info'],
    minWorkbuddyVersion: '5.0.0',
    localServerPath: 'tools/mcp-stdio-demo/server.mjs',
    readiness: 'needs-install-test',
    readinessLabel: '待安装实测',
    note: '已移除维护者绝对路径并内置服务源码；上传后需确认 WorkBuddy 从包根目录启动 server.mjs。',
  },
]
