export const CHECKED_AT = '2026-07-15'

export const PROVIDERS = [
  {
    id: 'honghai-pro',
    name: '红海 Pro',
    latin: 'Honghai Pro',
    mark: '红',
    tone: 'coral',
    status: 'offline',
    statusLabel: '官网提示不可用',
    verdict: '暂缓购买',
    confidence: 92,
    transparency: 74,
    price: 9.9,
    priceLabel: '¥9.9 / 月',
    traffic: '100 GB / 月',
    bandwidth: '1000 Mbps（宣称）',
    protocol: '未公开',
    regions: ['香港', '日本', '美国', '德国'],
    clients: '手机与电脑（未列具体客户端）',
    payment: '未公开',
    trial: '未发现',
    highlight: '价格、流量与节点地区披露较完整，但当前状态比参数更重要。',
    caution: '官网明确写着“正遭受攻击，节点暂时全部无法使用”。页面同时导流其他服务，购买前应再次核对主体与恢复公告。',
    sources: [
      {
        label: '红海 Pro 官网',
        type: '官网',
        url: 'https://honghaipro.pro/',
        note: '套餐、节点地区，以及当前不可用提示。',
      },
    ],
  },
  {
    id: 'parallel-net',
    name: '平行网',
    latin: 'Parallel Network',
    mark: '平',
    tone: 'violet',
    status: 'unclear',
    statusLabel: '公开信息过少',
    verdict: '先索要资料',
    confidence: 38,
    transparency: 22,
    price: null,
    priceLabel: '未核验',
    traffic: '未核验',
    bandwidth: '未核验',
    protocol: '未核验',
    regions: [],
    clients: '未核验',
    payment: '未核验',
    trial: '未核验',
    highlight: '搜索可定位到名称与入口，但公开页几乎没有可用于决策的套餐和服务条款。',
    caution: '不应把“能打开官网”当成可靠性证明。购买前至少确认套餐截图、退款规则、工单入口和官方社群。',
    sources: [
      {
        label: '平行网公开入口',
        type: '官网入口',
        url: 'https://yumi.mom/',
        note: '当前公开抓取仅能确认“平行网”名称。',
      },
    ],
  },
  {
    id: 'maidong-cloud',
    name: '脉动云',
    latin: 'Maidong Cloud',
    mark: '脉',
    tone: 'cyan',
    status: 'verify',
    statusLabel: '入口可核验',
    verdict: '小额月付试用',
    confidence: 61,
    transparency: 48,
    price: 9,
    priceLabel: '¥9 / 月（第三方）',
    traffic: '100 GB / 月（第三方）',
    bandwidth: '1000 Mbps（第三方宣称）',
    protocol: '未在公开入口披露',
    regions: [],
    clients: '未核验',
    payment: '未核验',
    trial: '未核验',
    highlight: '官方导航页提供国内、全球和通用入口；公开第三方资料给出低价入门套餐。',
    caution: '价格、带宽、BGP 中继与流媒体解锁均来自第三方页面，不应视作当前官方承诺。',
    sources: [
      {
        label: '脉动云导航页',
        type: '官方导航',
        url: 'https://maidongyun.com/',
        note: '列出国内、全球和通用入口。',
      },
      {
        label: '第三方机场列表',
        type: '第三方',
        url: 'https://www.clashfeiji.com/sanmaojichangapp',
        note: '给出 ¥9 / 100GB、1000M、BGP 中继等描述。',
      },
    ],
  },
  {
    id: 'huoshaoyun',
    name: '火烧云',
    latin: 'Huoshaoyun',
    mark: '火',
    tone: 'amber',
    status: 'verify',
    statusLabel: '同名站点较多',
    verdict: '只认固定入口',
    confidence: 68,
    transparency: 56,
    price: 18,
    priceLabel: '¥18 / 月（第三方）',
    traffic: '100 GB / 月（第三方）',
    bandwidth: '300 Mbps（第三方宣称）',
    protocol: 'Shadowsocks / SS2022（第三方）',
    regions: ['香港', '日本', '台湾', '新加坡', '美国'],
    clients: 'Windows / macOS / Android（第三方）',
    payment: '支付宝 / 微信（第三方）',
    trial: '2 小时 / 2 GB（第三方）',
    highlight: '公开第三方资料相对丰富，能拼出入门套餐、协议、节点地区与试用信息。',
    caution: '搜索结果中存在大量同名、SEO 聚合或相互冲突页面。先从固定发布地址进入，不要直接相信搜索广告。',
    sources: [
      {
        label: '火烧云公开站',
        type: '官网候选',
        url: 'https://huoshaoyun.org/',
        note: '可访问但抓取不到套餐正文。',
      },
      {
        label: '挂梯子条目',
        type: '第三方',
        url: 'https://guatizi.com/sites/1103.html',
        note: '试用、协议、节点地区、支付与客户端信息。',
      },
      {
        label: 'XuLaLa 套餐整理',
        type: '第三方',
        url: 'https://xu.dbsqp.com/a/page_b2302897342',
        note: '¥18 / 100GB / 300Mbps 等套餐口径。',
      },
    ],
  },
  {
    id: 'sakana-cloud',
    name: '鱼云',
    latin: 'SakanaCloud',
    mark: '鱼',
    tone: 'blue',
    status: 'watch',
    statusLabel: '仍有运营信号',
    verdict: '月付观察',
    confidence: 82,
    transparency: 66,
    price: null,
    priceLabel: '以面板实时价格为准',
    traffic: '未在公开页披露',
    bandwidth: '未在公开页披露',
    protocol: 'VLESS / XHTTP（公开资料）',
    regions: ['香港', '日本', '台湾', '新加坡', '美国'],
    clients: 'Mihomo / FlClash 等（频道信息）',
    payment: '支付宝 / 微信 / USDT（第三方）',
    trial: '未核验',
    highlight: '永久发布页、多个入口和社区更新仍可找到，协议与客户端更新信号相对近期。',
    caution: '公开记录曾提及订单与注册数据意外丢失。价格近期也有调整信号，建议保留支付凭证并坚持月付。',
    sources: [
      {
        label: 'SakanaCloud 永久发布页',
        type: '官方发布页',
        url: 'https://sakana.homes/',
        note: '列出优化、国际与备用入口。',
      },
      {
        label: '挂梯子条目',
        type: '第三方',
        url: 'https://guatizi.com/sites/3751.html',
        note: '运营时间、VLESS、节点地区与支付方式。',
      },
      {
        label: '频道公开镜像',
        type: '社区信号',
        url: 'https://telemetr.io/en/channels/1908951461-sakanacloud/posts',
        note: '近期协议更新与历史运营事故记录。',
      },
    ],
  },
]

export const STATUS_META = {
  all: { label: '全部 5 家' },
  actionable: { label: '可继续核验', ids: ['maidong-cloud', 'huoshaoyun', 'sakana-cloud'] },
  caution: { label: '暂缓 / 信息不足', ids: ['honghai-pro', 'parallel-net'] },
}

export const BUYING_CHECKLIST = [
  ['先月付', '未知稳定性阶段不买年付；一次性流量包也要确认有效期和退款条件。'],
  ['做晚高峰实测', '分别在工作日 20:00–23:00 测延迟、丢包、视频拖动和常用站点。'],
  ['核对入口', '从固定发布页或已确认社群进入，避免搜索广告、同名站和私聊收款。'],
  ['保留证据', '保存套餐页面、服务条款、订单号和支付凭证，重要账号不要共用密码。'],
  ['准备备用', '任何单一服务都可能临时故障；工作刚需至少准备一条不同供应方的备用链路。'],
  ['遵守当地规则', '网络工具的使用边界因地区而异；企业数据与敏感账号优先走合规专线和正式安全方案。'],
]
