export const STAGES = [
  {
    id: 'ready',
    min: 18,
    max: 23,
    shortAge: '1岁半–2岁',
    title: '亲耳朵 · 准备期',
    color: '#e66b45',
    summary: '先建立“英语也能一起玩”的感觉，不追着孩子开口。',
    goal: '能把熟悉的声音、动作和物品联系起来；听到固定短句会看、指、做动作。',
    focus: ['真实互动', '动作儿歌', '物品命名', '固定生活短句'],
    avoid: ['单独看屏幕', '抽认卡考问', '纠正发音', '长时间背景音'],
    minutes: '10–15 分钟，拆成 2–3 次',
    signals: ['听到 “Where is…?” 会找一找', '熟悉儿歌前奏响起会做动作', '能用看、指、拿回应一两个指令'],
  },
  {
    id: 'listen',
    min: 24,
    max: 35,
    shortAge: '2–3岁',
    title: '听懂 · 动作期',
    color: '#d19a2a',
    summary: '让英语和身体动作、日常流程一一对应。',
    goal: '听懂高频生活短句，愿意用动作、声音或单词参与。',
    focus: ['TPR 全身反应', '重复绘本', '短儿歌', '两步生活流程'],
    avoid: ['字母书写', '翻译每句话', '频繁换资源', '被动连播'],
    minutes: '15–20 分钟，拆成 2–3 次',
    signals: ['能执行 sit down / wash hands 等熟悉指令', '会补儿歌最后一个词或声音', '主动说出少量高频词或拟声词'],
  },
  {
    id: 'speak',
    min: 36,
    max: 47,
    shortAge: '3–4岁',
    title: '敢说 · 组合期',
    color: '#4d8e7b',
    summary: '从跟唱和单词，走向有目的的短语表达。',
    goal: '在熟悉情境里使用 2–4 词短语，能参与简单轮流问答。',
    focus: ['角色扮演', '预测故事', '选择式提问', '生活短语'],
    avoid: ['背孤立词表', '当众测试', '只看不聊', '追求口音'],
    minutes: '20–25 分钟，可拆分',
    signals: ['能说 I want… / More… 等有用途的短语', '能回答二选一问题', '会用熟悉句型替换一个词'],
  },
  {
    id: 'story',
    min: 48,
    max: 60,
    shortAge: '4–5岁',
    title: '会用 · 故事期',
    color: '#5976b5',
    summary: '用英语完成游戏、复述和简单任务。',
    goal: '理解短故事主线，能描述画面、表达选择并合作完成任务。',
    focus: ['故事复述', '主题项目', '自然拼读意识', '同伴互动'],
    avoid: ['提前刷题', '语法术语', '机械抄写', '忽视母语发展'],
    minutes: '25–35 分钟，可拆分',
    signals: ['能按先后说出两三个情节', '能提出或回答简单 what / where 问题', '开始留意首音、押韵和字母声音'],
  },
]

export const TODAY_PLAN = [
  {
    id: 'song',
    minutes: 4,
    title: '动作儿歌',
    instruction: '唱一首熟歌，只加 2 个动作：clap / stomp。孩子只做动作也算完成。',
    line: 'Clap, clap, clap. Stomp, stomp, stomp.',
  },
  {
    id: 'look',
    minutes: 4,
    title: '看图找物',
    instruction: '拿一本熟悉绘本，指 3 个孩子感兴趣的东西，停下来等回应。',
    line: 'Where is the dog? There it is!',
  },
  {
    id: 'life',
    minutes: 4,
    title: '生活短句',
    instruction: '洗手或收玩具时只重复同一组短句，不要求跟读。',
    line: 'Wash hands. Rub, rub, rub. All clean!',
  },
]

export const WEEK_PLAN = [
  { id: 'mon', day: '周一', theme: '身体', action: 'Head, shoulders + 指身体部位' },
  { id: 'tue', day: '周二', theme: '动物', action: '找动物 + 模仿叫声和动作' },
  { id: 'wed', day: '周三', theme: '洗手', action: '把 wash / rub / clean 放进流程' },
  { id: 'thu', day: '周四', theme: '绘本', action: '同一本书再读一遍，让孩子翻页' },
  { id: 'fri', day: '周五', theme: '收玩具', action: '用 in / out / one more 边玩边说' },
  { id: 'sat', day: '周六', theme: '共看', action: '选 1 段 3–7 分钟内容，共看后立刻模仿' },
  { id: 'sun', day: '周日', theme: '自由复现', action: '只玩孩子本周最喜欢的一项' },
]

export const SHOWS = [
  {
    id: 'super-simple',
    name: 'Super Simple Songs',
    age: '18个月–4岁',
    stages: ['ready', 'listen', 'speak'],
    accent: '多为美式英语',
    pace: '慢',
    unit: '2–4 分钟/首',
    best: '动作、韵律、高频词与固定句型',
    why: '由日本英语教师为学龄前 ESL 学习者制作，刻意放慢并简化儿歌。',
    how: '先听同一首 3–5 天；关屏后继续唱和做动作。',
    link: 'https://supersimple.com/super-simple-songs/',
  },
  {
    id: 'pocoyo',
    name: 'Pocoyo 英文版',
    age: '2–4岁',
    stages: ['listen', 'speak'],
    accent: '英式英语旁白',
    pace: '慢',
    unit: '约 7 分钟/集',
    best: '旁白清楚、画面干净、动作语义明显',
    why: 'Cambridge English 与 Pocoyo 另有面向 2–6 岁的英语活动视频。',
    how: '先选孩子熟悉的主题；暂停让孩子指一指，再模仿一个动作。',
    link: 'https://www.cambridgeenglish.org/learning-english/parents-and-children/activities-for-children/pocoyo/',
  },
  {
    id: 'hey-duggee',
    name: 'Hey Duggee',
    age: '2岁半–5岁',
    stages: ['listen', 'speak', 'story'],
    accent: '英式英语',
    pace: '中等',
    unit: '约 7 分钟/集',
    best: '活动主题、重复结构、社交与行动词汇',
    why: '每集围绕一项活动展开，适合把剧情变成现实里的小游戏。',
    how: '3 岁前只挑动作直观的集数；看完做一次相同主题的小任务。',
    link: 'https://www.bbc.co.uk/cbeebies/shows/hey-duggee',
  },
  {
    id: 'peppa',
    name: 'Peppa Pig',
    age: '3–5岁',
    stages: ['speak', 'story'],
    accent: '英式英语',
    pace: '中等',
    unit: '约 5 分钟/集',
    best: '家庭生活、完整对话、常见情境',
    why: '单集短、日常情境多，但句子密度明显高于儿歌和 Pocoyo。',
    how: '先用中文聊懂情节也没关系；第二次只抓 1 句能在生活中复用的话。',
    link: 'https://www.peppapig.com/',
  },
  {
    id: 'daniel',
    name: "Daniel Tiger's Neighborhood",
    age: '3–5岁',
    stages: ['speak', 'story'],
    accent: '美式英语',
    pace: '中等',
    unit: '11 分钟/段',
    best: '情绪表达、社交语言、策略儿歌',
    why: 'PBS 为 2–4 岁学龄前儿童设计，以社交情绪课程和可复用儿歌为核心。',
    how: '截取一个策略儿歌即可；遇到同类生活情境时再唱出来。',
    link: 'https://www.pbs.org/parents/shows/daniel/about',
  },
  {
    id: 'bluey',
    name: 'Bluey',
    age: '4–5岁起',
    stages: ['story'],
    accent: '澳式英语',
    pace: '偏快',
    unit: '约 7 分钟/集',
    best: '想象游戏、家庭对话、叙事理解',
    why: '语言自然、文化和语用丰富，适合已有听力基础后亲子共看。',
    how: '不作为零基础启蒙首选；先看动作线清楚的集数，再复刻一个游戏。',
    link: 'https://www.bluey.tv/',
  },
]

export const METHODS = [
  {
    id: 'serve-return',
    label: '互动优先',
    title: '回应孩子，再多说半步',
    detail: '孩子看、指、发声都算“发球”。大人先回应其注意点，再补一个词或短句，留出等待时间。',
    example: '孩子指车 → “Car. A red car. Beep beep!” → 等孩子回应。',
    source: '哈佛大学儿童发展中心：Serve and Return',
  },
  {
    id: 'comprehensible',
    label: '可理解输入',
    title: '让语言能被动作、物品和情境猜到',
    detail: '低龄儿童不需要逐句翻译。真实物品、手势、表情、重复流程，会把声音和意义连起来。',
    example: '穿鞋时说 “Shoes on”，同时拿鞋、穿鞋；每天用同一句。',
    source: 'British Council：在家教儿童英语',
  },
  {
    id: 'repeat-transfer',
    label: '重复与迁移',
    title: '同一素材多次用，再搬进生活',
    detail: '一周围绕少量歌、书和短句反复体验。熟悉之后暂停，让孩子补动作、声音或最后一个词。',
    example: '儿歌学了 “up / down”，抱玩偶、坐电梯、收玩具时继续用。',
    source: 'British Council：故事、儿歌与韵律建议',
  },
  {
    id: 'home-language',
    label: '母语打底',
    title: '不削弱家庭最自然的语言',
    detail: '家长用最能表达情感和复杂意思的语言持续交流。多语输入不会把孩子“搞混”，质量和使用机会更重要。',
    example: '中文把故事和情绪聊透，英语承担固定游戏和生活短句。',
    source: 'ASHA：Learning More Than One Language',
  },
]

export const SOURCES = [
  {
    name: '世界卫生组织：5 岁以下儿童活动、久坐与睡眠指南',
    note: '2 岁及 3–4 岁儿童的久坐屏幕时间建议每天不超过 1 小时，越少越好。',
    url: 'https://www.who.int/news/item/24-04-2019-to-grow-up-healthy-children-need-to-sit-less-and-play-more',
  },
  {
    name: '美国儿科学会：Media and Young Minds',
    note: '18–24 个月若引入媒体，应选择高质量内容并由家长共看；2–5 岁建议不超过每天 1 小时。',
    url: 'https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds',
  },
  {
    name: '哈佛大学儿童发展中心：Serve and Return',
    note: '回应式、来回互动支持早期语言与社会能力发展。',
    url: 'https://developingchild.harvard.edu/key-concept/serve-and-return/',
  },
  {
    name: 'ASHA：Learning More Than One Language',
    note: '孩子可以学习多种语言；交谈、唱歌、游戏和共读都能提供有质量的练习。',
    url: 'https://www.asha.org/public/speech/development/learning-more-than-one-language/',
  },
  {
    name: 'British Council：How to start teaching kids English at home',
    note: '建议建立固定英语时间，用日常情境、绘本和动作儿歌开展短而规律的活动。',
    url: 'https://learnenglishkids.britishcouncil.org/parents/helping-your-child/how-start-teaching-kids-english-home',
  },
  {
    name: '教育部：《3–6 岁儿童学习与发展指南》',
    note: '强调尊重发展规律、游戏和生活价值，并明确反对提前学习小学教育内容。',
    url: 'https://www.moe.gov.cn/srcsite/A06/s3327/201210/t20121009_143254.html',
  },
]

export function stageForMonths(months) {
  return STAGES.find((stage) => months >= stage.min && months <= stage.max) || STAGES[STAGES.length - 1]
}
