export const RESEARCH_ENTRY_KEYS = [
  'companies/51cto',
  'companies/china-mobile-internet',
  'companies/eve-energy',
  'companies/infoq',
  'companies/jixinghui',
  'companies/montnets',
  'companies/weixin-zhiyun',
  'companies/csdn',
  'companies/juejin',
  'companies/matrixlink-blogger-alliance',
  'companies/rollcode',
  'companies/xiaohongshu',
  'companies/zhihu',
  'topics/china-dishwasher-under-2k',
  'topics/qwen3-5-edge-deployment',
  'topics/rank-comparison-soe-civil-ming',
  'topics/dify-docx-image-handling',
  'topics/iseecmic',
  'topics/6g-network-frontier-technologies',
  'topics/multi-platform-account-posting-pricing',
  'topics/qwen3-6-qwen3-7-ecosystem',
  'topics/codex-project-status-management',
  'topics/cross-origin-window-messaging',
  'topics/dark-humor-memes-after-celebrity-deaths',
  'topics/fan-economy-definition',
  'topics/malaysia-data-center-etcon26',
]

export const RESEARCH_ENTRY_KEY_SET = new Set(RESEARCH_ENTRY_KEYS)
