// Generated by scripts/audit-research-style.mjs. Do not edit by hand.
export const RESEARCH_STYLE_AUDIT = {
  "generatedAt": "2026-07-14T04:08:12.971Z",
  "scannedFiles": 140,
  "fixCount": 482,
  "reviewCount": 19,
  "rules": [
    {
      "id": "one-sentence-takeaway",
      "phrase": "如果只记住一句话",
      "why": "AI 味极重的收尾套话；要收敛结论就直接写「先给结论」+ 一句加粗陈述。",
      "matcher": "如果只记住一句话",
      "severity": "fix",
      "occurrences": 0,
      "files": []
    },
    {
      "id": "false-contrast",
      "phrase": "不是 X，而是 Y",
      "why": "内容创作铁律：站内作者正文禁用这一句式。直接陈述 Y，或拆成两句具体事实。",
      "matcher": "不是[^。；，、：:！!？?\\n]{1,24}[，,]?\\s*而是",
      "severity": "fix",
      "occurrences": 429,
      "files": [
        "research/companies/2026-06-11-captainbed.md",
        "research/companies/2026-06-29-shangqiao-logistics.md",
        "research/companies/2026-07-06-v2ex.md"
      ]
    },
    {
      "id": "forced-elevation",
      "phrase": "不仅仅是 X，更是 Y",
      "why": "强行拔高普通事实，宣传腔。直接说 Y。",
      "matcher": "不仅仅是[^。；，、：:！!？?\\n]{1,24}更是",
      "severity": "fix",
      "occurrences": 0,
      "files": []
    },
    {
      "id": "empty-transition",
      "phrase": "值得关注 / 注意 / 一提的是",
      "why": "空转过渡句，什么信息都没给。直接说那件事。",
      "matcher": "值得(?:关注|注意|一提)",
      "severity": "fix",
      "occurrences": 27,
      "files": [
        "research/companies/2026-05-16-51cto.md",
        "research/companies/2026-05-16-china-mobile-internet.md",
        "research/companies/2026-05-16-eve-energy.md"
      ]
    },
    {
      "id": "vague-qualifier",
      "phrase": "某种程度上 / 某种意义上",
      "why": "模糊限定词，用来回避把话说准。要么给具体程度，要么删。",
      "matcher": "某种(?:程度|意义)上",
      "severity": "fix",
      "occurrences": 1,
      "files": [
        "research/topics/2026-06-08-codex-localization-deepseek-gui.md"
      ]
    },
    {
      "id": "grand-conclusion",
      "phrase": "本质上 / 从本质上讲 / 归根结底 / 说到底",
      "why": "把观察包装成终极判决的拔高腔。直接陈述。",
      "matcher": "(?:从)?本质上(?:讲)?|归根结底|说到底",
      "severity": "fix",
      "occurrences": 18,
      "files": [
        "research/companies/2026-05-16-montnets.md",
        "research/topics/2026-05-22-6g-network-frontier-technologies.md",
        "research/topics/2026-05-27-llm-self-reference.md"
      ]
    },
    {
      "id": "cheap-emphasis",
      "phrase": "更重要的是 / 值得强调的是",
      "why": "廉价递进，用来制造重点感。让内容自己承担重点。",
      "matcher": "(?:更重要|值得强调)的是",
      "severity": "fix",
      "occurrences": 4,
      "files": [
        "research/topics/2026-05-26-middleware-architecture-research.md",
        "research/topics/2026-05-30-blogger-alliance-growth-promotion.md",
        "research/topics/2026-06-05-local-agent-ops-launchd-cloudflare-tunnel.md"
      ]
    },
    {
      "id": "closing-filler",
      "phrase": "综上所述 / 总而言之 / 总的来说 / 一言以蔽之",
      "why": "收尾套话。用具体结论收束，不用套壳。",
      "matcher": "综上所述|总而言之|总的来说|一言以蔽之",
      "severity": "fix",
      "occurrences": 2,
      "files": [
        "research/topics/2026-05-27-llm-self-reference.md"
      ]
    },
    {
      "id": "rephrase-filler",
      "phrase": "换言之 / 换句话说",
      "why": "八成是把上一句换皮重说一遍。删掉重复，或只留一种说法。",
      "matcher": "换言之|换句话说",
      "severity": "review",
      "occurrences": 10,
      "files": [
        "research/topics/2026-05-26-bytedance-feilian-agent-interview.md",
        "research/topics/2026-05-28-china-general-agents.md",
        "research/topics/2026-06-02-local-always-on-llm-nvidia-spark.md"
      ]
    },
    {
      "id": "lazy-assertion",
      "phrase": "众所周知 / 显而易见 / 不难看出",
      "why": "偷懒断言，跳过论证；对读者也不礼貌。",
      "matcher": "众所周知|显而易见|不难看出",
      "severity": "fix",
      "occurrences": 0,
      "files": []
    },
    {
      "id": "marketing-jargon",
      "phrase": "赋能 / 打造 / 重塑 / 未来可期",
      "why": "宣传腔，读者立刻出戏。",
      "matcher": "赋能|打造|重塑|未来可期",
      "severity": "review",
      "occurrences": 9,
      "files": [
        "research/companies/2026-05-16-infoq.md",
        "research/companies/2026-05-16-montnets.md",
        "research/companies/2026-05-16-weixin-zhiyun.md"
      ]
    },
    {
      "id": "empty-context",
      "phrase": "在……的时代 / 背景 / 浪潮下",
      "why": "空泛背景句，没有具体的人和事。",
      "matcher": "在[^。；，、：:！!？?\\n]{1,24}(?:时代|背景|浪潮)下",
      "severity": "fix",
      "occurrences": 1,
      "files": [
        "research/topics/2026-06-28-eating-for-fat-loss-muscle-gain.md"
      ]
    },
    {
      "id": "ritual-scope-label",
      "phrase": "调研口径 / 核验口径 / 本调研定位",
      "why": "模板化的声明会放大批量调研感。把资料日期、适用范围和限制直接写成自然段。",
      "matcher": "调研口径|核验口径|本调研定位",
      "severity": "fix",
      "occurrences": 0,
      "files": []
    }
  ]
}
