// Generated by scripts/audit-research-style.mjs. Do not edit by hand.
export const RESEARCH_STYLE_AUDIT = {
  "generatedAt": "2026-09-01T11:09:13.159Z",
  "scannedFiles": 228,
  "fixCount": 47,
  "reviewCount": 17,
  "rules": [
    {
      "id": "one-sentence-takeaway",
      "phrase": "如果只记住一句话",
      "why": "AI 味极重的收尾套话；要收敛结论就直接写「先给结论」+ 一句加粗陈述。",
      "matcher": "如果只记住一句话",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "false-contrast",
      "phrase": "不是 X，而是 Y",
      "why": "内容创作铁律：站内作者正文禁用这一句式。直接陈述 Y，或拆成两句具体事实。",
      "matcher": "不是[^。；，、：:！!？?\\n]{1,24}[，,]?\\s*而是",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 44,
      "protectedReasons": {
        "source": 5,
        "quote": 15,
        "safety": 19,
        "subject-matter": 5
      }
    },
    {
      "id": "empty-self-reference",
      "phrase": "本文 / 本篇 / 下面 / 接下来",
      "why": "没有实际范围或导航作用的自我指涉会让正文像生成模板。直接陈述；引用原文、安全边界、必要范围和真实界面导航保留。",
      "matcher": "本文|本篇|本调研|(?<!文)本页|下面(?!试)|接下来",
      "severity": "fix",
      "occurrences": 1,
      "files": [
        "research/topics/2026-08-03-commission-pay-vs-revenue-share-cooperation.md"
      ],
      "protectedOccurrences": 252,
      "protectedReasons": {
        "quote": 55,
        "scope": 100,
        "safety": 23,
        "source": 38,
        "navigation": 11,
        "subject-matter": 20,
        "semantic": 4,
        "temporal": 1
      }
    },
    {
      "id": "model-self-reference",
      "phrase": "模型口吻与写作过程说明",
      "why": "公开正文应呈现作者判断、证据和适用边界，不用模型身份或生成过程代替内容本身。",
      "matcher": "本文(?:将|会|首先|主要|旨在)|本调研(?:将|会|主要|旨在)|写作说明|我作为[^。\\n]{0,24}(?:AI|大模型|语言模型|Claude|GPT)|由[^。\\n]{0,30}(?:AI|大模型|Claude|GPT)[^。\\n]{0,30}(?:生成|撰写|协助下成文)",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 5,
      "protectedReasons": {
        "subject-matter": 5
      }
    },
    {
      "id": "forced-elevation",
      "phrase": "不仅仅是 X，更是 Y",
      "why": "强行拔高普通事实，宣传腔。直接说 Y。",
      "matcher": "不仅仅是[^。；，、：:！!？?\\n]{1,24}更是",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "empty-transition",
      "phrase": "值得关注 / 注意 / 一提的是",
      "why": "空转过渡句，什么信息都没给。直接说那件事。",
      "matcher": "值得(?:关注|注意|一提)",
      "severity": "fix",
      "occurrences": 23,
      "files": [
        "research/companies/2026-05-16-51cto.md",
        "research/companies/2026-05-16-china-mobile-internet.md",
        "research/companies/2026-05-16-eve-energy.md"
      ],
      "protectedOccurrences": 5,
      "protectedReasons": {
        "quote": 2,
        "safety": 3
      }
    },
    {
      "id": "vague-qualifier",
      "phrase": "某种程度上 / 某种意义上",
      "why": "模糊限定词，用来回避把话说准。要么给具体程度，要么删。",
      "matcher": "某种(?:程度|意义)上",
      "severity": "fix",
      "occurrences": 1,
      "files": [
        "research/topics/2026-06-08-codex-localization-deepseek-gui.md"
      ],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "grand-conclusion",
      "phrase": "本质上 / 从本质上讲 / 归根结底 / 说到底",
      "why": "把观察包装成终极判决的拔高腔。直接陈述。",
      "matcher": "(?:从)?本质上(?:讲)?|归根结底|说到底",
      "severity": "fix",
      "occurrences": 15,
      "files": [
        "research/topics/2026-05-22-6g-network-frontier-technologies.md",
        "research/topics/2026-05-27-llm-self-reference.md",
        "research/topics/2026-06-01-15-minutes-understand-large-language-models.md"
      ],
      "protectedOccurrences": 1,
      "protectedReasons": {
        "quote": 1
      }
    },
    {
      "id": "cheap-emphasis",
      "phrase": "更重要的是 / 值得强调的是",
      "why": "廉价递进，用来制造重点感。让内容自己承担重点。",
      "matcher": "(?:更重要|值得强调)的是",
      "severity": "fix",
      "occurrences": 4,
      "files": [
        "research/topics/2026-05-26-middleware-architecture-research.md",
        "research/topics/2026-05-30-blogger-alliance-growth-promotion.md",
        "research/topics/2026-06-05-local-agent-ops-launchd-cloudflare-tunnel.md"
      ],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "closing-filler",
      "phrase": "综上所述 / 总而言之 / 总的来说 / 一言以蔽之",
      "why": "收尾套话。用具体结论收束，不用套壳。",
      "matcher": "综上所述|总而言之|总的来说|一言以蔽之",
      "severity": "fix",
      "occurrences": 2,
      "files": [
        "research/topics/2026-05-27-llm-self-reference.md"
      ],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "rephrase-filler",
      "phrase": "换言之 / 换句话说",
      "why": "八成是把上一句换皮重说一遍。删掉重复，或只留一种说法。",
      "matcher": "换言之|换句话说",
      "severity": "review",
      "occurrences": 9,
      "files": [
        "research/topics/2026-05-26-bytedance-feilian-agent-interview.md",
        "research/topics/2026-05-28-china-general-agents.md",
        "research/topics/2026-06-02-local-always-on-llm-nvidia-spark.md"
      ],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "lazy-assertion",
      "phrase": "众所周知 / 显而易见 / 不难看出",
      "why": "偷懒断言，跳过论证；对读者也不礼貌。",
      "matcher": "众所周知|显而易见|不难看出",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    },
    {
      "id": "marketing-jargon",
      "phrase": "赋能 / 打造 / 重塑 / 未来可期",
      "why": "宣传腔，读者立刻出戏。",
      "matcher": "赋能|打造|重塑|未来可期",
      "severity": "review",
      "occurrences": 8,
      "files": [
        "research/companies/2026-05-16-infoq.md",
        "research/companies/2026-05-16-montnets.md",
        "research/companies/2026-05-16-weixin-zhiyun.md"
      ],
      "protectedOccurrences": 2,
      "protectedReasons": {
        "source": 2
      }
    },
    {
      "id": "empty-context",
      "phrase": "在……的时代 / 背景 / 浪潮下",
      "why": "空泛背景句，没有具体的人和事。",
      "matcher": "在[^。；，、：:！!？?\\n]{1,24}(?:时代|背景|浪潮)下",
      "severity": "fix",
      "occurrences": 1,
      "files": [
        "research/companies/2026-08-09-a-share-000990.md"
      ],
      "protectedOccurrences": 1,
      "protectedReasons": {
        "quote": 1
      }
    },
    {
      "id": "ritual-scope-label",
      "phrase": "调研口径 / 核验口径 / 本调研定位",
      "why": "模板化的声明会放大批量调研感。把资料日期、适用范围和限制直接写成自然段。",
      "matcher": "调研口径|核验口径|本调研定位",
      "severity": "fix",
      "occurrences": 0,
      "files": [],
      "protectedOccurrences": 0,
      "protectedReasons": {}
    }
  ],
  "contentOpeningAudit": {
    "scannedFiles": 236,
    "openingSourceDeclarations": [],
    "duplicatedOpeningAndEndingSources": [],
    "safetyExceptions": [
      "research/topics/2026-06-19-father-parenting-18-month-toddler-evidence-based.md",
      "research/topics/2026-06-19-husband-toddler-meltdown-spouse-stress.md",
      "research/topics/2026-06-22-guest-identity-and-points-system.md",
      "research/topics/2026-06-22-personal-portal-traffic-monetization-threshold.md",
      "research/topics/2026-06-26-shen-zhi-dou-nei-bytedance-workplace-observation.md",
      "research/topics/2026-06-26-white-house-openai-gpt5-6-slow-roll.md",
      "research/topics/2026-06-28-china-mobile-token-office-ai-restructuring.md",
      "research/topics/2026-06-28-eating-for-fat-loss-muscle-gain.md",
      "research/topics/2026-07-04-jadepuffer-agentic-ransomware.md",
      "research/topics/2026-07-07-xiaohongshu-vie-option-labor-compensation-ipo-risk.md",
      "research/topics/2026-07-08-a-share-us-stock-h1-returns-positioning.md",
      "research/topics/2026-07-12-china-toddler-probiotics-prebiotics-synbiotics-postbiotics.md",
      "research/people/2026-07-16-jia-qianqian.md",
      "content/resources/shen-zhi-mi-nei.md"
    ]
  }
}
