#!/usr/bin/env node
// 把一份本地 markdown 加密后写入 shared_notes 表，作为可重复访问的分享链接。
//
// 用法：
//   node scripts/seed-share.mjs <markdown文件> <密码> [标题] [--slug=自定义slug] [--out=输出sql文件]
//
// 默认：
//   markdown 文件：private/family/2606-durian.md
//   密码：123123
//   标题：2606 榴莲事件
//   slug：随机 10 位
//   输出：private/seed-share.sql（gitignored，跑完即可删）
//
// 加密原语复用 lib/longCompass/crypto.js（与浏览器解锁参数完全一致）。
//
// 跑完后用 wrangler 应用：
//   npx wrangler d1 execute tuaran-me --remote --file=private/seed-share.sql
// 之后访问：
//   https://2aran.com/share/<slug>#<密码>

import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

import { encryptPayload } from '../lib/longCompass/crypto.js'

const ROOT = path.resolve(process.cwd())

function parseArgs(argv) {
  const positional = []
  const flags = {}
  for (const arg of argv) {
    if (arg.startsWith('--')) {
      const eq = arg.indexOf('=')
      if (eq > -1) flags[arg.slice(2, eq)] = arg.slice(eq + 1)
      else flags[arg.slice(2)] = true
    } else {
      positional.push(arg)
    }
  }
  return { positional, flags }
}

const SLUG_ALPHABET = 'abcdefghijkmnpqrstuvwxyz23456789'
function generateSlug(length = 10) {
  const bytes = new Uint8Array(length)
  globalThis.crypto.getRandomValues(bytes)
  let out = ''
  for (let i = 0; i < length; i += 1) {
    out += SLUG_ALPHABET[bytes[i] % SLUG_ALPHABET.length]
  }
  return out
}

function sqlString(value) {
  if (value === null || value === undefined) return 'NULL'
  return `'${String(value).replace(/'/g, "''")}'`
}

async function main() {
  const { positional, flags } = parseArgs(process.argv.slice(2))
  const filePath = positional[0] || 'private/family/2606-durian.md'
  const password = positional[1] || '123123'
  const title = positional[2] || '2606 榴莲事件'
  const slug = flags.slug || generateSlug()
  const outPath = flags.out || 'private/seed-share.sql'

  const absPath = path.resolve(ROOT, filePath)
  if (!fs.existsSync(absPath)) {
    console.error(`[seed-share] file not found: ${absPath}`)
    process.exit(1)
  }
  if (typeof password !== 'string' || password.length < 6) {
    console.error('[seed-share] password must be at least 6 characters')
    process.exit(1)
  }

  const content = fs.readFileSync(absPath, 'utf8')
  console.log(`[seed-share] file: ${filePath} (${content.length} chars)`)
  console.log(`[seed-share] title: ${title}`)
  console.log(`[seed-share] slug: ${slug}`)
  console.log('[seed-share] password: (hidden)')

  const envelope = await encryptPayload({ content }, password)
  const envelopeJson = JSON.stringify(envelope)
  const now = Date.now()

  // 用 UPSERT 写入：同一 slug 重复跑会覆盖（方便迭代正文 / 改密码后再 seed）
  const sql = [
    `-- generated by scripts/seed-share.mjs at ${new Date(now).toISOString()}`,
    `-- file: ${filePath}`,
    `-- slug: ${slug}`,
    `INSERT INTO shared_notes (slug, title, envelope, created_at, updated_at, expires_at, view_count, last_viewed_at, created_by)`,
    `VALUES (${sqlString(slug)}, ${sqlString(title)}, ${sqlString(envelopeJson)}, ${now}, ${now}, NULL, 0, NULL, 'seed-share.mjs')`,
    `ON CONFLICT(slug) DO UPDATE SET`,
    `  title = excluded.title,`,
    `  envelope = excluded.envelope,`,
    `  updated_at = excluded.updated_at;`,
    '',
  ].join('\n')

  const sqlPath = path.resolve(ROOT, outPath)
  fs.mkdirSync(path.dirname(sqlPath), { recursive: true })
  fs.writeFileSync(sqlPath, sql, 'utf8')
  console.log(`[seed-share] wrote SQL: ${outPath}`)

  // 如果带了 --apply，直接调 wrangler 写到 remote D1
  if (flags.apply) {
    console.log('[seed-share] applying to remote D1 via wrangler…')
    const result = spawnSync(
      'npx',
      ['wrangler', 'd1', 'execute', 'tuaran-me', '--remote', `--file=${outPath}`],
      { stdio: 'inherit' }
    )
    if (result.status !== 0) {
      console.error('[seed-share] wrangler failed')
      process.exit(result.status || 1)
    }
    console.log('[seed-share] applied.')
    console.log('')
    console.log('Share link (with password):')
    console.log(`  https://2aran.com/share/${slug}#${encodeURIComponent(password)}`)
    console.log('Share link (without password):')
    console.log(`  https://2aran.com/share/${slug}`)
  } else {
    console.log('')
    console.log('Next:')
    console.log(`  npx wrangler d1 execute tuaran-me --remote --file=${outPath}`)
    console.log('')
    console.log('After apply, the share link will be:')
    console.log(`  https://2aran.com/share/${slug}#${encodeURIComponent(password)}`)
  }
}

main().catch((err) => {
  console.error('[seed-share] error:', err)
  process.exit(1)
})
