/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/workbuddy-sms-relay/wrangler.jsonc --include-runtime=false workers/workbuddy-sms-relay/worker-configuration.d.ts` (hash: 9ed1f7a129c752817d06c445da3b7d85)
interface __BaseEnv_Env {
	DB: D1Database;
	SMS_PROVIDER: "tencent";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SMS_PROVIDER">> {}
}
